### ISSUE TITLE
能否支持spring security原生注解

### ISSUE THREAD

**Issue by sm1ple** [dromara/Sa-Token#100]
1.@PreAuthorize等原生注解支持
2.支持SecurityContextHolder.getContext().getAuthentication()获取登陆信息
3.支持短信验证码登陆，邮箱登陆等。

**Comment by click33** [comment]
问题1：Sa-Token提供了对应的注解：@SaCheckLogin、@SaCheckPermission 等，详细参考：http://sa-token.dev33.cn/doc/index.html#/use/at-check
问题2：在Sa-Token中可以使用 StpUtil.getLoginId() 获取账号信息
问题3：不支持
