### ISSUE TITLE
多账号验证+JWT整合方式有整合或者示例吗

### ISSUE THREAD

**Issue by GabbyMrH** [dromara/Sa-Token#101]
我看到官网有多账号整合，也看到了官网有JWT的示例（虽然这个JWT整合看起来有点一言难尽）。请问作者这边可否加上多账号验证+整合JWT的方式示例呀？

**Comment by GabbyMrH** [comment]
补充一些，这个写法也过期了，作者4个月没更新了：https://gitee.com/click33/sa-plus/blob/master/sp-server/src/main/java/com/pj/current/satoken/StpUserUtil.java

**Comment by click33** [comment]
整合jwt就是替换了StpLogic逻辑内核，在多账号模式下直接 StpUserUtil.stpLogic = xxx 来改就行了

**Comment by GabbyMrH** [comment]
> 整合jwt就是替换了StpLogic逻辑内核，在多账号模式下直接 StpUserUtil.stpLogic = xxx 来改就行了

嗯，我实现好了。如果需要提供代码示例的话，我很乐意提供☺️
