### ISSUE TITLE
集成redis后，redis中有不过期的tokenSession

### ISSUE THREAD

**Issue by lorkoy** [dromara/Sa-Token#102]
使用redis保存token,
token设置activity-timeout过期时间为1小时，
timeout为1天，
但是redis中会存在过期时间为-1的tokenSession

![image](https://user-images.githubusercontent.com/3382710/125912649-df718af3-95d3-4a60-8b1e-0733cec38783.png)
![image](https://user-images.githubusercontent.com/3382710/125912713-3dfe6c50-49c9-460d-b14d-962fd4348085.png)

**Comment by click33** [comment]
数据全部清除，重新测试一下
如果还有这个情况，提供一个复现步骤
