### ISSUE TITLE
生成 Java doc 文档

### ISSUE THREAD

**Issue by bravelionet** [dromara/Sa-Token#105]
sa-token 你好
     非常高兴在这里认识你, sa-token很强大且官方文档也很完善,  sa-token正在快速发展, 当下载源码进行学习时发现, 源码注释很清晰,  在官方寻找后没有生成 doc,  社区工作者可以生成 Java Doc 方便社区更近一步方便学习.

**Comment by click33** [comment]
不好意思没太明白您的意思
您是指源码里的javadoc格式的注释吗？这个是有的，
如果您在开发中只能看到源码不能看到注释可能是因为maven没有下载完毕source.jar源码
如果您指的是使用javadoc编译出来的API文档，我觉得这个必要性不是很大，毕竟官网的文档已经比较详细了，需要API文档的同学也可以自己手动编译
还是没太明白您说的 Java Doc 具体指的是什么，希望详细阐述一下
