### ISSUE TITLE
建议StpUtil添加几个方法

### ISSUE THREAD

**Issue by initchen** [dromara/Sa-Token#110]
StpUtil.hasRole和StpUtil.hasPermission方法只能一次判断一个角色或权限, 建议添加一个类似StpUtil.hasAnyRole(role1, role2...)和StpUtil.hasAllRole(rorle1, role2...)方法方便调用, 不然判断几个角色或权限的时候发现有点小繁琐.

**Comment by click33** [comment]
这里能解决你的问题不，骚年.

![image](https://user-images.githubusercontent.com/36243476/126925932-1eabbed2-b486-4bf8-905d-01fdc3d611b0.png)
