### ISSUE TITLE
webflux集成SaReactorFilter 中无法获取自定义配置信息的问题

### ISSUE THREAD

**Issue by wcp1230** [dromara/Sa-Token#111]
webflux集成SaReactorFilter 中，初始化时无法获取到配置文件中自定义配置的白名单信息；
是否可以考虑 SaReactorFilter implements  InitializingBean 实现afterPropertiesSet 方法， 把构造函数中的相关初始化代码放到afterPropertiesSet 方法中

**Comment by click33** [comment]
“webflux集成SaReactorFilter 中，初始化时无法获取到配置文件中自定义配置的白名单信息；” 中提到的“初始化”是指什么时候？
可不可以来个详细说明，现在的处理方式有哪些局限
