### ISSUE TITLE
前后端分离，使用路由拦截无法进行登录认证

### ISSUE THREAD

**Issue by tiaotiaopig** [dromara/Sa-Token#112]
> 1. 配置了路由拦截器，使用了自定义头，进行satoken传递
> 2. 但是带有自定义头部的跨域请求是复杂请求，会分两次请求，在预请求中不会携带自定义头satoken，但是会被拦截，导致报错：未提供token，controller中的方法不会执行
> 3. 基于以上，自定义请求头的方法行不通啊，是我的用法有问题吗？

**Comment by click33** [comment]
判断option请求直接返回就行了
https://gitee.com/click33/sa-plus/blob/master/sp-server/src/main/java/com/pj/current/CorsFilter.java

**Comment by tiaotiaopig** [comment]
太感谢啦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/Sa-Token"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/Sa-Token] 前后端分离，使用路由拦截无法进行登录认证 (#112)





 
判断option请求直接返回就行了
 https://gitee.com/click33/sa-plus/blob/master/sp-server/src/main/java/com/pj/current/CorsFilter.java
