### ISSUE TITLE
网关鉴权写法很麻烦

### ISSUE THREAD

**Issue by wlb632363** [dromara/Sa-Token#113]
网关统一鉴权的方式需要每个权限都声明，若微服务接口特别多，这种方式会导致代码很多吧， 还有注解权限的方式是否也就不能用了

![image](https://user-images.githubusercontent.com/30819363/127299279-59ed2ccb-e88a-4563-b0df-1b6efa5bfaf1.png)

**Comment by click33** [comment]
所以如果你的服务权限粒度比较细的话，还是服务内部各自鉴权号一点

**Comment by wlb632363** [comment]
> 所以如果你的服务权限粒度比较细的话，还是服务内部各自鉴权号一点

那这个框架中哪个场景比较适合这种细粒度（接口级）的权限校验

**Comment by click33** [comment]
鉴权粒度从高到底：
路由拦截鉴权 -> 注解鉴权 -> 代码鉴权

**Comment by click33** [comment]
网关那里鉴权只能用路由拦截鉴权，所以想要更细粒度的只能内部服务注解鉴权或代码鉴权了

**Comment by wlb632363** [comment]
> 网关那里鉴权只能用路由拦截鉴权，所以想要更细粒度的只能内部服务注解鉴权或代码鉴权了

服务内部自己鉴权的话，需要怎么改造，让网关传递token之类的信息吗

**Comment by click33** [comment]
对，需要把 token 从网关传递到内部服务

**Comment by wlb632363** [comment]
> 对，需要把 token 从网关传递到内部服务

有什么格式要求吗，然后微服务内部就按照单体应用去配置就行了是吗，还有这种和 Id-Token这个模块一样吗

**Comment by click33** [comment]
没什么格式要求，传过去就行了
这个和 Id-Token 不一样 
这里传递的是 代表用户身份信息的 token
 Id-Token 是解决的 内部服务外网隔离的问题

**Comment by wlb632363** [comment]
> token

了解了，感谢这么详细的解答

**Comment by click33** [comment]
不客气，点个star再走吧

**Comment by wlb632363** [comment]
> 不客气，点个star再走吧

好的，还有个问题就是当前网关统一鉴权的话，没有封装微服务里获取当前登录用户的相关信息的方法，这种应该比较常用，可以作为框架中和id-token那样的模块

**Comment by click33** [comment]
其实加个过滤器透传一下token也就十几行代码的事情，不过你说的这个点也确实可以整合到框架中，下个版本会考虑一下

**Comment by YoungTakhin** [comment]
同样的需求，我也觉得网关鉴权不太友好
