### ISSUE TITLE
接口签名认证

### ISSUE THREAD

**Issue by yuanweiGit** [dromara/Sa-Token#116]
接口签名认证的有吗

**Comment by click33** [comment]
什么样的签名认证？

**Comment by yuanweiGit** [comment]
restful接口签名 接口安全认证 



***@***.***
 
发件人： click33
发送时间： 2021-08-04 16:00
收件人： dromara/Sa-Token
抄送： 苑伟; Author
主题： Re: [dromara/Sa-Token] 接口签名认证 (#116)
什么样的签名认证？
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by click33** [comment]
说的太笼统了，是前后端的身份鉴权，还是内部服务接口调用鉴权
<这两种目前都有了，可以详细看一下文档>

**Comment by yuanweiGit** [comment]
内部服务接口调用鉴权 部门之间服务调用



***@***.***
 
发件人： click33
发送时间： 2021-08-04 16:30
收件人： dromara/Sa-Token
抄送： 苑伟; Author
主题： Re: [dromara/Sa-Token] 接口签名认证 (#116)
说的太笼统了，是前后端的身份鉴权，还是内部服务接口调用鉴权
<这两种目前都有了，可以详细看一下文档>
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by click33** [comment]
参考 Id-Token 模块
