### ISSUE TITLE
怎么在sa-token环境下进行单元测试

### ISSUE THREAD

**Issue by martinou** [dromara/Sa-Token#120]

**Comment by click33** [comment]
参考：
https://github.com/dromara/Sa-Token/blob/dev/sa-token-starter/sa-token-spring-boot-starter/src/test/java/com/pj/test/SaTokenSpringBootStarterTest.java

**Comment by martinou** [comment]
我希望是在和spring webmvc一起做的单元测试。您给的demo只是satoken自己的单元测试。谢谢
