### ISSUE TITLE
gateway webflux 装饰器模式下提示未成功初始化上下文

### ISSUE THREAD

**Issue by llm163520** [dromara/Sa-Token#121]
![error](https://user-images.githubusercontent.com/22343834/129466030-6ca887ad-4537-46ce-a1b2-52a03f0e2091.png)
参考图例
伪代码
@Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        ServerHttpResponse response = exchange.getResponse();
        Long requestStartTime = System.currentTimeMillis();
        ServerRequest serverRequest = ServerRequest.create(exchange, codecConfigurer.getReaders());
        Mono<String> modifiedBody = serverRequest.bodyToMono(String.class).flatMap(body -> Mono.just(body));
        BodyInserter bodyInserter = BodyInserters.fromPublisher(modifiedBody, String.class);
        HttpHeaders headers = new HttpHeaders();
        headers.putAll(request.getHeaders());
        CachedBodyOutputMessage outputMessage = new CachedBodyOutputMessage(exchange, headers);
        // 写入全局上下文 (同步)
        SaReactorSyncHolder.setContent(exchange);
        return bodyInserter.insert(outputMessage, new BodyInserterContext()).then(Mono.defer(() -> {
                return chain.filter(exchange.mutate().request(new ServerHttpRequestDecorator(exchange.getRequest()) {
                    @Override
                    public Flux<DataBuffer> getBody() {
                        return outputMessage.getBody();
                    }

                    @Override
                    public HttpHeaders getHeaders() {
                        return super.getHeaders();
                    }
                }).response(new ServerHttpResponseDecorator(exchange.getResponse()){
                    @Override
                    public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
                        //异常代码
                        StpUtil.getTokenInfo();
                        Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) body;
                        return super.writeWith(fluxBody.buffer().map(dataBuffers -> {
                            //异常代码
                            StpUtil.getTokenInfo();
                            DataBufferFactory dataBufferFactory = new DefaultDataBufferFactory();
                            DataBuffer join = dataBufferFactory.join(dataBuffers);
                            byte[] content = new byte[join.readableByteCount()];
                            join.read(content);
                            DataBufferUtils.release(join);
                            HttpHeaders headers = getDelegate().getHeaders();
                            headers.putIfAbsent(HttpHeaders.CONTENT_LENGTH, Lists.newArrayList(content.length + ""));
                            return getDelegate().bufferFactory().wrap(content);
                        })).subscriberContext(ctx -> {
                            // 写入全局上下文 (异步)
                            ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
                            return ctx;
                        }).doFinally(r -> {
                            // 清除上下文
                            SaReactorSyncHolder.clearContent();
                        });
                    }
                }).build()).subscriberContext(ctx -> {
                    // 写入全局上下文 (异步)
                    ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
                    return ctx;
                }).doFinally(r -> {
                    // 清除上下文
                    SaReactorSyncHolder.clearContent();
                });
            }).subscriberContext(ctx -> {
                // 写入全局上下文 (异步)
                ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
                return ctx;
            }).doFinally(r -> {
                // 清除上下文
                SaReactorSyncHolder.clearContent();
            }));
    }

**Comment by click33** [comment]
贴的代码太乱了 你重新整理一下

**Comment by llm163520** [comment]
@override
public Mono filter(ServerWebExchange exchange, WebFilterChain chain) {
	ServerHttpRequest request = exchange.getRequest();
	ServerHttpResponse response = exchange.getResponse();
	Long requestStartTime = System.currentTimeMillis();
	ServerRequest serverRequest = ServerRequest.create(exchange, codecConfigurer.getReaders());
	Mono modifiedBody = serverRequest.bodyToMono(String.class).flatMap(body -> Mono.just(body));
	BodyInserter bodyInserter = BodyInserters.fromPublisher(modifiedBody, String.class);
	HttpHeaders headers = new HttpHeaders();
	headers.putAll(request.getHeaders());
	CachedBodyOutputMessage outputMessage = new CachedBodyOutputMessage(exchange, headers);
	// 写入全局上下文 (同步)
	SaReactorSyncHolder.setContent(exchange);
	return bodyInserter.insert(outputMessage, new BodyInserterContext()).then(Mono.defer(() -> {
		return chain.filter(exchange.mutate().request(new ServerHttpRequestDecorator(exchange.getRequest()) {
			@override
			public Flux getBody() {
				return outputMessage.getBody();
			}

			@Override
			public HttpHeaders getHeaders() {
				return super.getHeaders();
			}
		}).response(new ServerHttpResponseDecorator(exchange.getResponse()){
			@Override
			public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
				//异常代码
				StpUtil.getTokenInfo();
				Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) body;
				return super.writeWith(fluxBody.buffer().map(dataBuffers -> {
					//异常代码
					StpUtil.getTokenInfo();
					DataBufferFactory dataBufferFactory = new DefaultDataBufferFactory();
					DataBuffer join = dataBufferFactory.join(dataBuffers);
					byte[] content = new byte[join.readableByteCount()];
					join.read(content);
					DataBufferUtils.release(join);
					HttpHeaders headers = getDelegate().getHeaders();
					headers.putIfAbsent(HttpHeaders.CONTENT_LENGTH, Lists.newArrayList(content.length + ""));
					return getDelegate().bufferFactory().wrap(content);
				})).subscriberContext(ctx -> {
					// 写入全局上下文 (异步)
					ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
					return ctx;
				}).doFinally(r -> {
					// 清除上下文
					SaReactorSyncHolder.clearContent();
				});
			}
		}).build()).subscriberContext(ctx -> {
			// 写入全局上下文 (异步)
			ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
			return ctx;
		}).doFinally(r -> {
			// 清除上下文
			SaReactorSyncHolder.clearContent();
		});
	}).subscriberContext(ctx -> {
		// 写入全局上下文 (异步)
		ctx = ctx.put(SaReactorHolder.CONTEXT_KEY, exchange);
		return ctx;
	}).doFinally(r -> {
		// 清除上下文
		SaReactorSyncHolder.clearContent();
	}));
}

**Comment by llm163520** [comment]
![QQ图片20210815151951](https://user-images.githubusercontent.com/22343834/129470423-61aa4a43-425e-4dc4-8f23-9385c40e8edf.png)
调整好的，上传上来格式不对呢

**Comment by Xiong-qi** [comment]
解决方案没写？

**Comment by Xiong-qi** [comment]
请一下问解决方案是？ @llm163520 @click33

**Comment by llm163520** [comment]
> 请一下问解决方案是？ @llm163520 @click33

我这边也暂时未解决

**Comment by Xiong-qi** [comment]
> > 请一下问解决方案是？ @llm163520 @click33
> 
> 我这边也暂时未解决

我的场景和你类型，在gateway的filter中获取登录的用户。我现在的解决的思路是，获取头的token，注入satoken的SaTokenDaoRedisJackson。通过redis存储获取。

**Comment by llm163520** [comment]
> > > 请一下问解决方案是？ @llm163520 @click33
> > 
> > 
> > 我这边也暂时未解决
> 
> 我的场景和你类型，在gateway的filter中获取登录的用户。我现在的解决的思路是，获取头的token，注入satoken的SaTokenDaoRedisJackson。通过redis存储获取。

这样也是一直办法，如果原生API能支持的话就更好了
