### ISSUE TITLE
过期Token的处理问题

### ISSUE THREAD

**Issue by wapearoudy** [dromara/Sa-Token#123]
用了Redis的方式持久化认证信息，调试的时候发现，超时过期的Token不会修改状态，Redis中存放的还是用户ID，再次登录后，旧的Token中存放的数据变成了-4，运行一段时间之后库里会有一大堆值为-4的Token

**Comment by click33** [comment]
把允许并发登录打开就没这个问题了

**Comment by java-lyf** [comment]
> 把允许并发登录打开就没这个问题了

每个服务里面都有websocket，然后通过token授权校验，将并发登录关掉了，然后通过getLoginIdByToken获取用户id的时候，就会出现-4，有没有别的解决方案啊
