### ISSUE TITLE
StpInterface权限集合getPermissionList

### ISSUE THREAD

**Issue by wlb632363** [dromara/Sa-Token#124]
当需要获取登录用户的权限集合时候，采用 [账号id -> 角色id -> 权限列表] 的缓存模型
可是getPermissionList函数定义的入参确是loginId（账号id），导致每次都需要在这个函数中获取角色id，再获取权限列表，多了一层转换
是否应该设计成入参为角色id，然后我们程序中可以用一个hashMap(key为角色id，value为权限集合)，这样就可以快速返回用户的权限列表，如果入参是用户id，则无法用map作为内存缓存（因为若项目大，则用户太多，内存爆炸，而角色一般不会太多）

![image](https://user-images.githubusercontent.com/30819363/129883350-7b62af1a-b1ab-4d00-be90-24857d63ff05.png)

**Comment by click33** [comment]
这个可以参考官网示例做两层缓存 [账号id -> 角色id -> 权限列表]  
入参不能修改为角色ID，因为不是所有的项目都是RBAC模型的

**Comment by wlb632363** [comment]
> 这个可以参考官网示例做两层缓存 [账号id -> 角色id -> 权限列表]
> 入参不能修改为角色ID，因为不是所有的项目都是RBAC模型的

getPermissionList(Object loginId, String loginKey)
请问logingKey参数是在哪个地方定义的

**Comment by wlb632363** [comment]
![image](https://user-images.githubusercontent.com/30819363/129994684-1ba04ebc-1a9e-48d8-964e-4c2e3b7f7c11.png)
控制台的sa-token的logo打印能去掉吗

**Comment by zhangrw** [comment]
> ![image](https://user-images.githubusercontent.com/30819363/129994684-1ba04ebc-1a9e-48d8-964e-4c2e3b7f7c11.png)
> 控制台的sa-token的logo打印能去掉吗

sa-token.is-print = false
参见: [官方文档 - 常用类、方法 - safoxutil](https://sa-token.dev33.cn/doc/index.html#/more/common-action?id=safoxutil)
