### ISSUE TITLE
oauth2模式下的access_token和前后端分离下的token

### ISSUE THREAD

**Issue by wlb632363** [dromara/Sa-Token#125]
项目为前后端分离，使用oauth2调用登录之后，怎么返回请求接口的sa-token（没有token调用其他接口，会被拦截没有登录），还有这个token是否和access_token在一起是否冗余了

**Comment by wlb632363** [comment]
当成功获取到oauth2的access_token之后，可否不用传入sa-token请求头，只传access_token

**Comment by click33** [comment]
access_token 是解决第三方授权的 和这个 satoken 没关系  
两者不能混用

**Comment by wlb632363** [comment]
> access_token 是解决第三方授权的 和这个 satoken 没关系
> 两者不能混用

那开放给oauth2三方应用的接口是不是就不能对用户进行鉴权，得直接放行？

**Comment by click33** [comment]
开放给 OAuth2 三方应用的接口你鉴 access_token 的权不就行了

**Comment by wlb632363** [comment]
> 开放给 OAuth2 三方应用的接口你鉴 access_token 的权不就行了

就是路由直接放过，然后直接在接口中对access_token 进行鉴权吗，和另外路由中SaRouter.match的鉴权要分开是吗

**Comment by click33** [comment]
对

**Comment by wlb632363** [comment]
> 对

如果需要开放给三方应用的服务很多接口的话，那是不是又得再自己起一个鉴权的流程，会不会和原来配置好的就有点冗余了，本来想的是oauth2登录的也是系统的账号，然后access_token的鉴权也用的配置好的sa-token那套，这样看来是不能这样子兼容吗

**Comment by click33** [comment]
开放给自己系统的接口和开放给第三方的接口，肯定得分两套写，虽然这两套接口部分可以重用，但是还是分开设计比较好
自己系统的就 satoken 鉴权，第三方接口的用 access_token 鉴权，两者互不干扰，最好是分成两个独立的项目

**Comment by wlb632363** [comment]
> access_token 鉴权

access_token 鉴权的话是否需要自己实现，后续sa-token能否支持直接路由配置下鉴权或者提供一些工具类，就不用自己写filter或者在接口中鉴权了

**Comment by click33** [comment]
目前 OAuth2 模块提供的鉴权方法有：

``` java
// 校验：指定 Access-Token 是否具有指定 Scope
SaOAuth2Util.checkScope(accessToken, scopes);
```

整体来讲不如 StpUtil  模块带有各种注解鉴权、URL鉴权等等，目前仅支持在接口中使用上述方法进行 代码鉴权 

可参考文档：http://sa-token.dev33.cn/doc/index.html#/oauth2/oauth2-dev
整体功能参考源码：https://gitee.com/dromara/sa-token/blob/dev/sa-token-plugin/sa-token-oauth2/src/main/java/cn/dev33/satoken/oauth2/logic/SaOAuth2Util.java

**Comment by wlb632363** [comment]
> ```java
> checkScope
> ```

其实鉴权方面是否可以考虑下加入 **应用** 的维度
像ocp开源项目里，权限鉴权那块，可以给不同的应用分配对应的服务
![image](https://user-images.githubusercontent.com/30819363/130173029-3198bdd5-3b98-439e-96a2-631eb74dc188.png)

**Comment by click33** [comment]
是指不同 Client 拥有不同权限的功能吗，如果是的话在 Sa-OAuth2 中有体现
![image](https://user-images.githubusercontent.com/36243476/130173354-f83d0341-5e30-4879-be0f-a6e4edd08323.png)

**Comment by wlb632363** [comment]
> 是指不同 Client 拥有不同权限的功能吗，如果是的话在 Sa-OAuth2 中有体现
> ![image](https://user-images.githubusercontent.com/36243476/130173354-f83d0341-5e30-4879-be0f-a6e4edd08323.png)

对的，但是在sa-token不涉及oauth2那块鉴权上是否可以也考虑进Client的维度，这样的话其实oauth2接入的话就可以根据client来复用原来的鉴权，是否也就不用分成两套token来鉴权了，只要根据token对应的client就可以区分三方应用还是自己平台

**Comment by click33** [comment]
"只要根据token对应的client就可以区分三方应用还是自己平台" 
你说的这种功能，如果 Sa-Token 一开始就拿OAuth2模式  来搞单体项目授权认证的话，是可以实现的
但是 Sa-Token 从第一个版本开始就不是走的这一套模式，OAuth2.0 只是其中一个衍生模块，是为了搭建像QQ那样的标准第三方授权平台开发的
如果你想拿OAuth2.0模式搞单体系统的鉴权的话，还是 SpringOAuth2.0 用着舒服一点

**Comment by click33** [comment]
另外，这种模式，Sa-Token 在未来版本有计划加入 ，但是目前还不支持

**Comment by wlb632363** [comment]
> 另外，这种模式，Sa-Token 在未来版本有计划加入 ，但是目前还不支持

好的，了解了，感谢耐心的回复
