### ISSUE TITLE
activity-timeout和timeout选择问题

### ISSUE THREAD

**Issue by wlb632363** [dromara/Sa-Token#126]
系统中一般需要设置token过期时间，用的timeout设置没法续签，会出现用户明明在做操作，却突然退出登录
用activity-timeout续签功能，需要将timeout设置永久，又会有个问题就是当token过期之后，token对应的值还会存在redis之中，占用内存

**Comment by click33** [comment]
担心内存问题，timeout可以不设置-1，设置个比较长的时间就行了，比如一个月、两个月、或半年，
国内很多大厂网站都是每隔一两个月就需要再次登录一次的
只要这个值不是很短、30分钟或者两小时，对用户体验影响不大

**Comment by wlb632363** [comment]
> 担心内存问题，timeout可以不设置-1，设置个比较长的时间就行了，比如一个月、两个月、或半年，
> 国内很多大厂网站都是每隔一两个月就需要再次登录一次的
> 只要这个值不是很短、30分钟或者两小时，对用户体验影响不大

设置时间长好像也不行吧，比如我设置为2天，用户也一直在操作，所以token一直没有过期，所以用户也不需要重新登录，可是在两天后用户刚刚操作还好好的，提交下东西，token恰好时间到了，突然发现退出登录了，这不太友好吧
不理解的是为什么不设计成一个超时时间就好，要永久就设置-1，若设置超时时间，就进行续签，不更简单一些吗

**Comment by click33** [comment]
"不理解的是为什么不设计成一个超时时间就好，要永久就设置-1，若设置超时时间，就进行续签，不更简单一些吗"
你把 timeout 和 active-timeout 都设置为-1 就是前半句的效果
你把 timeout=-1   active-timeout=xxx   就是续签效果

**Comment by WheelerLee** [comment]
解决了吗 @wlb632363
