### ISSUE TITLE
在springcloud gateway下，跨域问题

### ISSUE THREAD

**Issue by zhaneven** [dromara/Sa-Token#133]
使用gateway配置文件配置跨域，由于SaReactorFilter设置了order，导致优先于gateway本身的跨域处理，结果未登录情况下SaReactorFilter直接进行了返回，没有走gateway的跨域处理，这种情况下应该如何处理？

**Comment by click33** [comment]
你也设置个order 值为-200

**Comment by zhaneven** [comment]
> 你也设置个order 值为-200

那就是我也只能用手写过滤器的形式处理跨域，不能使用gateway直接在配置文件里配置跨域了

**Comment by click33** [comment]
是的

**Comment by qq229338869** [comment]
> 使用gateway配置文件配置跨域，由于SaReactorFilter设置了order，导致优先于gateway本身的跨域处理，结果未登录情况下SaReactorFilter直接进行了返回，没有走gateway的跨域处理，这种情况下应该如何处理？

SaReactorFilter可以不设置order吗？

**Comment by click33** [comment]
你注册过滤器的方法上也可以加 Order 注解，这里的值 会覆盖掉 源码里的值
