### ISSUE TITLE
SaTokenException在@RestControllerAdvice全局异常处理处理中捕获不到

### ISSUE THREAD

**Issue by baikingrio** [dromara/Sa-Token#137]
按文档中的多账号验证方式将StpUtil.java类的全部代码复制粘贴到 StpUserUtil.java里，之后在StpUserUtil中出现的SaTokenException都在全局异常处理中无法捕获到。
![image](https://user-images.githubusercontent.com/3849855/131087334-c2251e35-f6fb-4bfa-9640-21feb9c5c79f.png)

**Comment by son3ofSatan** [comment]
css/theme/template/exposer.scss
