### ISSUE TITLE
SaToken 发起一个新的请求 是否重置redis中的失效时间

### ISSUE THREAD

**Issue by Scroogeds** [dromara/Sa-Token#138]

**Comment by click33** [comment]
没太读懂题意，可否再详细说明一下

**Comment by Scroogeds** [comment]
用户不断操作的时候,redis中token失效时间还是按登陆时候的时间减少,如何按最后一次操作的时间重置redis中的失效时间

**Comment by son3ofSatan** [comment]
h![image](https://user-images.githubusercontent.com/58794659/131605380-72cf193f-e3bd-4506-91cd-7f9331cec778.png)

**Comment by click33** [comment]
active-timeout 就是干这个事的，你看看文档 框架配置 那一块

**Comment by Scroogeds** [comment]
我使用的是**1.21.0**
sa-token:
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3600

登陆进去,调用其他的接口的,带token 的,redis中ttl时间并没有变化

**Comment by Scroogeds** [comment]
就是我应该把timeout的时间设置的大点?
activity-timeout规定时间没操作,token相当于失效的?

**Comment by click33** [comment]
是的

**Comment by click33** [comment]
续签默认开启，只要 active-timeout 配置的值大于0  就会自动不断续签

**Comment by click33** [comment]
要是没有疑问了 就 close issues 吧
