### ISSUE TITLE
Dubbo服务调用中无法获取上下文

### ISSUE THREAD

**Issue by qudonghui** [dromara/Sa-Token#140]
在微服务架构中，网关调用服务A，服务A 通过Dubbo 调用服务B，提示
cn.dev33.satoken.exception.SaTokenException: 非Web上下文无法获取Request
![I1NOR F3K0SLOE9 _97U2{V](https://user-images.githubusercontent.com/39752827/131602166-2b14cb86-1862-4740-899e-5b4768a45670.jpg)

**Comment by click33** [comment]
上下文处理暂未适配dubbo，你可以把需要用到的值先从调用方取出来，再通过参数传递给被调用方

**Comment by ZJM6658** [comment]
如果并非取值呢，而是封禁、解封用户这类操作怎么处理呢

> 上下文处理暂未适配dubbo，你可以把需要用到的值先从调用方取出来，再通过参数传递给被调用方
