### ISSUE TITLE
sa-token既然处理登录以及权限管控方面，那么能否把登录场景中常用的验证码逻辑也给集成进来呢

### ISSUE THREAD

**Issue by 195070811** [dromara/Sa-Token#141]
目前登录场景经常会用到验证码，可否考虑集成验证码逻辑到目前的框架中，并且内置开关，以及验证码类型选择。

**Comment by click33** [comment]
Sa-Token 不干预认证的具体方案，只做认证成功后的 token 颁发，你说的这个功能有过规划，可能以后的版本会增加相关扩展，但是短时间内应该不会支持

**Comment by ddxl123** [comment]
> Sa-Token 不干预认证的具体方案，只做认证成功后的 token 颁发，你说的这个功能有过规划，可能以后的版本会增加相关扩展，但是短时间内应该不会支持

我也需要这个功能，现在有没有在规划里面呢？
