### ISSUE TITLE
header中的tokenName和Redis存储的key，希望在配置上能够分开

### ISSUE THREAD

**Issue by itweixiang** [dromara/Sa-Token#142]
1、header的tokenName，一般是与前端协商而定，如我们常用的字面值为'token'，改这个值，不要太奇葩前端都可以接受

2、但是，redis不一样，redis作为服务器系统，key命名有一定的规范，如"集群名称"+":"+"业务名称"+":"+"模块名称"+":"+"具体存储的key"

结果：如果想要满足Redis的内部规范，那么返回给前端，tokenName的值会比较奇葩。所以希望代码在配置上能够区分开，之所以提出来，是因为在看源码时，相关代码，无法@Bean去覆盖，改动代价较高

**Comment by click33** [comment]
目前可以通过重写  splicingKeyXxx 方法 来达到目的，后续会出更简便的方法：
StpUtil.stpLogic = new StpLogic("logic"){
        // 重写所有 splicingKeyXxx 方法
        @Override
        public String splicingKeyTokenName() {
            return ...;
        }
        // ... 
}

**Comment by itweixiang** [comment]
我是重载了SaTokenDaoRedis，自己搞了redis的key进去。后续版本可以考虑支持一下

**Comment by itweixiang** [comment]
我是重写了SaTokenDaoRedis，自己搞了redis的key进去。后续版本可以考虑支持一下

**Comment by itweixiang** [comment]
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: "token"
  redis-prefix: "ydata:user"


@Primary
@Component
public class YDataSaTokenDaoRedis extends SaTokenDaoRedis {
    public StringRedisTemplate stringRedisTemplate;
    public RedisTemplate<String, Object> objectRedisTemplate;
    public boolean isInit;

    @Value("${sa-token:redis-prefix}")
    public String redisPrefix;


    @Autowired
    public void init(RedisConnectionFactory connectionFactory) {
        super.init(connectionFactory);
    }

    private String getKey(String key) {
        return redisPrefix + ":" + key;
    }


    public String get(String key) {
        return super.get(getKey(key));
    }

    public void set(String key, String value, long timeout) {
        super.set(getKey(key), value, timeout);
    }

    public void update(String key, String value) {
        super.update(getKey(key), value);
    }

    public void delete(String key) {
        super.delete(getKey(key));
    }

    public long getTimeout(String key) {
        return super.getTimeout(getKey(key));
    }

    public void updateTimeout(String key, long timeout) {
        super.updateTimeout(getKey(key), timeout);
    }

    public Object getObject(String key) {
        return super.getObject(getKey(key));
    }

    public void setObject(String key, Object object, long timeout) {
        super.setObject(getKey(key), object, timeout);
    }

    public void updateObject(String key, Object object) {
        super.updateObject(getKey(key), object);
    }

    public void deleteObject(String key) {
        super.deleteObject(getKey(key));
    }

    public long getObjectTimeout(String key) {
        return super.getObjectTimeout(getKey(key));
    }

    public void updateObjectTimeout(String key, long timeout) {
        super.updateObjectTimeout(getKey(key), timeout);
    }

    public List<String> searchData(String prefix, String keyword, int start, int size) {
        return super.searchData(getKey(prefix), keyword, start, size);
    }
}

**Comment by itweixiang** [comment]
sa-token:
  token-name: "token"
  redis-prefix: "ydata:user"


@Primary
@Component
public class YDataSaTokenDaoRedis extends SaTokenDaoRedis {
    public StringRedisTemplate stringRedisTemplate;
    public RedisTemplate<String, Object> objectRedisTemplate;
    public boolean isInit;

    @Value("${sa-token:redis-prefix}")
    public String redisPrefix;


    @Autowired
    public void init(RedisConnectionFactory connectionFactory) {
        super.init(connectionFactory);
    }

    private String getKey(String key) {
        return redisPrefix + ":" + key;
    }


    public String get(String key) {
        return super.get(getKey(key));
    }

    public void set(String key, String value, long timeout) {
        super.set(getKey(key), value, timeout);
    }

    public void update(String key, String value) {
        super.update(getKey(key), value);
    }

    public void delete(String key) {
        super.delete(getKey(key));
    }

    public long getTimeout(String key) {
        return super.getTimeout(getKey(key));
    }

    public void updateTimeout(String key, long timeout) {
        super.updateTimeout(getKey(key), timeout);
    }

    public Object getObject(String key) {
        return super.getObject(getKey(key));
    }

    public void setObject(String key, Object object, long timeout) {
        super.setObject(getKey(key), object, timeout);
    }

    public void updateObject(String key, Object object) {
        super.updateObject(getKey(key), object);
    }

    public void deleteObject(String key) {
        super.deleteObject(getKey(key));
    }

    public long getObjectTimeout(String key) {
        return super.getObjectTimeout(getKey(key));
    }

    public void updateObjectTimeout(String key, long timeout) {
        super.updateObjectTimeout(getKey(key), timeout);
    }

    public List<String> searchData(String prefix, String keyword, int start, int size) {
        return super.searchData(getKey(prefix), keyword, start, size);
    }
}
