### ISSUE TITLE
微服务架构整合了nacos的依赖找不到视图

### ISSUE THREAD

**Issue by lionelkali** [dromara/Sa-Token#143]
`cfg.sso
// 配置：未登录时返回的View 
.setNotLoginView(() -> {
    return new ModelAndView("xxx.html");
})`

这里重定向到 服务认证端给出的视图在整合了nacos之后，找不到视图，有什么好的解决办法吗
具体依赖版本如下
<spring.cloud-version>Hoxton.SR11</spring.cloud-version>
<alibaba.cloud.version>2.2.5.RELEASE</alibaba.cloud.version>
<boot.version>2.2.13.RELEASE</boot.version>

**Comment by click33** [comment]
这，，，，，，
提供的信息太少了，没法给你解决，你不如搭建个复现的demo 再给你调试

**Comment by lionelkali** [comment]
问题已经解决了。是cloud 和 boot 版本的问题
