### ISSUE TITLE
支持动态资源控制? 数据权限控制？

### ISSUE THREAD

**Issue by SYanalyser** [dromara/Sa-Token#144]

**Comment by click33** [comment]
支持动态资源控制
不支持数据权限（这是ORM框架的事情）

**Comment by SYanalyser** [comment]
文档 https://sa-token.dev33.cn/doc/index.html#/use/route-check?id=_3%e3%80%81%e5%ae%8c%e6%95%b4%e7%a4%ba%e4%be%8b
路由拦截鉴权不是动态的吧？需要自己手动配置进去？

**Comment by click33** [comment]
里面是可以写任意代码的，你可以通过流程语句实现动态化

**Comment by zwdgit** [comment]
> 支持动态资源控制 不支持数据权限（这是ORM框架的事情）

请问如何动态资源控制，可以提供下参考文档吗
这里的动态控制能不能是在用户登录且获取过资源后，触发某些操作后进行资源的重新授权？
