### ISSUE TITLE
集成redis的连接池问题

### ISSUE THREAD

**Issue by HHHHhgqcdxhg** [dromara/Sa-Token#148]
hi, 我读了读sa-token的代码, 发现SaAloneRedisInject类里新建了个redis的连接池, 这样会有问题么, 比如本来就有一个redis连接池, 这里又建了一个, 会不会实际的连接数是配置的两倍了? 我理解应该优先复用spring里的redis的连接池

**Comment by click33** [comment]
你复用 Spring 的连接池还怎么做到给Sa-Token配置单独的 Redis

**Comment by click33** [comment]
你复用 Spring 的连接池还怎么做到给Sa-Token配置单独的 Redis
