### ISSUE TITLE
角色权限缓存模块

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#149]
### 使用版本:
1.26.0

### 报错信息：
无
对于StpInterface来说、如果不加上缓存支持，在进行接口压力测试时候效率较低
一般的业务情况是
用户授权修改很少会进行、属于查询多修改少情况

### 希望结果：
对于的实现、一般都是通过数据库或者

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
Sa-Token框架不内置缓存功能，你可以自己实现
至于不内置缓存实现的原因请参考：https://sa-token.dev33.cn/doc/index.html#/fun/jur-cache
