### ISSUE TITLE
同一个用户登陆多次session覆盖

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#150]
### 使用版本:
请提供一下版本号
1.26.0

### 报错信息：

在设置
  \# 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  \# 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
情况下、一个用户登陆多次、在redis中可以看到第二次登陆的session信息将第一次的替换掉了、如下图只有一个session信息了

![image](https://user-images.githubusercontent.com/24662536/133231121-dce91a58-4564-48ed-9362-a81a0ac59590.png)

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
不是替换掉了，两个客户端登录同一账号用的是同一个Session对象，可以参考一下.
https://sa-token.dev33.cn/doc/index.html#/use/session
