### ISSUE TITLE
非web环境调用时, 也应该返回预期结果

### ISSUE THREAD

**Issue by fangzhengjin** [dromara/Sa-Token#151]
### 场景
项目中有使用xxl-job任务调用, 任务执行过程中使用到了jpa的审计功能, 会自动填充数据中的操作人信息, 但是xxl-job调度时, 虽然代码都在一起,但是却获取不到web上下文信息, 所以会出现此异常

### 使用版本:
请提供一下版本号
v1.26.0

### 报错信息：

调用StpUtil.isLogin()时, 期望返回Boolean结果, 时间抛出异常

cn.dev33.satoken.exception.SaTokenException: 非Web上下文无法获取Request at cn.dev33.satoken.spring.SpringMVCUtil.getRequest(SpringMVCUtil.java:25)

### 希望结果：
无论底层是否抛出异常都应返回Boolean结果

**Comment by click33** [comment]
定时任务中应该避免 Sa-Token API 的调用

**Comment by fangzhengjin** [comment]
> 定时任务中应该避免 Sa-Token API 的调用

应该避免, 但可惜不是所有场景都能完美避开, 所以应该对一些基础方法, 比如 是否已登陆 返回预期结果

**Comment by click33** [comment]
StpUtil.isLogin()  是询问当前会话是否已登录
你得有个明确的访问人，框架才能校验是否已登录
在定时任务里，不是web上下文，根本没有会话概念，怎么判断一个会话是否已登录呢？

你不如调用Sa-Token-API之前先判断一下当前是不是web上下文，是web上下文再调

**Comment by tiro8183** [comment]
> 

怎么判断是否web上下文呢
