### ISSUE TITLE
user session并发安全问题

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#153]
### 使用版本:
请提供一下版本号
1.26.0

### 报错信息：
在集成过程中、阅读源代码 StpUtil.logout、如果使用redis存储session、在此将会删除对应的redis中token同时更新user session、将其中这一个token删除掉
在这里，是否会有可能发生并发安全问题、例如在此时，有这个user的另一个token同时logout、会导致最终的redis中token信息清除完、但是user session还是会保留一个token信息

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
考虑单机、集群后台使用中的并发安全问题

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
这个涉及到分布式锁的问题了，你说的问题确实存在，但是是比较小的概率发生（一般不会有同一个人对自己的账号同时又登录又注销，而且是同一时间），而且这个地方的tokenList并不是作为会话依据，只是个log记录，不会对整体逻辑产生影响

**Comment by baichangda** [comment]
在例如 getTokenValueListByLoginId 如果user session异常，会返回异常值

**Comment by baichangda** [comment]
是否可以考虑将usersession 改为 redis hash 结构？

**Comment by click33** [comment]
有考虑，这一块以后的版本肯定是会继续优化的
