### ISSUE TITLE
cookie获取没有解码

### ISSUE THREAD

**Issue by sunxingyuqaq** [dromara/Sa-Token#157]
### 使用版本:
请提供一下版本号
1.26.0

### 报错信息：
请提供报错的详细信息
获取不到cookie里面的token  空格变成了   %20

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址
![QQ图片20210917171010](https://user-images.githubusercontent.com/26001714/133757080-eb3aa612-1a41-446c-820e-96cef73c8b61.png)

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
Cookie 不支持空格字符
