### ISSUE TITLE
如何实现 springSecurity 那种 禁用 csrf和禁用session的功能

### ISSUE THREAD

**Issue by JavaLionLi** [dromara/Sa-Token#162]
### 使用版本:
请提供一下版本号
1.26.0

### 报错信息：
请提供报错的详细信息
![image](https://user-images.githubusercontent.com/31852897/134614664-a0395ecd-180e-4734-8939-a9dd025fe6c1.png)

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
如何使用satoken实现这种配置  如果无法实现  会不会有什么安全问题

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
Sa-Token 不操作 HttpSession ，本身就是关闭的

**Comment by JavaLionLi** [comment]
好的 多谢
