### ISSUE TITLE
在做AOP日志记录遇到的问题

### ISSUE THREAD

**Issue by lin11da** [dromara/Sa-Token#170]
请提供一下版本号
 v1.26.0

### 报错信息：
请提供报错的详细信息
并没有报错

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
我想知道在做AOP日志记录的时候
![图片](https://user-images.githubusercontent.com/68210427/135565785-56f1a939-bed8-48b5-8ff8-d02ca81694dd.png)
@AfterThrowing(value="execution(* com.example.config..*.*(..))",throwing="ex")
这个是怎么写的，报token不存在或者没有token的时候我想进去这个方法

复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址
也不算多麻烦，就是想知道切点在哪里wwwwwwwwwwwwww

备注：您提供的信息越充足，我们将越能快速的定位错误 
。

**Comment by click33** [comment]
这个你还是再搜搜百度吧，我也没试过这个

**Comment by yuebaix** [comment]
兄弟，这就是个切面，找到throw对应exception的工具类加个切面就好了，一般是实现了过滤器了，切面在过滤器外面就好了

**Comment by yuebaix** [comment]
而且你还可以用springboot的exceptionhandler，框架没吞掉异常，你就可以处理，因为那个异常处理在最外层
