### ISSUE TITLE
StpUtil.getLoginId()返回类型与登录时不一致的问题

### ISSUE THREAD

**Issue by MarcioXIN** [dromara/Sa-Token#172]
### 使用版本:
sa-token:v1.26.0

### 报错信息：
```
//自定义权限验证类登录
// id = 1
StpAdminUtil.login(loginCache.getId(), "web");
//获得LoginId的类型为"1",String类型
SaTokenInfo tokenInfo = StpAdminUtil.getTokenInfo();
tokenInfo.getLoginId()
```

### 希望结果：
传递进去什么类型,拿到就是什么类型

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
没办法，这个是为了抹平不同底层持久库差异而做的限制
要拿固定的类型可以调用 
StpUtil.getLoginIdAsInt()
StpUtil.getLoginIdAsLong()
StpUtil.getLoginIdAsString()
