### ISSUE TITLE
定义一个XssFilter，获取到的header内容为空

### ISSUE THREAD

**Issue by qiongbi9527** [dromara/Sa-Token#182]
### 使用版本:
请提供一下版本号
1.27.0

### 报错信息：
定义一个XssFilter之后,satoken提示未登录，发现request获取header的时候token为空了，不确定是否跟filter的顺序有关系

### 希望结果：
能正常获取header的内容

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
代码：

你希望的结果：

目前表现出来的结果：

**Comment by qiongbi9527** [comment]
我在gitee上传了一个自定义filter的测试例子，地址是：https://gitee.com/zohar001/satoken-test.git
重现步骤
1.先在浏览器打开：http://localhost:8080/api/login?userName=123
2.再打开：http://localhost:8080/api/getLoginAccountInfo
报错提示：未提供token
希望的结果：能正确获取到header内容

**Comment by click33** [comment]
这个示例我看了下，初步推测可能是因为构造 XssHttpServletRequestWrapper 时没有把 header 参数加进去，导致header参数 没有一直传递下去导致的？可以加一下试试

**Comment by Alickx** [comment]
XssHttpServletRequestWrapper类的getHeader方法中
String value = super.getParameter(name); 应改为
String value = super.getHeader(name);，
方法调用错误，所以获取不了header中的值。

**Comment by qiongbi9527** [comment]
检查发现确实是调用错误了，感谢指点
