### ISSUE TITLE
网关统一鉴权 启动异常

### ISSUE THREAD

**Issue by zhucl1006** [dromara/Sa-Token#183]
### 使用版本:
 <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-reactor-spring-boot-starter</artifactId>
            <version>1.27.0</version>
        </dependency>
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-dao-redis-jackson</artifactId>
            <version>1.27.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

### 报错信息：
The bean 'getSaTokenConfig', defined in class path resource [cn/dev33/satoken/spring/SaBeanRegister.class], could not be registered. A bean with that name has already been defined in class path resource [cn/dev33/satoken/reactor/spring/SaBeanRegister.class] and overriding is disabled.

### 希望结果：
Gateway 中根据官网说明引入出现错误

**Comment by click33** [comment]
是不是多引入包了
引入了   cn.dev33 sa-token-reactor-spring-boot-starter
就不需要再引入  cn.dev33 sa-token-spring-boot-starter 了

**Comment by zhucl1006** [comment]
> 是不是多引入包了 引入了 cn.dev33 sa-token-reactor-spring-boot-starter 就不需要再引入 cn.dev33 sa-token-spring-boot-starter 了

有测试去掉 sa-token-spring-boot-starter,但是还是一样的错误

**Comment by zhucl1006** [comment]
> 是不是多引入包了 引入了 cn.dev33 sa-token-reactor-spring-boot-starter 就不需要再引入 cn.dev33 sa-token-spring-boot-starter 了

是， 仔细看了下pom的依赖，有一个多引入了。
排除掉就可以了。
谢谢~

**Comment by zhucl1006** [comment]
解决
