### ISSUE TITLE
关于sa-token的RSA加密的建议

### ISSUE THREAD

**Issue by Kola96** [dromara/Sa-Token#187]
### 使用版本:
v1.27.0

### 报错信息：
前端JSEncrypt库的RSA加密密文是base64编码，而sa-token是不太常见的16进制编码，直接解密会报错

### 希望结果：
希望加密模块能提供一个base64密文解密的方法

**Comment by click33** [comment]
下几个版本会考虑重构一下，目前推荐你使用 Hutool 的加密模块 https://sa-token.dev33.cn/doc/index.html#/up/password-secure
