### ISSUE TITLE
【activityTimeout】redis设置过期时间有误

### ISSUE THREAD

**Issue by itweixiang** [dromara/Sa-Token#189]
### 使用版本:

cn.dev33:sa-token-spring-boot-starter:1.25.0
cn.dev33:sa-token-dao-redis:1.25.0

### 报错信息：
设置：
timeout=86400
activity-timeout=7200

具体的key过期时间发现不是配置的情况
![图片](https://user-images.githubusercontent.com/40189074/143394938-71bd3db1-fcde-47f9-97e6-e89b610f7c02.png)

项目启动的时候，是配置的值：
![图片](https://user-images.githubusercontent.com/40189074/143395283-82276305-7d8e-4623-ab9f-84b8d9319b27.png)

发现是Redis写的时候，用了timeout的超时时间
![图片](https://user-images.githubusercontent.com/40189074/143394908-34c6ac45-d3dc-443d-a46f-30096a23fe4a.png)

**Comment by itweixiang** [comment]
有请求进来的时候，SaTokenDao.updateTimeout()也没有调用，对activityTimeout进行续签

**Comment by ghu212** [comment]
这个问题在1.28.0版本仍然存在，本来临时token有效期只有半小时，结果检查是否过期要续签的缓存要保存30天,redis里一大堆无用的key
