### ISSUE TITLE
登录验证 - sa-token 官方文档

### ISSUE THREAD

**Issue by click33** [dromara/Sa-Token#19]
http://sa-token.dev33.cn/doc/index.html#/use/login-auth 

 Description

**Comment by LittleZhizhi** [comment]
登录之后我请求返回的响应头中有set-cookie，我想把它存进veux中，但我在js文件就是获取不了，显示null。

**Comment by click33** [comment]
> @LittleZhizhi
> 登录之后我请求返回的响应头中有set-cookie，我想把它存进veux中，但我在js文件就是获取不了，显示null。

直接放在返回body里就行，参考这一章：http://sa-token.dev33.cn/doc/index.html#/use/not-cookie
