### ISSUE TITLE
添加白名单配置

### ISSUE THREAD

**Issue by HuWei1995109** [dromara/Sa-Token#190]
建议：希望添加白名单配置，白名单配置的接口可以跳过登录
1、白名单接口 包括 数据接口、文件接口等

**Comment by bggmjxh** [comment]
你直接写个filter得了。然后可以读配置，自己写还灵活。

**Comment by click33** [comment]
默认就没有全拦截，全是根据你自己写的拦截规则和放行规则来处理的，详细参考 https://sa-token.dev33.cn/doc/index.html#/use/route-check
