### ISSUE TITLE
sso使用模式三，服务端已登陆的用户信息是存在哪里的？可以单独存到redis做高可用吗？

### ISSUE THREAD

**Issue by bggmjxh** [dromara/Sa-Token#192]
sso使用模式三，服务端已登陆的用户信息是存在哪里的？可以单独存到redis做高可用吗？

**Comment by click33** [comment]
就是存在 Redis 中的

**Comment by bggmjxh** [comment]
@click33 
官方文档中：https://sa-token.dev33.cn/doc/index.html#/sso/sso-server
“在SSO模式三时 Redis 相关包是可选的”
如果我不配置redis，服务端的登陆信息是存在那里的？
