### ISSUE TITLE
微服务模式，没有先鉴权，而是先转发了请求

### ISSUE THREAD

**Issue by slientuniverse** [dromara/Sa-Token#194]
### 使用版本:
 v1.28.0

### 报错信息：
完全按照文档内容编写微服务demo，但是在网关处，先走了ForwardAuthFilter的filter给请求加了header，转发了请求，然后才走到SaTokenConfigure配置的getSaReactorFilter鉴权里，微服务报了IdTokenInvalidException: 无效Id-Token，然后网关报SaTokenException: cn.dev33.satoken.exception.NotLoginException: 未提供Token

### 希望结果：
希望微服务模式下，可以先鉴权，然后再转发请求，这样可以拦截

### 复现步骤：
https://gitee.com/ryan-universe/sa-token-demo-gateway.git

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
可能是过滤器的注册顺序问题，你搜搜相关文章吧，这个问题不难解决，
实在不行就把 ForwardAuthFilter 的逻辑写在 SaReactorFilter setAuth 现有代码的后面
