### ISSUE TITLE
token 包含信息问题

### ISSUE THREAD

**Issue by GreatWriter** [dromara/Sa-Token#195]
### 使用版本:
1.28.0

比如想把 姓名、工号、职位等信息暴露出去。。是否可以利用token将这些信息暴露出来？
或者说有什么方式将这类信息能再hearders里面传了token的情况下快速获取到这类信息？

**Comment by SUDOCS** [comment]
看 sa-token-jwt 的实现，继承 [`StpLogic`](https://github.com/dromara/Sa-Token/blob/5ad5a514260cb3b3ab2eb6714b6c6026b4178123/sa-token-core/src/main/java/cn/dev33/satoken/stp/StpLogic.java) 并注入。

这里我想到两种方式：
一是，继承  [`SaJwtUtil`](https://github.com/dromara/Sa-Token/blob/5ad5a514260cb3b3ab2eb6714b6c6026b4178123/sa-token-plugin/sa-token-jwt/src/main/java/cn/dev33/satoken/jwt/SaJwtUtil.java)，将让需要暴露的信息也作为 payload 传进去生成 token，需要用到那些信息的时候解密出来，但是解密需要花费更多时间。

二是，类似框架那样，把 token 和 loginId 建立映射关系，可以让额外的用户信息也和 token 建立映射关系。


https://github.com/dromara/Sa-Token/blob/5ad5a514260cb3b3ab2eb6714b6c6026b4178123/sa-token-core/src/main/java/cn/dev33/satoken/stp/StpLogic.java#L314-L319


PS：我没有实践过

**Comment by fxbin** [comment]
我这边也有类似的需求，我的做法是扩展了 `SaJwtUtil`,  将需要暴露的信息也作为 payload 传进去生成 token

https://github.com/dromara/Sa-Token/pull/196

**Comment by mj19910923** [comment]
自定义 uid 和  姓名、工号、职位 的缓存关系，每次请求中使用 sa-token 获取uid，再根据uid从缓存里面拉取用户信息

**Comment by GreatWriter** [comment]
> 自定义 uid 和 姓名、工号、职位 的缓存关系，每次请求中使用 sa-token 获取uid，再根据uid从缓存里面拉取姓名、工号、职位信息

我现在就这这样做的。这种做法太依赖缓存机制了。加上不是敏感的信息。暴露出来是比较理想的，或者像Security一样放在上下文中直接去拿也是不错的
