### ISSUE TITLE
建议增加 使用 请求path 和 请求方法 组合成权限码，这样不用在每个方法上去标注

### ISSUE THREAD

**Issue by mj19910923** [dromara/Sa-Token#199]
建议增加 使用 请求path 和 请求方法 组合成权限码，这样不用在每个方法上去标注

类似这样：
get/v1/users
post/v1/users
get/v1/users/1
delete/v1/users/1

**Comment by ly-chn** [comment]
这个可以自定义注解实现

**Comment by click33** [comment]
``` java

/**
 * Sa-Token 代码方式进行配置 
 * @author kong 
 */
@Configuration
public class SaTokenConfigure implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SaRouteInterceptor((req, res, handler)->{
            // 把请求的 path 当做权限码来鉴权
            SaRouter.match("/**", r -> StpUtil.checkPermission(req.getRequestPath()));
        })).addPathPatterns("/**");
    }
    
}

```

**Comment by sunxyz** [comment]
/**
 * Sa-Token 代码方式进行配置 
 * @author kong 
 */
@Configuration
public class SaTokenConfigure implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SaRouteInterceptor((req, res, handler)->{
            // 参考楼上
            SaRouter.match("/**", r -> StpUtil.checkPermission(req.getMethod().toLowerCase()+"/"+req.getRequestPath()));
        })).addPathPatterns("/**");
    }
    
}

**Comment by sunxyz** [comment]
自定义注解可以参考这个例子
···
@Configuration
public class SaTokenConfigure implements WebMvcConfigurer {
    // 注册Sa-Token的注解拦截器，打开注解式鉴权功能

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
//        注册注解拦截器，并排除不需要注解鉴权的接口地址(与登录拦截器无关)
        registry.addInterceptor(new RolesAllowedSaAnnotationInterceptor()).addPathPatterns("/**");
    }

    static class RolesAllowedSaAnnotationInterceptor extends SaAnnotationInterceptor {

        static final String ROLE_PREFIX = "ROLE_";

        @Override
        public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
            if (handler instanceof HandlerMethod) {
                Method method = ((HandlerMethod) handler).getMethod();
                RolesAllowed rolesAllowed = method.getAnnotation(RolesAllowed.class);
                if (Objects.nonNull(rolesAllowed)) {
                    String[] roles = Stream.of(rolesAllowed.value()).filter(o -> o.startsWith(ROLE_PREFIX)).collect(Collectors.toList()).toArray(new String[]{});
                    if (roles.length > 0) {
                        StpUtil.checkRoleOr(roles);
                    }
                    String[] permissions = Stream.of(rolesAllowed.value()).filter(o -> !o.startsWith(ROLE_PREFIX)).collect(Collectors.toList()).toArray(new String[]{});
                    if (permissions.length > 0) {
                        StpUtil.checkPermissionOr(permissions);
                    }
                }
                return super.preHandle(request, response, handler);
            } else {
                return true;
            }
        }
    }

}
···

**Comment by laboratorys** [comment]
SaRouteInterceptor这个被删除了，现在该如何实现呢？
