### ISSUE TITLE
redis中保存token时key名问题

### ISSUE THREAD

**Issue by ying010** [dromara/Sa-Token#203]
redis缓存时，如果一个公司有多个项目同时使用了同一个redis，并且项目中都应用了sa-token,那么token名称一样时保存token信息就可能会出现覆盖现象。
暂时想到不冲突的解决方式：
1. 现在一个比较好的办法是每个项目都用自己独特的token名，让前端传不同token名；但是这样做会让前端有所抵触，他们更想应用统一的token名。
2. 类似于方法1，后端设置不同的token名，但是区别是前端传统一的token名，各项目配过滤器/拦截器设置自己个性token名的值为前端传的token；sa-token是取的，header、session、cookie；request中的这三个都是读取容易修改很难。
3. 每个项目都定义自己的loginType，这样处理就更麻烦了。

如果生成redis的key时，在token名前面再加一个可配的统一前缀是否更好一些呢？

例如：
```java
// 假设sa-token的key生成策略改为如下
public String splicingKeyTokenValue(String tokenValue) {
    return getConfig().getPrefix() + getConfig().getTokenName() + ":" + loginType + ":token:" + tokenValue;
}
```
那么本地项目中如下配置：
```yml
sa-token:
    prefix: demo1:
    token-name: token
```
前端请求时：
token: XXX
最终生成的redis key： demo1:token:login:token:XXX
这么处理的话使用相同redis的多个项目只要prefix不相同，就不会冲突了，配置起来更加简单，并且生成的key自动根据prefix分组了。

**Comment by click33** [comment]
针对你这个问题，我列出以下可选的方案：
1、不用同一个Redis，因为多个项目用同一个Redis，这不是很合理，还是分开比较好
2、用同一个Redis，但不用同一个db索引，比如项目1用db1，项目2用db2
3、如果既用了同一个redis，还用了同一个索引，那么可以配置不同的 token-name，前端不必变，依然传递原先的satoken，或者任意值，放在header里，后端来一个全局过滤器（或拦截器）把前端提交的token做一下二次写入：
``` java
SaHolder.getStorage().set("<配置的token-name>", <接收到的前端token值>);
```
这样框架就可以正常的读取到token了
4、至于在redis序列化时，增加一个前缀，这种方案可不可以呢，当然是可以，只不过目前有此需求的比较少，所有框架没弄这个功能，如果以后有此需求的比较多，就考虑加上
现在你可以通过重写SaTokenDao的方式，自己做到这一点

**Comment by ying010** [comment]
首先谢谢你的回复。
第1、2条实现较为简单、正规。但是由于公司策略，个人无法保证其正常运行(例如在老的redis索引中加了新项目而没有通知到相关人，就可能导致老系统的登录信息出现不可预知的错误)；这两种方式适合公司业务规划极为清晰(或者有钱)，加项目就会用新redis。
第3点是错误的实现方式，因为从Storage取token时并不是根据配置的token名取，是一个常量key，如果在Storage中保存这个常量key，并没用正确设置token，可能会出现不可预知的错误；贴一下部分主要源码：
```java
public class StpLogic {
  public String getTokenValueNotCut(){
    // 1. 尝试从Storage里读取 
    if(storage.get(splicingKeyJustCreatedSave()) != null) {
      tokenValue = String.valueOf(storage.get(splicingKeyJustCreatedSave()));
    }
  }

  public String splicingKeyJustCreatedSave() {
// return SaTokenConsts.JUST_CREATED_SAVE_KEY + loginType;
    return SaTokenConsts.JUST_CREATED;
  }
}

public class SaTokenConsts {
  public static final String JUST_CREATED = "JUST_CREATED_"; 
}
```
第4点是非常正确的选择，所以我copy下SaTokenDaoRedis的代码重写下，在每个key前面加一下前缀

**Comment by click33** [comment]
第3点那个地方是我疏忽大意了，不好意思 
有解决方案了就好

**Comment by baichangda** [comment]
我也遇到了这个问题、似乎这样配置是可行的
![image](https://user-images.githubusercontent.com/24662536/154908287-0294bf4e-d93a-4432-aa0c-482125ed6c0a.png)

**Comment by TOP-LH** [comment]
> 我也遇到了这个问题、似乎这样配置是可行的 ![image](https://user-images.githubusercontent.com/24662536/154908287-0294bf4e-d93a-4432-aa0c-482125ed6c0a.png)

一般redis分项目都会

**Comment by Mrqqqwww** [comment]
希望后续可以支持此功能，需求还是挺多的

**Comment by FaberSober** [comment]
同上，希望后续可以支持此功能～

**Comment by wltj920** [comment]
+1，同样有这个需求，希望在前后端交互时的token名为Authorization，而在Redis中的key前缀自定义

**Comment by hhtower** [comment]
+1，同样有这个需求，希望在前后端交互时的token名为Authorization，而在Redis中的key前缀自定义。
从设计上来说 这是前后端的分离。 前端传的值一般是Authorization，而后端定义redis key有多样化需求。
