### ISSUE TITLE
OAuth2.0的Code授权模式 获取授权码时 能否根据client_id直接获取Code授权码

### ISSUE THREAD

**Issue by zichen1019** [dromara/Sa-Token#205]
### 使用版本:
1.28.0

### 希望结果：
OAuth2.0的Code授权模式 获取授权码 能够返回授权码

### 想法：
授权模式Code授权码和隐藏式在文档中介绍的获取授权码，竟然要先登录才能再去获取？
我觉得有些不可思议。如果我有账号和密码我用密码模式登录不是更好一些吗？此处是否会采用根据client_id直接获取Code授权码的方式呢？

**Comment by Tutty98** [comment]
账号密码和client_id,secret是两码事
