### ISSUE TITLE
登陆后无法检测是否登陆时始终返回false，登出也如此

### ISSUE THREAD

**Issue by Own-lin** [dromara/Sa-Token#206]
### 使用版本:
sa-token-core-1.28.0.jar

### 报错信息：
登陆后无法检测是否登陆时始终返回false，登出也如此

### 希望结果：
正常返回

### 复现步骤：
登陆源码
` /**
     * {@code login()}接口业务流程：用户输入账号密码 ——> 使用 SaLoginDTO 接收 ——> 从传入的 Bean 对象中获取用户输入的手机号 ——>
     * 通过获取的手机号使用 service 中的 getRoleByTelephone 方法从数据库中查询用户数据 ——> 若 getRoleByTelephone() 返回为 null 则说明该手机号没注册或已被封禁
     * ——> 使用 security 的 passwordEncoder 接口中的 match 方法对用户输入的密码与从数据库中查到的密码进行比对 ——>
     * 使用 {@code StpUtil} 的 login()方法并传入用户的手机号作为标记ID ——> 使用{@code StpUtil}的getTokenValue()方法通过传入标记ID获取对应的token值
     * ——> 返回token值
     */
    @ApiOperation(value = "登陆")
    @PostMapping("/saLogin")
    public BaseResponse<String> login(HttpServletRequest request,
                                      HttpServletResponse response,
                                      SaLoginDTO loginDTO){

        //  TODO:看看如何设置这些值
        response.setCharacterEncoding("UTF-8");
        response.setContentType("application/json;charset=UTF-8");

        //  从传入的Bean中提取信息
        String userTelephone = loginDTO.getTelephone();
        Boolean readme = loginDTO.getReadMe();
        //  通过入参查找数据
        User userInfo = userImpl.getRoleByTelephone(userTelephone);
        //  查看是否该手机号是否已注册
        if (null == userInfo || null == userInfo.getTelephone()){
            return Resulting.error(ExceptionEnum.TELEPHONE_IS_NOT_FOUND);
        }
        //  查看是否该密码是否正确
        String userPassword = loginDTO.getPassword();
        if (!passwordEncode.matches(userPassword, userInfo.getPassword()))
        {
            return Resulting.error(ExceptionEnum.PASSWORD_FAILED);
        }
        //  该用户是否已经登陆
        if (StpUtil.isLogin()){
            return Resulting.error(ExceptionEnum.USER_IS_LOGGING);
        }
        //  判断是否开启了自动登陆
        if (readme == null){
            readme = false;
        }
        //  标记当前会话的ID
        StpUtil.login(userTelephone, readme);
        //  获取token
        String token = StpUtil.getTokenValue();

        //  从当前会话中获取Session，没有则创建一个
        HttpSession userSession = request.getSession();
        userSession.setAttribute("UserInfo", userInfo);
        //  设置当前会话的过期时间
        userSession.setMaxInactiveInterval(3600);

        return Resulting.success(token, "用户登陆成功");
    }`

登出以及检测是否登陆源码
`    /**
     * logout()登出功能流程: 通过{@code StpUtil.getLoginIdDefaultNull()}方法获取当前会话的token的标记ID —> 存在token则返回Object类型的ID，否则返回null
     * —> 对{@code tokenId}进行判空，为空则说明没有登陆 —> 通过{@code StpUtil.logout()}方法并传入token标记ID对相应的token进行注销操作
     */
    @ApiOperation(value = "登出/注销")
    @PostMapping("/saLogout")
    public BaseResponse<String> logout(){
        Object tokenId = StpUtil.getLoginIdDefaultNull();
        //  判断是否已经登陆
        if (null == tokenId){
            return Resulting.error(ExceptionEnum.UNAUTHORIZED_OR_TOKEN_OUT);
        }
        StpUtil.getSession().logout();
        StpUtil.logout(tokenId);

        return Resulting.success(null, "用户已登出");
    }

    @ApiOperation(value = "检测用户是否登陆")
    @GetMapping("/checkLogin")
    public BaseResponse<String> isLogin(){
        if (StpUtil.isLogin()){
            String isLogin = "用户<已>登录";
            return Resulting.success(isLogin, isLogin);
        }
        String notLogin = "用户<未>登录";

        return Resulting.success(notLogin, notLogin);
    }`

截图：
![2021-12-21_181344](https://user-images.githubusercontent.com/58496860/146912644-3ceb6f49-35b4-462a-b26b-75c610957072.png)

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
前端请求的时候，是否提交了Token？

**Comment by Own-lin** [comment]
> 前端请求的时候，是否提交了Token？

添加请求头的token后也如此

**Comment by Own-lin** [comment]
![image](https://user-images.githubusercontent.com/58496860/147205211-81894221-2c15-45c0-adc0-7d94e2c74739.png)

**Comment by Own-lin** [comment]
> 前端请求的时候，是否提交了Token？

已解决，是我设置时设置了Bearer前缀，而Knife4j我的固定请求头为Authorization，作者可以考虑多处理这样一种错误情况
