### ISSUE TITLE
activity-timeout临时token有效期到期后，redis中的session信息不会自动清除

### ISSUE THREAD

**Issue by as363018325** [dromara/Sa-Token#207]
### 使用版本:
1.22.0

### 希望结果：
token临时有效期到期后，自动清除redis中的session信息

### 复现步骤：
![image](https://user-images.githubusercontent.com/40160141/147315092-f5c37e51-cdc2-4ab4-b46b-af765013bac3.png)

**Comment by click33** [comment]
等timeout时间到了就自动清除了

**Comment by as363018325** [comment]
> 等timeout时间到了就自动清除了
这个可以在程序中动态修改timeout的到期时间吗
有没有比较好的方法，在activity-timeout触发后，清除掉对应存储得session信息。因为允许同时登录的情况下，会产生多个session信息。其中一个用户因为临时token到期，没有清理掉对应session信息，程序中有获取session信息做处理，会导致程序误判。

**Comment by click33** [comment]
用这个方法判断一个token是否临时过期了
```
StpUtil.stpLogic.checkActivityTimeout(tokenValue);

```

因为 activity-timeout 到期的时候，Redis并不会主动通知系统，所以无法清除数据

**Comment by as363018325** [comment]
activity-timeout 到期时长是根据什么判断用户有没有操作得，只要调用了sa-token相关的拦截器之类的都会重置吗

**Comment by as363018325** [comment]
> activity-timeout 到期时长是根据什么判断用户有没有操作得，只要调用了sa-token相关的拦截器之类的都会重置吗

**Comment by as363018325** [comment]
> 用这个方法判断一个token是否临时过期了
> 
> ```
> StpUtil.stpLogic.checkActivityTimeout(tokenValue);
> ```
> 
> 因为 activity-timeout 到期的时候，Redis并不会主动通知系统，所以无法清除数据

activity-timeout 到期时长是根据什么判断用户有没有操作得，只要调用了sa-token相关的拦截器之类的都会重置吗
