### ISSUE TITLE
关于 timeout 的相关问题

### ISSUE THREAD

**Issue by ily433664** [dromara/Sa-Token#213]
关于 timeout 有两个问题希望能优化

### 1、现在 timeout 无法进行续期，只有 activity-timeout 可以续期，**希望添加 timeout 续期功能**

举个例子，如果我的需求是这样，用户登录有效期是七天，只要有操作就进行续期。
按照现在框架的逻辑，只能是 timeout = -1， activity-timeout = 7天，才能满足需求，但是会导致相关的（redis）**缓存永远不会清除**，这个显然来说是不合理的。

在其他问题也看过相关的回复，虽然将 timeout 设为比较大的也可以有一定的体验。
但是也会存在两个问题，
一是登录过期后相关的垃圾数据会存在很长时间，**在 timeout 过期后才会被清除**；
二是多次续期达到 timeout 的时间后也会立马过期，极端情况下是**刚刚还正常使用突然就到期了**，这种情况只会让用户以为系统有问题，是完全不能接受的。

看过作者在其他地方的回复，认为这个影响不大，但我觉得这个影响不大应该是交给产品去判断的，而不是连这个功能都没有。

### 2、activity-timeout 过期后，session 里面的 TokenSign 不会被清除
如果设置 timeout = -1 ，用户没有手动退出，那么 TokenSign 只会**无限增长**下去，虽然占用空间不大，但在功能上来说也是一个问题了。

**Comment by click33** [comment]
第一条，已经解决，下次版本更新发包可见
第二条，可以在每次登陆时提前调用一下注销方法，注销之前的数据
