### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: 'org.apache.dubbo.rpc.RpcContext org.apache.dubbo.rpc.RpcContext.getServerContext()'

### ISSUE THREAD

**Issue by GreenCypress** [dromara/Sa-Token#216]
### 使用版本:
Sa-Token: 2.8.0
Dubbo: 3.0.5
已导入 sa-token-context-dubbo
### 报错信息：
调用 StpUtil.login(userInfo.getUserId(), "APP"); 时报错：
Caused by: java.lang.NoSuchMethodError: 'org.apache.dubbo.rpc.RpcContext org.apache.dubbo.rpc.RpcContext.getServerContext()'

**Comment by click33** [comment]
应该是 Dubbo 的版本问题，目前适配的版本是 2.7.11 ，你试试
