### ISSUE TITLE
采用 Style 模式生成 Jwt Token 的时候没有考虑 Jwt Token 的过期时间的问题

### ISSUE THREAD

**Issue by Antediluvian** [dromara/Sa-Token#218]
### 使用版本:
1.29.0

### 报错信息：
获取扩展信息时抛出 NotLoginException 异常

### 希望结果：
成功获取扩展信息值

### 复现步骤：
1. 采用 Style 模式生成 Jwt Token，调用 SaLoginConfig.setExtra("key", "value") 方法放入扩展信息，将生成 Jwt Token 返回给客户端；
2. 客户端使用这个 token 去访问受限接口；
3. 后端接口接到请求后，调用 StpUtil.isLogin() 时返回值为 true，但是后续调用 StpUtil.getExtra("key") 方法想要获取扩展信息的时候抛出了 NotLoginException 异常。

经查，sa-token 在 Style 模式下生成 Jwt Token 的时候根本就没有使用 timeout 值，但是当需要获取扩展信息的时候先要解析生成的 token，导致这时候取出的 eff 值永远为 0，过不了对 Jwt Token 是否过期的判断。

具体代码可参见 StpLogicJwtForStyle.java 类的 45 行。

**Comment by click33** [comment]
正在修复……

**Comment by click33** [comment]
补发了一个 v1.29.1.trial 版本解决这个问题，你可以先更新一下
https://www.oschina.net/news/182301/sa-token-1-29-1-trial-released
