### ISSUE TITLE
错误信息想通过 RestControllerAdvice 进行拦截,拦截到后还是会进行错误内容打印.

### ISSUE THREAD

**Issue by PeixyJ** [dromara/Sa-Token#219]
### 使用版本:
1.29.0

### 报错信息：
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is cn.dev33.satoken.exception.NotLoginException: 未提供Token] with root cause

### 希望结果：
希望通过 RestControllerAdvice 进行获取而不进行这个错误的展示.

### 复现步骤：
全局拦截后任意访问网址.

<img width="1875" alt="image" src="https://user-images.githubusercontent.com/45998593/153745873-82792fc8-eefe-4531-a5a4-3687ea1f80ea.png">

**Comment by PeixyJ** [comment]
代码通是可以的,我只是想不展示这个错误内容. RestControllerAdvice 可以拦截并做处理.但是我不想再log中展示这个[未提供Token]错误提示
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/45998593/153788948-8bd24590-4144-47e0-9ef7-2190c305e17a.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/45998593/153789009-e4786a68-2099-45e9-89a0-6c88b481b98d.png">

**Comment by click33** [comment]
Sa-Token 框架里没有显式打印异常的地方，你debug一下这个异常从哪里打印出的

**Comment by PeixyJ** [comment]
好的。我仔细检查下.

**Comment by liuzhihai520** [comment]
兄弟这个问题处理了吗，可以分享一下怎么处理的吗？

**Comment by PeixyJ** [comment]
@liuzhihai520 处理掉了 你检查下路由拦截器 可能写了多次的登录认证.

**Comment by juning98** [comment]
> @liuzhihai520 处理掉了 你检查下路由拦截器 可能写了多次的登录认证.

大佬  能不能说一下具体是怎么处理的啊
