### ISSUE TITLE
多账号验证 - sa-token 官方文档

### ISSUE THREAD

**Issue by click33** [dromara/Sa-Token#22]
http://sa-token.dev33.cn/doc/index.html#/use/many-account 

 Description

**Comment by yangyonglin** [comment]
多账号请求头里设置了，修改后的token名称。权限验证的时候取不到名称。报错

**Comment by click33** [comment]
先打印一下 getTokenName()  看看是根据哪个名称读取的

**Comment by LittleZhizhi** [comment]
StpUtil可以做成通过构造方法传入KEY参数生成不同的认证工具吗？或者是有更好的方式？现在的话如果多账号验证需要复制多几个StpUtil文件进行修改。

**Comment by click33** [comment]
> @LittleZhizhi
> StpUtil可以做成通过构造方法传入KEY参数生成不同的认证工具吗？或者是有更好的方式？现在的话如果多账号验证需要复制多几个StpUtil文件进行修改。

这个没办法的，为了方便调用，所有方法都静态化了，相当于一个静态类，而静态类就没法通过构造方法来进行key区分，其实这种复制方案就是初期稍微操作一下，后期的调用都完全和StpUtil一致，不麻烦
