### ISSUE TITLE
默认生成的token是否有可能重复

### ISSUE THREAD

**Issue by AaronW-BE** [dromara/Sa-Token#221]
Token生成是否会重复（包括低概率重复）

**Comment by click33** [comment]
理论上会，但概率低到无需担心。而且你可以在配置文件更改token生成格式，或者自定义生成策略

**Comment by AaronW-BE** [comment]
> 理论上会，但概率低到无需担心。而且你可以在配置文件更改token生成格式，或者自定义生成策略

好的，个人感觉还是在生成的时候考虑一下重复token的情况，或者可以加一个配置项是否进行重复检测

**Comment by ly-chn** [comment]
单独检查效率太低
如果怕重复建议使用UUID#nameUUIDFromBytes
