### ISSUE TITLE
FastJson序列化SaSession问题

### ISSUE THREAD

**Issue by russleung44** [dromara/Sa-Token#225]
### 使用版本:
1.29.0

### 报错信息：
无法反序列化 tokenSignList

![image](https://user-images.githubusercontent.com/56534185/156709120-645af303-fc71-4d59-96e8-0eadf6934276.png)

**Comment by click33** [comment]
用 jackson 不行吗

**Comment by russleung44** [comment]
> 
Jackson是没问题, 但是大佬说项目要改成 fastjson, 所以想问问有没有解决的办法

**Comment by click33** [comment]
jackson 写进去的就用 jackson 取 
用 fastjson 写进去的 再用  fastjson 取

**Comment by russleung44** [comment]
读写都是用 fastjson , 只是从redis拿出来反序列化成对象时没有写入 tokenSignList 的数据

**Comment by khalidzk** [comment]
有解决了吗 这个问题

**Comment by russleung44** [comment]
> 有解决了吗 这个问题

没有, 用回Jackson了

**Comment by shuaohan** [comment]
1.可以升级 fastjson的版本 
2.重写TokenSign.class 类，增加 get 、set方法

**Comment by colo1994** [comment]
> fastjson

你好，请问你的fastjson是哪个版本，具体的包名呢
