### ISSUE TITLE
登录拦截器配置了全部接口拦截，我在某个接口方法上加个 “注解” 可以放行不校验么望后续官方支持

### ISSUE THREAD

**Issue by EllenJack** [dromara/Sa-Token#230]
登录拦截器配置了全部接口拦截，我在某个接口方法上加个 “注解” 可以放行不校验么望后续官方支持

**Comment by EllenJack** [comment]
restful 接口，路径名一样，不同请求方法

**Comment by ly-chn** [comment]
可以使用AOP方式自己重新定义一下AOP判断. 
目前你说的这种问题没看到实际应用场景. 或者可以把应用场景贴出来一起讨论一下

**Comment by lwQin** [comment]
@ly-chn 应用场景例如
```
login -> PUT http://localhost/api/v1/sessions
logout -> DELETE http://localhost/api/v1/sessions
```

**Comment by ly-chn** [comment]
@lwQin 
@EllenJack 
https://github.com/ly-chn/sa-token-ignored-annotation-sample

这里有个demo实现可以参考一下, 因为这是一个相对于灵活的验证方式, 具体官方是否会合并有待考虑
