### ISSUE TITLE
关于GateWay全局过滤器增加自定义Token获取的参数往下传递

### ISSUE THREAD

**Issue by zhanghan2585** [dromara/Sa-Token#234]
版本:
1.29

问题：
SaReactorFilter 全局过滤器是否可以把 StpUtil.getTokenValue() 值放入到header里面往下传递？尝试直接实现GlobalFilter 执行StpUtil.getTokenValue() 提示上下文未准备

**Comment by click33** [comment]
GateWay 不是会自动给你转发请求头的吗
