### ISSUE TITLE
希望增加dependency management

### ISSUE THREAD

**Issue by fastkdm** [dromara/Sa-Token#235]
### 使用版本:
请提供一下版本号
1.29.0

### 报错信息：
请提供报错的详细信息
无

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
希望增加类似springboot或springcloud那种，dependency-management统一管理版本号

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址
无

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
后续整理一下
