### ISSUE TITLE
Springboot 2.6.* 循环依赖。

### ISSUE THREAD

**Issue by Zbuter** [dromara/Sa-Token#236]
### 报错信息：
Springboot 版本 2.6 Sa-token 版本任意。

2022-03-15 08:50:29.935 ERROR 25580 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  cn.dev33.satoken.spring.SaTokenSpringAutowired
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

根据提示，需要在配置文件设置
spring.main.allow-circular-references=true
才能运行解决。

请问这循环依赖的问题，有解决的计划吗？

**Comment by ly-chn** [comment]
后续将处理此问题, 感谢反馈. 请暂时允许Spring循环依赖处理机制来屏蔽此问题.

**Comment by click33** [comment]
1.29.0 版本还有这个问题吗？

**Comment by man2293127414** [comment]
都2024年了，还是不行哎

**Comment by jzhParallel** [comment]
我用的1.9.0版本也不行，2024年9月9号了

**Comment by Zbuter** [comment]
> 我用的1.9.0版本也不行，2024年9月9号了

能用就行了。

**Comment by click33** [comment]
用最新版呀

**Comment by Hr-byte-art** [comment]
我是真的找不到为啥会循环依赖

**Comment by ZhaoFlowerFlower** [comment]
我今天遇到了，应该是和springboot版本有关系，有些版本之间不兼容。我用的是2.3.7.RELEASE的springboot和1.14.0的satoken

**Comment by ZhaoFlowerFlower** [comment]
> 我用的1.9.0版本也不行，2024年9月9号了
我今天遇到了，应该是和springboot版本有关系，有些版本之间不兼容。我用的是2.3.7.RELEASE的springboot和1.14.0的satoken

**Comment by ZhaoFlowerFlower** [comment]
> 我是真的找不到为啥会循环依赖

我今天遇到了，应该是和springboot版本有关系，有些版本之间不兼容。我用的是2.3.7.RELEASE的springboot和1.14.0的satoken
