### ISSUE TITLE
单点登录自定义视图

### ISSUE THREAD

**Issue by 77xiaoxx** [dromara/Sa-Token#238]
### 使用版本:
V1.28.0

单点登录模式二
// 配置：未登录时返回的View 
		cfg.sso.setNotLoginView(() -> {
			return new ModelAndView("sa-login.html");
		});
对于前后端分离的登录页此方法应该如何返回视图呢？
我尝试过如下的写法
		cfg.sso.setNotLoginView(() -> {
			return new ModelAndView(new RedirectView("http://xxx/login"));
		});
虽然页面可以跳转过去，但是并不是http://{sso-server}/sso/auth?redirect=xxx?back=xxx这种形式的，这就导致后续无法刷新页面进行授权

**Comment by 77xiaoxx** [comment]
已解决谢谢

**Comment by Dream-s-Wang** [comment]
我也有这个问题，请问您是怎么解决的？ @77xiaoxx
