### ISSUE TITLE
redis 没有写入参数

### ISSUE THREAD

**Issue by lingzhejie** [dromara/Sa-Token#239]
### 使用版本:
请提供一下版本号
1.29.0

### 报错信息：
请提供报错的详细信息
sa-token 配置 redis 后，没有写入 redis  以及尝试了 StpUtil.getTokenSession().set() 没有写入redis 

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
我希望能看到报错

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by lingzhejie** [comment]
![image](https://user-images.githubusercontent.com/100008881/159832846-85ad1a18-9bc9-419a-9374-336f4c17ae43.png)
![image](https://user-images.githubusercontent.com/100008881/159832932-9955baaa-90ec-4e21-b2ea-214fed0172de.png)
这是我的效果

**Comment by click33** [comment]
测试官网仓库里的demo是不是同样会出问题

**Comment by lingzhejie** [comment]
是的 使用仓库中的demo也是一样的没有对redis写入参数发自我的iPhone------------------ 原始邮件 ------------------发件人: click33  ***@***.***>发送时间: 2022年4月21日 02:11收件人: dromara/Sa-Token ***@***.***>抄送: lingzhejie ***@***.***>, Author ***@***.***>主题: Re: [dromara/Sa-Token] redis 没有写入参数 (Issue #239)
Closed #239.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dromara/Sa-Token/issues/239#event-6465231062",
"url": "https://github.com/dromara/Sa-Token/issues/239#event-6465231062",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
