### ISSUE TITLE
Spring Boot 2.6.* 项目使用Quick-Login插件提示循环依赖

### ISSUE THREAD

**Issue by Cr-y** [dromara/Sa-Token#240]
### 使用版本:
sa-token-spring-boot-starter:1.29.0
sa-token-quick-login:1.29.0

### 报错信息：
Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  cn.dev33.satoken.quick.SaQuickBean
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

### 希望结果：
项目希望部署到线上环境供前端调试，于是增加简易的认证，但高版本Springboot禁止循环依赖无法使用，只能通过配置手动关闭阻止。

**Comment by ly-chn** [comment]
已知问题, 请使用配置手动关闭循环依赖检测临时处理, 后续会解决此问题
