### ISSUE TITLE
如何使用mysql或者file做session store

### ISSUE THREAD

**Issue by laoyur** [dromara/Sa-Token#248]
### 使用版本:
1.29.0

### 报错信息：
无

### 希望结果：
希望能够支持mysql或者文件作为session store

我知道可能作者会有 `居然会有这种需求？` 的想法，哈哈，但是内部小项目，不想再多弄个redis增加依赖，如果mysql略复杂的话，file也行啊，不知道能否实现？

**Comment by click33** [comment]
你可以自己试试，实现 SaTokenDao 接口就好了
