### ISSUE TITLE
Http Basic功能的一个问题

### ISSUE THREAD

**Issue by qq229338869** [dromara/Sa-Token#249]
### 使用版本:
satoken 1.29.0
chrome 版本 100.0.4896.127（正式版本） （64 位）

### 报错信息：
在项目中嵌套了iframe，jquery请求一个接口服务，接口服务使用 Http Basic功能，被Chrome block了，Firefox没有问题。

login_main.do:1 Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.
![image](https://user-images.githubusercontent.com/30120123/166892854-5088d6d4-0e20-4cd3-8e26-9e52d0aa8cd0.png)

### 希望结果：
找了半天没解决，请教大佬有没有解决方案。

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
这个我也不知道咋解决

**Comment by qq229338869** [comment]
> 



> 这个我也不知道咋解决

好的，被chrome制裁了，不在这个地方使用httpbasic了
