### ISSUE TITLE
如何获取有效token的总数量

### ISSUE THREAD

**Issue by iCloudys** [dromara/Sa-Token#251]
### 使用版本:
请提供一下版本号

### 报错信息：
请提供报错的详细信息

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
StpUtil.searchTokenValue(null, -1, 0).size()

**Comment by iCloudys** [comment]
感谢您的回答，但是拿不出来，在redis中明明有token记录，但是这样写返回0

**Comment by iCloudys** [comment]
通过断点可以看出，如果keyword传null的话，会走如下结果:最终redis的key不正确
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/13017318/169634650-48df3c84-4a3c-400f-b55d-c6fb99805a5e.png">
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/13017318/169634661-3c26414f-6fcb-4dd1-9d98-7beb55c3b380.png">
