### ISSUE TITLE
哥，为什么我在土澳访问不了官方文档？

### ISSUE THREAD

**Issue by ManuRodgers** [dromara/Sa-Token#252]
![image](https://user-images.githubusercontent.com/33333844/167624832-707eeb13-af2e-48cb-83a3-01ab3bfecca2.png)
点进去以后就是这个样子

**Comment by click33** [comment]
可能是cdn不太行，，

**Comment by click33** [comment]
现在再试试呢 应该行了吧

**Comment by ManuRodgers** [comment]
哥 可以了， 十分感谢
