### ISSUE TITLE
文档404

### ISSUE THREAD

**Issue by oecoder** [dromara/Sa-Token#253]
wend文档j部分。 404
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/99719606/167699562-5e52f7ce-246f-4a67-9e91-678ed3282330.png">

**Comment by click33** [comment]
现在呢

**Comment by oecoder** [comment]
还是不可以，海外地区

**Comment by click33** [comment]
页面是什么样子，显示的什么，方便截个图吗

**Comment by oecoder** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/99719606/168170230-eaf76479-3410-4fb3-90ef-9f5007bddd00.png">
要换cdn了

**Comment by click33** [comment]
我现在加了一个判断，在cdn加载无效的时候，页面将提示你打开一个备用地址，你看看你那边可以正常加载吗

**Comment by oecoder** [comment]
好的，感恩！

**Comment by oecoder** [comment]
可以用备用地址打开了

**Comment by click33** [comment]
ok，那我就 close issue 了
