### ISSUE TITLE
自定义用户超时时间 session与token有效期不一致

### ISSUE THREAD

**Issue by xiaoxiao6666** [dromara/Sa-Token#254]
### 使用版本:
请提供一下版本号
1.30

### 报错信息：
请提供报错的详细信息
自定义用户超时时间 session与token有效期不一致

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
自定义用户超时时间 session与token有效期应一致

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址
SaLoginModel saLoginModel = new SaLoginModel();
saLoginModel.setTimeout(60)
StpUtil.login(user.getId(), saLoginModel);

造成的原因是因为在cn.dev33.satoken.stp.StpLogic#createLoginSession(java.lang.Object, cn.dev33.satoken.stp.SaLoginModel)
方法中判断了全局时间和当前设置的超时时间进行的判断。
![image](https://user-images.githubusercontent.com/24434907/168076612-5a8bcdfe-3b00-4056-b1d2-edbcd5907e57.png)

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
session 的有效时间和最长的 token 保持一致

**Comment by click33** [comment]
如果第一个客户端登录时 指定的 timeout 是 1000
第二个客户端登录时 指定的 timeout 是100
那么 session 的时间以 1000 为准

**Comment by xiaoxiao6666** [comment]
明白了 谢谢大佬
