### ISSUE TITLE
springboot依赖

### ISSUE THREAD

**Issue by wlb632363** [dromara/Sa-Token#255]
### 使用版本:
[v1.30.0]

### 报错信息：
springboot重复依赖

### 希望结果：
sa-token去除依赖的springboot-web的jar

### 复现步骤：
当前项目中依赖的是springboot 2.6.3的版本，sa-token依赖的是2.5.12，项目产生了重复依赖，sa-token作为中间件，是否应该考虑不依赖于springboot-web这种比较基础的大框架，否则一旦和项目本身业务所需的版本冲突，应该怎么取舍

**Comment by click33** [comment]
maven 会以你引入的依赖为准，放弃sa-token引入的
