### ISSUE TITLE
期望支持jdk9模块化

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#256]
### 使用版本:
请提供一下版本号
1.30.0

### 报错信息：
无

### 希望结果：
期望支持一下jdk9+、否则高版本引入必须舍弃了

### 复现步骤：
无

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by ly-chn** [comment]
jdk9上有什么问题吗

**Comment by baichangda** [comment]
因为框架升级jdk17、准备将项目转换为jigsaw模块化
发现sa-token并没有支持模块化
![image](https://user-images.githubusercontent.com/24662536/173313441-45e4a295-23d9-4450-93ec-0eb335cfdb05.png)

建议至少应该将sa-token jar转换为 自动模块、像spring一样
spring马上也会发布6.+支持 jdk17、这是一个趋势
![image](https://user-images.githubusercontent.com/24662536/173313330-24da0281-e4e1-4b92-9c67-04d6a5ffb302.png)
