### ISSUE TITLE
pr

### ISSUE THREAD

**Issue by herowws** [dromara/Sa-Token#260]
### 使用版本:
v1.29.0

![image](https://user-images.githubusercontent.com/41428542/171311048-51069add-47c1-4012-8bb1-d2ec568aef7b.png)

getLoginId 本身就把loginid当成字符串处理了，没必要返回object 直接返回string,  我存的long现在使用 Long.valueOf((String) StpUtil.getLoginId())

**Comment by click33** [comment]
有个API，专门用long类型获取：
``` java
StpUtil.getLoginIdAsLong();  
```

**Comment by herowws** [comment]
整挺好
