### ISSUE TITLE
webflux下，全局过滤器报错：未成功初始化上下文

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [dromara/Sa-Token#261]
### 使用版本:
sa-token-reactor-spring-boot-starter:1.30.0

## 测试结果
标签失效 - @SaCheckLogin
报错代码 - `StpUtil.checkLogin()`

### Code:
```
@Configuration
public class SaRouterConfig {

    @Bean
    public SaReactorFilter getSaReactorFilter() {
        return new SaReactorFilter()
                .setAuth(obj -> {
                    System.out.println("---------- sa全局认证");
                    SaRouter.match("/api/*/pri/**")
                            .check(r -> StpUtil.checkLogin());
                });
    }

}
```
### 报错信息：
```
cn.dev33.satoken.exception.SaTokenException: 未成功初始化上下文
	at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:54) ~[sa-token-core-1.30.0.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP GET "/api/user/pri/logout" [ExceptionHandlingWebHandler]
```

### 希望结果：
在普通模式下没有问题，webflux模式下follow教程也应该没有问题

**Comment by click33** [comment]
“webflux模式下follow教程也应该没有问题”这句话啥意思 没太看懂

**Comment by ANUGLYPLUGIN** [comment]
> “webflux模式下follow教程也应该没有问题”这句话啥意思 没太看懂
跟着官方教程，会报错

**Comment by ANUGLYPLUGIN** [comment]
> “webflux模式下follow教程也应该没有问题”这句话啥意思 没太看懂
更新了一下
标签失效 - @SaCheckLogin
报错代码 - `StpUtil.checkLogin()`

**Comment by ANUGLYPLUGIN** [comment]
> 仓库里的demo能运行成功吗

稍等，我试下

**Comment by ANUGLYPLUGIN** [comment]
> 仓库里的demo能运行成功吗
## @SaCheckLogin
<img width="870" alt="image" src="https://user-images.githubusercontent.com/97073795/171815490-a12f7be0-fb95-4470-b128-95d3fa329e29.png">
```
@SaCheckLogin
@RequestMapping("annotation")
public AjaxJson testAnnotation() {
     return AjaxJson.getSuccessData(1);
}
```

## CheckLogin function
<img width="814" alt="image" src="https://user-images.githubusercontent.com/97073795/171815602-cc99a183-e36e-43fa-82b7-884e7c0e24a8.png">
```
@RequestMapping("checkLogin")
public AjaxJson checkLogin() {
StpUtil.checkLogin();
    return AjaxJson.getSuccessData(1);
}
```

**Comment by ANUGLYPLUGIN** [comment]
> 仓库里的demo能运行成功吗

注解不行，但是函数可以

**Comment by click33** [comment]
“注解不行”是指没效果，还是报错

**Comment by ANUGLYPLUGIN** [comment]
> “注解不行”是指没效果，还是报错

没效果

**Comment by click33** [comment]
没效果是正常的，注解鉴权需要加拦截器才能生效，webflux下没这个功能，用函数鉴权就行了

**Comment by ANUGLYPLUGIN** [comment]
> 没效果是正常的，注解鉴权需要加拦截器才能生效，webflux下没这个功能，用函数鉴权就行了

好的明白了
不过函数鉴权本身也没有配置，我自己的demo改成webflux以后，使用函数鉴权就报这个错了。

**Comment by click33** [comment]
是不是因为没注册 SaReactorFilter，webflux下注册 SaReactorFilter 这一步是必须的

**Comment by ANUGLYPLUGIN** [comment]
> 是不是因为没注册 SaReactorFilter，webflux下注册 SaReactorFilter 这一步是必须的

```
@Configuration
public class SaRouterConfig {

    @Bean
    public SaReactorFilter getSaReactorFilter() {
        return new SaReactorFilter()
                .setAuth(obj -> {
                    System.out.println("---------- sa全局认证");
                    SaRouter.match("/api/*/pri/**")
                            .check(r -> StpUtil.checkLogin());
                });
    }

}
```

我注册了吧，这和语言和包管理工具有关系吗，我用的kotlin和gradle

**Comment by click33** [comment]
可能有吧，我没试过 kotlin。
总之既然仓库demo能运行成功，你就和demo比对一下吧，看看是哪里的差异造成的

**Comment by ANUGLYPLUGIN** [comment]
> 可能有吧，我没试过 kotlin。 总之既然仓库demo能运行成功，你就和demo比对一下吧，看看是哪里的差异造成的

好的好的，谢谢。

**Comment by ANUGLYPLUGIN** [comment]
kotlin请单独配置一个kt的config文件，有的包config可以java文件里配置，satoken会报错，并且请仔细按照demo来。
