### ISSUE TITLE
FastJSON 反序列化 SaSession 时 TokenSign 中变量为 null

### ISSUE THREAD

**Issue by llll1004** [dromara/Sa-Token#262]
### 使用版本:
1.30.0

### 报错信息：
使用 FastJSON 进行 Redis 反序列化操作时，由于 TokenSign 没有相关 setter 导致变量为 null，只能手动处理，不知可否添加 setter ?

### 希望结果：
添加 setter

**Comment by click33** [comment]
可以

**Comment by llll1004** [comment]
> 可以

感谢您的回复

**Comment by shuaohan** [comment]
升级fastjson的版本（自测2.0.7可用），可以不用重写TokenSign.class类
