### ISSUE TITLE
退出后获取用户信息成功

### ISSUE THREAD

**Issue by nzb15555196162** [dromara/Sa-Token#265]
### 使用版本:
请提供一下版本号
1.30.0

### 报错信息：
请提供报错的详细信息
sa-token对接oauth2
1 账号密码登录成功
2 获取用户信息
3 退出
4 获取用户信息
note:以上都是通过接口操作流程

### 希望结果：
相比于已发生的报错，您希望看到什么样的运行结果
退出后理论上不能获取用户信息,现在可以获取到用户信息

### 复现步骤：
如果复现步骤比较复杂，请将 demo 上传到 git 并留下地址
1 调用登录接口
2 调用获取用户信息接口
3 调用退出接口
4 调用获取用户信息接口

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
你观察一下 退出后 redis的数据自动删除了吗

**Comment by nzb15555196162** [comment]
没有

**Comment by nzb15555196162** [comment]
这里补充下，未退出之前redis里面数据
![图片](https://user-images.githubusercontent.com/18350673/174514489-7c2822a7-97a4-44ef-85a6-98d9fe64f78b.png)

退出以后redis里面的数据
![图片](https://user-images.githubusercontent.com/18350673/174514470-ae734c89-46e1-415c-8f71-95b55bbf45b1.png)
退出方法调用
![图片](https://user-images.githubusercontent.com/18350673/174514563-97de8e82-6b64-4d19-a51a-81ea600898eb.png)

**Comment by click33** [comment]
你退的是 StpUtil 会话，和 OAuth2 没关系，两者不要混淆

**Comment by nzb15555196162** [comment]
我的意思是退出了，调用几口为啥还能获取到用户信息，这里理论上是不合理的

**Comment by nzb15555196162** [comment]
> 你退的是 StpUtil 会话，和 OAuth2 没关系，两者不要混淆

我的意思是退出了，调用几口为啥还能获取到用户信息，这里理论上是不合理的

**Comment by nzb15555196162** [comment]
> 你退的是 StpUtil 会话，和 OAuth2 没关系，两者不要混淆

退出至少清除access-token，否则这个退出是个假退出，我是这样理解的
