### ISSUE TITLE
请问生成的token，在服务器重启之后，token会失效，这样是正常的吗？

### ISSUE THREAD

**Issue by ChenforCode** [dromara/Sa-Token#266]
### 使用版本:
请提供一下版本号

### 报错信息：
请提供报错的详细信息

### 希望结果：
是否可以在服务器重启之后token仍然有效，只有当到期了才会失效

### 复现步骤：
使用StpUtil.login登录
使用StpUtil.getTokenValue()获取token
这个token会在服务器重启之后失效
使用的jwt模式

备注：您提供的信息越充足，我们将越能快速的定位错误

**Comment by click33** [comment]
Simple 模式正常
Stateless 模式不正常
Mixin 模式看情况

**Comment by ChenforCode** [comment]
十分感谢！原来没有搞明白这几个模式的作用，现在改为stateless模式重启不失效了！
