### ISSUE TITLE
网关统一鉴权能否获取异常类型, 然后自定义抛出呢?

### ISSUE THREAD

**Issue by TOP-LH** [dromara/Sa-Token#271]
### 对以下问题有疑问:
网关统一鉴权能否获取异常类型, 然后自定义抛出呢?
因为我们有统一返回类型, 不能破坏结构性

**Comment by Guanghua0714** [comment]
你定义一个全局异常处理器拦截 NotLoginException 就可以了啊
或者  SaReactorFilter 里面  有个 setError 方法  你可以看一下 [sa-token-demo-webflux](https://github.com/dromara/Sa-Token/blob/dev/sa-token-demo/sa-token-demo-webflux/src/main/java/com/pj/satoken/SaTokenConfigure.java)

**Comment by Guanghua0714** [comment]
你可以参考一下内容：
```java
 if (e instanceof NotLoginException) {

                        return new Gson().toJson(new Result(Boolean.FALSE, ResultCode.NOT_LOGIN, e.getMessage()));
                    }
                    return new Gson().toJson(new Result(Boolean.FALSE, ResultCode.ERROR, e.getMessage()));
}
```
