### ISSUE TITLE
使用sa-token的网关鉴权如何获取请求头信息并判断

### ISSUE THREAD

**Issue by lihao0324** [dromara/Sa-Token#272]
之前我们网关也会路由别的系统的服务, 别的系统的服务会单独带一个请求头, 我们会去获取请求头中获取来源系统的标识并判断.
如果我使用了SaReactorFilter鉴权模块, 我该如何判断呢, 我看SaReactorFilter不支持我获取请求头中的一些信息

**Comment by click33** [comment]
SaHolder.getRequest().getHeader(name)
