### ISSUE TITLE
建议官方文档内容新增和部分内容位置调整

### ISSUE THREAD

**Issue by 303470934** [dromara/Sa-Token#275]
### 建议增加的新功能:
1.文档内所有有Maven依赖的地方，全部增加Gradle的依赖。Gradle是有很大批量的用户的，这块强烈见要做到。
2.首页【开始】有 [在SpringBoot环境集成]、[在WebFlux环境集成]。这么重要的板块，强烈建议把[在Spring Cloud环境集成] 放到这个位置。毕竟Java web两大核心框架springboo和spring cloud。往前放放。
3.文档不怕全。药水哥问的问题，省长你也应该放到文档里。因为这都是常见问题，别人也会遇到。

### 应用场景阐述：
1.Gradle 和 Maven 都是重要项目管理工具。请支持。
2.satoken支持 spring cloud 是重点支持。请靠前。
3.做技术的，能力参差不齐。大家如果群里问，或者没加群，issue也等不到保姆级的回复，很多问题得不到结局，就凉凉了。所以，文档丰富是好事。

< 备注：请尽量详细描述功能应用场景 >
来自 sa-药水 真挚的建议

**Comment by uncarbon97** [comment]
"在Cloud集成"
还要区分 Feign 和 Dubbo 在用户态传递上的不同
加外链就行了，反正原来都有写，只是在目录最后面

**Comment by daiyun169** [comment]
token 的 redis 前缀是否可以支持 自定义呢？

**Comment by uncarbon97** [comment]
> token 的 redis 前缀是否可以支持 自定义呢？

配置项中的 token-name 和 StpUtil.type 都会参与前缀拼接；如果担心影响业务数据，可以使用 alone-redis 另外指定一个 database 甚至是 redis 实例

**Comment by click33** [comment]
我尽量
