### ISSUE TITLE
路由拦截鉴权 报错 NestedServletException

### ISSUE THREAD

**Issue by iehong** [dromara/Sa-Token#276]
### 使用版本:
1.30

### 报错信息：
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is cn.dev33.satoken.exception.NotLoginException: 未能读取到有效Token

### 希望结果：
不报错

### 复现步骤：
~~~java
public void addInterceptors(InterceptorRegistry registry) {
    // 注册 Sa-Token 的路由拦截器
    registry.addInterceptor(new SaRouteInterceptor())
        .addPathPatterns("/**")
        .excludePathPatterns("/user/register", "/user/login");
  }
~~~

类似 https://blog.csdn.net/qq_61317175/article/details/120784746

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177100485-dd588f40-aa2c-461e-a9d1-d0a2d40991c7.png)

**Comment by iehong** [comment]
~~~java
registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
    }))
~~~
改成这样可以

**Comment by click33** [comment]
访问的什么接口

**Comment by iehong** [comment]
> 访问的什么接口

获取用户信息

**Comment by click33** [comment]
路由是啥

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177102967-ce68879a-cecc-41c5-88ea-9a9d32a5ce4f.png)
还没上线 /api/user/info

**Comment by click33** [comment]
你添加了登录校验拦截器，只排除了："/user/register", "/user/login"
然后访问的： /api/user/info
被校验出：会话未登录
这不很正常吗

**Comment by click33** [comment]
从报错来看，是前端没有提交token

排查一下： 1、登录时有没有返回token 2、token有没有写入到前端cookie或localStore中 3、后续请求时，token有没有提交到后端

**Comment by iehong** [comment]
提交了 
改成

registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
    }))
正常的，应该是框架的问题

**Comment by click33** [comment]
你改成 
registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
}))

就没有校验了，没有校验当然就不报错了

仔细看文档：
![image](https://user-images.githubusercontent.com/36243476/177105020-e899001c-2432-4391-87f0-7f891bbf4aa6.png)

**Comment by iehong** [comment]
就算没提交token也不能报NestedServletException，应该报NotLoginException，报NestedServletException就是框架的锅

**Comment by click33** [comment]
你有写全局异常拦截处理器吗

**Comment by iehong** [comment]
写了 
~~~java
@ControllerAdvice
public class AllExceptionHandler {

  @ExceptionHandler(Exception.class)
  @ResponseBody
  public Result doException(Exception ex) {
    ex.printStackTrace();
    return Result.fail(500, "系统异常");
  }

  @ExceptionHandler(NotLoginException.class)
  @ResponseBody
  public Result doNotLoginException(NotLoginException ex) {
    return Result.fail(401, ex.getMessage());
  }
}
~~~

**Comment by click33** [comment]
你在浏览器f12看一下控制台，截图一下发送请求时的 token 参数我看看

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177108467-b13105d5-284d-40ce-bb69-d0aa433b4e3b.png)

**Comment by click33** [comment]
后端的 yml 配置中，token-name 参数有改动吗

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177110914-e5b60cf5-bfec-4775-a737-a5ce6417211b.png)

**Comment by click33** [comment]
你打印一下  StpUtil.getTokenValue()  看看能成功获取到前端提交的 token 吗

**Comment by iehong** [comment]
框架的锅，别再说我没传token了

**Comment by Abandoned9** [comment]
有没有可能真的是你有问题？
首先，你访问的是/api/user/info
你的拦截器里面写的是
``` java
public void addInterceptors(InterceptorRegistry registry) {
    // 注册 Sa-Token 的路由拦截器
    registry.addInterceptor(new SaRouteInterceptor())
        .addPathPatterns("/**")
        .excludePathPatterns("/user/register", "/user/login");
  }
```  
excludePathPatterns是放行的路由地址，你只放了/user/register，你的/api前缀呢？  
其次，你说改成下面的代码就行  
``` java
registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
}))
```
你真的懂上面写法的含义吗？  
再有，你仔细看看上面的错误类型，你看报错信息里面写的不就是NotLoginException吗？只是被包了一层NestedServletException

然后你上面发的那个csdn的博客那博主怕是自己都没写明白，属于是俩臭皮匠，顶不了一个臭皮匠了

**Comment by iehong** [comment]
> 有没有可能真的是你有问题？ 首先，你访问的是/api/user/info 你的拦截器里面写的是
> 
> ```java
> public void addInterceptors(InterceptorRegistry registry) {
>     // 注册 Sa-Token 的路由拦截器
>     registry.addInterceptor(new SaRouteInterceptor())
>         .addPathPatterns("/**")
>         .excludePathPatterns("/user/register", "/user/login");
>   }
> ```
> 
> excludePathPatterns是放行的路由地址，你只放了/user/register，你的/api前缀呢？ 其次，你说改成下面的代码就行
> 
> ```java
> registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
> }))
> ```
> 
> 你真的懂上面写法的含义吗？ 再有，你仔细看看上面的错误类型，你看报错信息里面写的不就是NotLoginException吗？只是被包了一层NestedServletException
> 
> 然后你上面发的那个csdn的博客那博主怕是自己都没写明白，属于是俩臭皮匠，顶不了一个臭皮匠了

没有可能，是框架的锅
改成

registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
}))
正常的

**Comment by Abandoned9** [comment]
> ![image](https://user-images.githubusercontent.com/5433554/177100485-dd588f40-aa2c-461e-a9d1-d0a2d40991c7.png)

还有，你这错误是CORS错误，你给我好好的先弄明白跨域问题再说？

**Comment by Abandoned9** [comment]
你知道你上面那么写为什么正常了吗？
你上面那种写法跟你把sa-token从你的maven里删掉是一个意思，你要真不明白你别用了

**Comment by iehong** [comment]
~~~java
@Override
  public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOriginPatterns("*")
        .allowedMethods("*");
  }
~~~

跨域

**Comment by Abandoned9** [comment]
``` java
public void addInterceptors(InterceptorRegistry registry) {
    // 注册 Sa-Token 的路由拦截器
    registry.addInterceptor(new SaRouteInterceptor())
        .addPathPatterns("/**")
        .excludePathPatterns("/user/register", "/user/login");
  }
```

上面的代码表示拦截`/**`所有路径，但是放行`/user/register`和`/user/login`  
你`/api/user/login`和你`/user/login`有什么关系？有个寄吧关系

**Comment by iehong** [comment]
大家踩这说脏话，没素质，秀优越的人

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177123111-b7ff1a87-a08b-48a0-82ca-e108f1079c63.png)
apis是写在这里的

**Comment by Abai-LL** [comment]
> ![image](https://user-images.githubusercontent.com/5433554/177100485-dd588f40-aa2c-461e-a9d1-d0a2d40991c7.png)

CORS跨域开了吗

**Comment by iehong** [comment]
> ```java
> @Override
>   public void addCorsMappings(CorsRegistry registry) {
>     registry.addMapping("/**")
>         .allowedOriginPatterns("*")
>         .allowedMethods("*");
>   }
> ```

@Override
  public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOriginPatterns("*")
        .allowedMethods("*");
  }
开了

**Comment by Abai-LL** [comment]
> 

改成这样 Sa-token直接不校验了    Sa-token都不跑了   怎么可能报错

**Comment by 980421** [comment]
无意间翻翻issue   看到了你这个问题   小伙子给你个建议   如果看不懂或者用不明白   好几千人都能帮你解决    没必要在这丢人现眼    加群   10分钟给你解决了

**Comment by Abai-LL** [comment]
> 提交了 改成
> 
> registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> { })) 正常的，应该是框架的问题

改成这样 Sa-token直接不校验了 Sa-token都不跑了 怎么可能报错

**Comment by Abandoned9** [comment]
sa-token 官方2群614714762 来吧

**Comment by 980421** [comment]
你这里面总共就两个问题   第一个路由拦截路径写的不对   另外就是你没传token    checkLogin方法你都调用了    日志写的多明白

**Comment by click33** [comment]
你配置前缀了吗？sa-token.token-prefix

**Comment by click33** [comment]
前端提交了，但后端却没获取到，看看后端接受到token参数了吗

打印 StpUtil.getTokenValue() 看看有值吗
然后再打印 SaHolder.getRequest().getHeader("Authorization") 看看有值吗

**Comment by iehong** [comment]
registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> { console.log(StpUtil.getTokenValue()) }))  这样就正常了 只有写在这里面，不然报没有剩下文的错

**Comment by iehong** [comment]
~~~java
package com.yyt.jdfyakfp.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import cn.dev33.satoken.interceptor.SaRouteInterceptor;
import cn.dev33.satoken.jwt.StpLogicJwtForSimple;
import cn.dev33.satoken.stp.StpLogic;

@Configuration
public class SaTokenConfigure implements WebMvcConfigurer {
  // Sa-Token 整合 jwt (Simple 简单模式)
  @Bean
  public StpLogic getStpLogicJwt() {
    return new StpLogicJwtForSimple();
  }

  // 注册拦截器
  @Override
  public void addInterceptors(InterceptorRegistry registry) {
    // 注册 Sa-Token 的路由拦截器
    registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
    }))
        .addPathPatterns("/**")
        .excludePathPatterns("/user/register", "/user/login");
  }

  @Override
  public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOriginPatterns("*")
        .allowedMethods("*");
  }
}

~~~

**Comment by click33** [comment]
那你倒是说一下，这两个打印有值吗

```
打印 StpUtil.getTokenValue() 看看有值吗
然后再打印 SaHolder.getRequest().getHeader("Authorization") 看看有值吗
```

**Comment by AppleOfGray** [comment]
当前问题异议很大, 如果还是无法解决,建议提供能复现当前bug的最小开发项目压缩包或开源的项目地址(请务必删除私人信息), 我们将在本地测试后再提供相关指导意见.

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177237769-4783618d-2738-4d62-beec-9636e5e856c7.png)
postman 测试室可以的，是不是前端请求头有点问题

**Comment by click33** [comment]
我知道你前端提交 token 了，但是后端框架没有接受到这个参数，所以我想知道在 SpringMVC 层面解析到这个参数了吗，需要你打印一下这两句代码来确认一下：
```
打印 StpUtil.getTokenValue() 看看有值吗
然后再打印 SaHolder.getRequest().getHeader("Authorization") 看看有值吗
```
希望你可以测试一下提供结果

**Comment by iehong** [comment]
~~~java
registry.addInterceptor(new SaRouteInterceptor((req, res, handler) -> {
      Console.log(StpUtil.getTokenValue());
      Console.log(SaHolder.getRequest().getHeader("Authorization"));
    }))
~~~
![image](https://user-images.githubusercontent.com/5433554/177241322-588b0c97-00fb-4033-83d9-1b035ce5c858.png)

**Comment by iehong** [comment]
写这个 (req, res, handler) ->    前端就不会卡住的
![image](https://user-images.githubusercontent.com/5433554/177241594-78439ee5-3f3b-4cf4-9114-33dbf211e9f9.png)
三次请求

**Comment by click33** [comment]
再多打印几个我看看
```
Console.log(StpUtil.getTokenName());
		Console.log(StpUtil.getTokenValue());
	    Console.log(SaHolder.getRequest().getHeader("Authorization"));
		Console.log(SaManager.getConfig());
```

**Comment by iehong** [comment]
~~~log
2022-07-05 11:11:34.875  INFO 6628 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2022-07-05 11:11:35.904  INFO 6628 --- [nio-8080-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiS0szR25zQ0xIemFsRDhYUlU1UzE0OWpiWXFpRE5EdVkifQ.mLj5nSa9zvp_NLkS6hNWmITFt403yffeyQWkXrP31vY
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
~~~

**Comment by click33** [comment]
目前看配置方面没啥问题，你再加俩我看看
``` java
Console.log(StpUtil.getTokenName());
		Console.log(StpUtil.getTokenValue());
	    Console.log(SaHolder.getRequest().getHeader("Authorization"));
		Console.log(SaManager.getConfig());
		Console.log(SaHolder.getRequest().getRequestPath());
		Console.log(SaHolder.getRequest().getMethod());
```

**Comment by iehong** [comment]
~~~log

2022-07-05 11:15:31.707  WARN 6628 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [cn.dev33.satoken.exception.NotLoginException: 未能读取到有效Token]
2022-07-05 11:15:54.307  INFO 6628 --- [nio-8080-exec-2] com.alibaba.druid.pool.DruidDataSource   : {dataSource-2} inited
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
/user/info
GET
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
/workspace/info
GET
Authorization
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsInJuU3RyIjoiRDJ5TGFQeHBFblJOdmg3T2FsVTExdHliUkpNUG9GZ2MifQ.jtD8sBxm3wEfICGU0YqEnoRDILLVomx-ioAZxiHgx48
SaTokenConfig [tokenName=Authorization, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=false, maxLoginCount=12, isReadBody=true, isReadHead=true, isReadCookie=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=false, jwtSecretKey=1qaz2wsx3edc, idTokenTimeout=86400, basic=, currDomain=null, checkIdToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]]
/error
GET
~~~

**Comment by iehong** [comment]
加上(req, res, handler) ->这个是不报错的

**Comment by click33** [comment]
加上(req, res, handler) ->这个是不报错，
是因为加上这个后，相当于把 Sa-Token 的鉴权给关闭了，关闭了当然就不会报错了

**Comment by click33** [comment]
这里为啥有个 /error
你有访问这个接口吗
![image](https://user-images.githubusercontent.com/36243476/177242912-7720139a-f93e-4e0f-a166-2b0a9ac8685b.png)

**Comment by iehong** [comment]
没有，估计是sa-token访问的

**Comment by click33** [comment]
sa-token 是个鉴权框架，不是个http请求框架，不会发送请求

**Comment by click33** [comment]
你弄个复现的demo上传一下吧，我下载到本地调试一下

**Comment by AppleOfGray** [comment]
关于这个博客, 我作出了相关回复: https://blog.csdn.net/qq_61317175/article/details/120784746

**Comment by click33** [comment]
或者你加一下微信、qq群，我给你远程

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177247439-aa190cd6-e203-4be9-b078-dd2ee1c31c2e.png)

**Comment by AppleOfGray** [comment]
1群和2群总人数都是快2千了,
大部分开发者都是会使用satoken框架的, 
所以平时闲聊也就不足为怪了.
如果有技术问题他们还是会优先回答的.
开放新群的目的就是给新人一个融入的机会,
人数少回答问题也方便.

**Comment by qzmer1104** [comment]
> > ```java
> > @Override
> >   public void addCorsMappings(CorsRegistry registry) {
> >     registry.addMapping("/**")
> >         .allowedOriginPatterns("*")
> >         .allowedMethods("*");
> >   }
> > ```
> 
> @OverRide public void addCorsMappings(CorsRegistry registry) { registry.addMapping("/**") .allowedOriginPatterns("_") .allowedMethods("_"); } 开了

很简单的问题，https://blog.csdn.net/huangyaa729/article/details/103893660

cors尽量不要用此方式添加如果你们都不看源码的情况，可以用过滤器加，加个config的bean就好了
`
@Bean
    public FilterRegistrationBean corsFilter() {

        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();

        CorsConfiguration config = new CorsConfiguration();

        config.setAllowCredentials(true);

        config.addAllowedOrigin("*");

        config.addAllowedHeader(CorsConfiguration.ALL);
        config.addAllowedMethod(CorsConfiguration.ALL);

        source.registerCorsConfiguration("/**", config);

        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));

        bean.setOrder(Ordered.HIGHEST_PRECEDENCE);

        return bean;
    }
`

**Comment by Enaium** [comment]
controller有异常的时候，并不会抛出controller的异常，只会抛出`未能读取到有效Token`这个异常

**Comment by lizeze** [comment]
> 这里为啥有个 /error 你有访问这个接口吗 ![image](https://user-images.githubusercontent.com/36243476/177242912-7720139a-f93e-4e0f-a166-2b0a9ac8685b.png)

我遇到过这样的问题，前端传的请求是带token的没问题，但是方法执行过程中出现异常，然后就访问 `/error`，这个时候就报错`未能读取到有效Token`

**Comment by Huzhengtao** [comment]
> 你这里面总共就两个问题 第一个路由拦截路径写的不对 另外就是你没传token checkLogin方法你都调用了 日志写的多明白



> ```java
> public void addInterceptors(InterceptorRegistry registry) {
>     // 注册 Sa-Token 的路由拦截器
>     registry.addInterceptor(new SaRouteInterceptor())
>         .addPathPatterns("/**")
>         .excludePathPatterns("/user/register", "/user/login");
>   }
> ```
> 
> 上面的代码显示截取`/**`所有路径，但是放行`/user/register`和`/user/login` 你`/api/user/login`和你`/user/login`有什么关系？有一个寄存吧关系
戾气太重，这是框架和跨域的冲突问题。spring使用注册WebMvcConfigurer的addCorsMappings方法的方式做跨域会导致options预检请求也会检测token，但options预检请求不会携带自定义header，就会抛出异常，然后spring会把请求重定向到/error。换成注册CorsFilter来做跨域就会正常了
