### ISSUE TITLE
退出登录后，redis登录信息还存在

### ISSUE THREAD

**Issue by iehong** [dromara/Sa-Token#277]
### 对以下问题有疑问:
集成redis后，退出登录后，redis登录信息还存在，这是正常的吗

**Comment by click33** [comment]
咋退出的
调用代码，还是直接关闭的浏览器

**Comment by iehong** [comment]
~~~java
@GetMapping("logout")
  public Result logout() {
    StpUtil.logout();
    return Result.success("ok");
  }
~~~

**Comment by iehong** [comment]
代码退出

**Comment by iehong** [comment]
![image](https://user-images.githubusercontent.com/5433554/177103323-7bf004a5-5f39-4271-b596-1384a550ac1c.png)

**Comment by click33** [comment]
手动把数据全部清除了，然后再重新登录、注销测试一下，还这样的话，就不正常

**Comment by iehong** [comment]
清除过 还这样 
![image](https://user-images.githubusercontent.com/5433554/177104458-b511db6e-30e6-4f01-8689-45f96c93c159.png)
![image](https://user-images.githubusercontent.com/5433554/177104486-5c06fb5e-c5c5-400e-a299-74c871026e8f.png)

**Comment by click33** [comment]
整理复现bug的代码demo，或者录个屏看看

**Comment by click33** [comment]
怎么关闭了？是问题已解决，还是不用解决了
