### ISSUE TITLE
建议登录的时候SaLoginModel 暴露activityTimeout参数

### ISSUE THREAD

**Issue by bijialin** [dromara/Sa-Token#279]
### 建议增加的新功能:
建议登录的时候SaLoginModel 暴露activityTimeout参数
### 应用场景阐述：
activityTimeout有可能来自系统设置中，不直接配置在配置文件，
登录的时候有些场景需要按用户、用户组进行设置activityTimeout

**Comment by click33** [comment]
架构设计所限，SaLoginModel 中无法添加 activityTimeout 参数，只能在全局配置中统一设置
