### ISSUE TITLE
支持批量注销吗

### ISSUE THREAD

**Issue by ljlzzzzz** [dromara/Sa-Token#280]
有一些场景需要针对应用全量下线(相当于强制更新)，比如说根据StpUtil的type或者批量根据loginid注销

**Comment by click33** [comment]
框架没有直接支持这一点，不过你可以手动做到：
方法一：利用 [会话治理] API ，获取全部会话，逐个注销
方法二：注解操作redis，删除指定前缀下的所有key

**Comment by ljlzzzzz** [comment]
好的 我想到这两种方案了 只是想着有根据type区分的话 业务就不用处理这个了，看来还是得要走方案1了，谢谢
