### ISSUE TITLE
官网文档 和 jwt 集成支持扩展参数，但未看到设置jwt sign默认算法，建议增加

### ISSUE THREAD

**Issue by stef4java** [dromara/Sa-Token#285]
### 建议增加的新功能:
官网文档 和 jwt 集成支持扩展参数，但未看到设置jwt sign默认算法[扩展参数](https://sa-token.dev33.cn/doc/index.html#/plugin/jwt-extend?id=_6%e3%80%81%e6%89%a9%e5%b1%95%e5%8f%82%e6%95%b0)
 
### 应用场景阐述：
需要和一个老项目 sign算法保持一致。

**Comment by click33** [comment]
已上提案
