### ISSUE TITLE
建议添加更加安全的密码摘要加密算法

### ISSUE THREAD

**Issue by lyc8503** [dromara/Sa-Token#287]
### 建议增加的新功能:
更加安全的密码摘要加密算法, 如 BCrypt, HMAC, PBKDF2 等.
https://sa-token.dev33.cn/doc/index-backup.html#/up/password-secure

### 应用场景阐述：
目前加盐哈希的实现使用了组合哈希函数的方法, 本身有一定争议.
且目前使用的 MD5 加密已经被公认为存在缺陷的一种摘要算法.

**Comment by click33** [comment]
密码加密可以参考 hutool： 
https://hutool.cn/docs/#/crypto/%E6%A6%82%E8%BF%B0
已经封装的比较完善了

Sa-Token 不打算重复造这一块的轮子了

**Comment by lyc8503** [comment]
了解了, 感谢!

**Comment by lyc8503** [comment]
无意中发现了 cn.dev33.satoken.secure 中包含了一个 BCrypt, 注明了来自 https://github.com/jeremyh/jBCrypt
但在文档中没有相关说明, 是文档缺失说明还是这个包并不打算给用户使用?

**Comment by click33** [comment]
是文档迟滞了
