### ISSUE TITLE
sa-core 和sa-token-spring-boot starter 在java9 module下包冲突

### ISSUE THREAD

**Issue by vicykie** [dromara/Sa-Token#288]
### 使用版本:
`            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-spring-boot-starter</artifactId>
                <version>1.30.0</version>
            </dependency>`

### 报错信息：

java: 模块 dv.util 同时从 sa.token.spring.boot.starter 和 sa.token.core 读取程序包 cn.dev33.satoken.filter

### 希望结果：
修改包名

**Comment by click33** [comment]
目前暂没有精力适配 java9
