### ISSUE TITLE
建议可以着手准备 spring 6 ,spring boot3适配了。

### ISSUE THREAD

**Issue by os7blue** [dromara/Sa-Token#290]
### 建议增加的新功能:

 近期尝试springboot3 -m3 ，使用下来发现已经趋于完善了，但随着jdk版本的变化，各种包的迁移，势必会对各种框架/库造成影响。

### 应用场景阐述：

在尝试引入sa-token,就出现了因为包路径的改变引起的问题，暂时自己写了一套比较方便以后satoken支持springboot3的时候进行替换的逻辑

### 备注：
例子如下：
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/33112372/183729863-a06617f6-bfa9-4cc8-bd8e-e57b29f74205.png">

以上纯属个人建议，谢谢作者。

**Comment by ly-chn** [comment]
是的, 感谢提议

**Comment by click33** [comment]
已上提案
