### ISSUE TITLE
登录，获取登录信息都很慢，比直接用redis慢了10倍左右的时间

### ISSUE THREAD

**Issue by hahafreeasair666** [dromara/Sa-Token#293]
### 使用版本:
1.30.0
Sa-Token 整合 Redis （使用 jackson 序列化方式）
### 报错信息：
没报错，就是很慢，登录，获取登录信息都很慢，比直接用redis慢了10倍左右的时间

### 希望结果：
与直接使用redis慢不了多少

### 复现步骤：
无

**Comment by hahafreeasair666** [comment]
satoken
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/35718045/185529203-5bb348e1-8e64-4121-906d-08360751dbf4.png">
直接redis
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/35718045/185529271-4366f422-528b-4514-8c4c-3e6e5fc7a5df.png">
二者均包含了续期与获取当前登录用户信息

**Comment by click33** [comment]
我本地测试的没这么慢，你这是不是因为项目启动后首次调用要初始化一堆组件给带来的慢？多调用几次都这么慢吗？

**Comment by click33** [comment]
建议加入交流群提供代码反馈
