### ISSUE TITLE
StpLogic.isValidLoginId() 登陆id小于0时会认定为无效

### ISSUE THREAD

**Issue by zhongjun96** [dromara/Sa-Token#294]
### 对以下问题有疑问:
系统有设置 **后门用户**，id都是小于0的。
``` java
/**
* 判断一个 loginId 是否是有效的 
* @param loginId 账号id 
* @return / 
*/
public boolean isValidLoginId(Object loginId) {
    return loginId != null && !NotLoginException.ABNORMAL_LIST.contains(loginId.toString());
}
/** 
* 代表异常token的标志集合 
*/
//此list包含-1～-5。导致id=-1的获取用户使用 isLogin() 方法失败。
public static final List<String> ABNORMAL_LIST = Arrays.asList(NOT_TOKEN, INVALID_TOKEN, TOKEN_TIMEOUT, BE_REPLACED, KICK_OUT); 

```
不理解为何要有`!NotLoginException.ABNORMAL_LIST.contains(loginId.toString())` 这部分判断，
并没有发现异常的时候会设置当前登录用户id为负数的逻辑。

**Comment by click33** [comment]
-1 到 -5 是五个异常值，对应五种 未登录状态：
![image](https://user-images.githubusercontent.com/36243476/185775379-06e031ed-cb4e-41f8-988b-95de5bcb8339.png)

你需要在调用 StpUtil.login() 时避开这几个值
