### ISSUE TITLE
可以实现像调用微信api一样通过密钥方式鉴权接口嘛，不使用token方式，是不是一样开箱即用

### ISSUE THREAD

**Issue by gaobinbin991314** [dromara/Sa-Token#295]
请在以下地址复制 issue 模板进行提交：
https://sa-token.dev33.cn/doc/index.html#/fun/issue-template

**Comment by click33** [comment]
参考 Sa-Token OAuth2 模块
https://sa-token.dev33.cn/doc/index.html#/oauth2/readme
