### ISSUE TITLE
请配置 Http 请求处理器

### ISSUE THREAD

**Issue by makesence** [dromara/Sa-Token#297]
### 使用版本:
1.30.0

### 报错信息：
请配置 Http 请求处理器

### 希望结果：
不报错

### 复现步骤：
sso单点登录模式3，集成到自己系统
Object loginId = SaSsoHandle.checkTicket(ticket, "/sso/doLoginByTicket");
这一行报错了

**Comment by click33** [comment]
仔细看文档：
![image](https://user-images.githubusercontent.com/36243476/186558410-a3425f85-c905-40dc-86df-2374cc72ab96.png)
