### ISSUE TITLE
Referrer Policy: strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by makesence** [dromara/Sa-Token#298]
使用版本:
1.30.0

报错信息：
![image](https://user-images.githubusercontent.com/12952893/186567186-5b643a3b-46ba-4d85-aa63-885f3846505b.png)

希望结果：
不报错

复现步骤：
sso单点登录模式3，集成到自己系统
客户端前端调用客户端后端的sso/logout接口报错了

**Comment by makesence** [comment]
![image](https://user-images.githubusercontent.com/12952893/186568792-8ed757d0-f049-440d-88ed-d75c0ccfb2b1.png)
经过调试，好像是后端返回时跳转页面跨域了

**Comment by click33** [comment]
把 back 参数指定一个具体的地址

**Comment by makesence** [comment]
![image](https://user-images.githubusercontent.com/12952893/186570175-4f44d7e8-6121-4e04-9a6e-722447f85fcf.png)
刚看错，这里我有指定back的地址

**Comment by click33** [comment]
前端怎么调用的，截图看看

**Comment by makesence** [comment]
![image](https://user-images.githubusercontent.com/12952893/186570504-2f588c42-6eae-46ff-89af-5c1d559b5b7a.png)
前端vue

**Comment by click33** [comment]
Ajax异步调用，不要加 back  参数

**Comment by click33** [comment]
把 token 提交上去

**Comment by makesence** [comment]
不传back不报错了，调用logout后再调一次接口判断登录状态，不用跳转页面

**Comment by click33** [comment]
可参考：
![image](https://user-images.githubusercontent.com/36243476/186572022-bca5c20e-578f-44c7-888f-d0c3669930f2.png)
