### ISSUE TITLE
建议增加新功能

### ISSUE THREAD

**Issue by chushanming** [dromara/Sa-Token#301]
### 建议增加的新功能:
授权特定IP进行访问的功能

### 应用场景阐述：
限定特殊的接口，如管理接口等，在本地或特定的IP可以访问，隐蔽和保护这些接口。
作用类似于Spring Security中的hasIpAddress函数。

**Comment by click33** [comment]
这个需求 手动获取 ip 字符串 equals 一下不就好了

**Comment by chushanming** [comment]
如果用逻辑的话，用限定权限也可以的，但是这样的话，外部还是能访问到这个接口，仅仅是不返回结果，就单纯的不想被探测到管理接口的URL

**Comment by click33** [comment]
那你加个全局过滤器来判断，校验不通过直接返回拒绝访问

**Comment by chushanming** [comment]
那需不需要加一个checkLogin一样的注解？或者我来写

**Comment by click33** [comment]
我意思是这个功能手动写也费不了多大劲，没必要加在 Sa-Token 中 ，Sa-Token 主打登录校验和权限校验，不想附加太多其他功能 😥

**Comment by chushanming** [comment]
理解
