### ISSUE TITLE
reactor的小建议

### ISSUE THREAD

**Issue by hanjieliao** [dromara/Sa-Token#303]
### 建议增加的新功能:

sa-token-reactor-spring-boot-starter
和
sa-token-spring-boot-starter

是不是应该做个兼容处理？ 同时引入这两个包会有错误

### 应用场景阐述：
我的需求是这样的， 我打算把sa-token抽成项目的一个模块引入， 加个boolean reactor的配置， true就注入SaReactorFilter 否则注入SaServletFilter， 但是实际运行的时候我发现SaBeanRegister已经有了冲突

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
这是因为 SpringBoot 无法同时引入 `spring-boot-starter-web` 和 `spring-boot-starter-webflux` 两个包，
不是 Sa-Token 做出的限制
