### ISSUE TITLE
将 token 编码写入 Cookie 后，其风格将和其它情景不一致，Sa-Token 目前不打算通过此方式实现这个功能。

### ISSUE THREAD

**Issue by sunl888** [dromara/Sa-Token#314]
将 token 编码写入 Cookie 后，其风格将和其它情景不一致，Sa-Token 目前不打算通过此方式实现这个功能。

After the token code is written into the cookie, its style will be inconsistent with other scenarios. SA token does not intend to realize this function in this way at present.

_Originally posted by @click33 in https://github.com/dromara/Sa-Token/issues/250#issuecomment-1118511172_
      
请问这个问题现在解决了吗？这边使用1.30.0版本还是出现这个问题了

**Comment by sunl888** [comment]
我们现在的做法是覆写 StpLogic的getTokenValueNotCut()方法

**Comment by click33** [comment]
> 

那就先这样解决吧，Sa-Token 目前不准备增加在Cookie中使用 token 前缀的功能
