### ISSUE TITLE
sso在前后分离场景下, 关于使用其他语言客户端

### ISSUE THREAD

**Issue by gaozhenyusky** [dromara/Sa-Token#315]
### 对以下问题有疑问:

请问一下前后分离场景下, 如果使用sa-token作为sso的服务端, 客户端是golang或其他语言的话怎样做(我看了文档, 但还不是太清楚)
,客户端是否直接用http的方式从sso-server来获取session是否存在来模拟stpUtil.isLogin()

**Comment by click33** [comment]
![image](https://user-images.githubusercontent.com/36243476/192666130-e98975ef-c816-4122-9d58-fe2e01bce816.png)

https://sa-token.dev33.cn/doc/index.html#/sso/sso-apidoc

**Comment by gaozhenyusky** [comment]
thx

**Comment by gaozhenyusky** [comment]
你好, demo看了下主要是把userId放到httpSession里
我还有个问题请教下, nosdk前后分离场景下, 前端带着token来请求接口, filter在每次请求都验证isLogin这种壮态, 如果为false则返回401, 想问下client关于isLogin这种状态是需要用http的方式用token作为入参请求sso-server的接口来验证吗, 这里不太明白

**Comment by click33** [comment]
nosdk 的意思就是指没有 sdk，就是指不使用 Sa-Token 。
既然不使用 Sa-Token 了，那你肯定就要使用别的框架来管理会话。
既然你使用别的框架来管理会话了，那你就得用这个框架来生成token，
既然你用这个框架来生成token了，那你也得用这个框架来校验。

意思就是指：Sa-Token 只负责生成 ticket，client 端拿着 ticket 换到 loginId 后，剩下的 登录、校验、鉴权啥的，都在 client 端独立完成，和 sso-server 无关了

**Comment by gaozhenyusky** [comment]
明白了 thx
