### ISSUE TITLE
请问要在哪里进行改造 ，实现session 等数据 双写进 redis 

### ISSUE THREAD

**Issue by saheibe** [dromara/Sa-Token#318]
### 建议增加的新功能:
redis客户端双写 

### 应用场景阐述：
整个系统双活架构  

请问这个要在哪里进行改造 ，实现session 等数据 双写进 redis ，数据一致性要求不高

**Comment by click33** [comment]
实现 SaTokenDao 接口，每次往两个数据源里 set 数据
