### ISSUE TITLE
建议将token-style配置为enum而非String, IDEA中代码提示不友好

### ISSUE THREAD

**Issue by ly-chn** [dromara/sa-token#32]
建议将token-style配置为enum而非String, IDEA中代码提示不友好
例如mybatis-plus中的
![图片](https://user-images.githubusercontent.com/37045167/106243083-ab3a7d00-6243-11eb-95f0-cc5c30b1eb9b.png)

**Comment by click33** [comment]
😎😎😎

**Comment by click33** [comment]
枚举影响自定义类型的拓展
