### ISSUE TITLE
Sa-Token-OAuth2 Server端在配置sa-token.token-prefix: Bearer参数后，登录后获取授权码时在检查cookie中的token时失败

### ISSUE THREAD

**Issue by NickLuo21** [dromara/Sa-Token#321]
### 使用版本:
1.30.0

### 报错信息：
Sa-Token-OAuth2 Server端在配置sa-token.token-prefix: Bearer参数后，登录获取授权码时在检查用户是否登录时失败
StpLogic.setTokenValueToCookie方法中setValue时不会判断sa-token.token-prefix: Bearer参数，但是在StpLogic.getTokenValue方法中，会根据sa-token.token-prefix: Bearer参数来裁剪token，从而导致已登录但是从cookie中获取token失败

**Comment by click33** [comment]
官网有提到哦，用了前缀模式后就不能用Cookie模式了

![image](https://user-images.githubusercontent.com/36243476/197083666-2c695db3-7a5e-4395-b922-cf2a70498344.png)
