### ISSUE TITLE
临时Token的存活期问题

### ISSUE THREAD

**Issue by mark0614** [dromara/Sa-Token#327]
### 对以下问题有疑问:
移动端的临时token过期时间设置成15天，而PC端的临时token过期时间设置成2小时；这个问题怎么解决？

**Comment by click33** [comment]
临时token是每次调用时传入有效时间
``` java
SaTempUtil.createToken("10014", 200);
```

你直接写个if判断不就好了？

**Comment by mark0614** [comment]
大神，可能我我描述的不是特别准确。这个SaTempUtil的使用场景跟我说的还有点区别。我的场景如下：
在多端登录场景下（PC、PAD、PHONE），我想实现PC端的有效期是2小时，PAD端有效期是10天，PHONE端有效期15天。之前看过[Token有效期详解](https://sa-token.cc/doc.html#/fun/token-timeout?id=token%e6%9c%89%e6%95%88%e6%9c%9f%e8%af%a6%e8%a7%a3)这篇文章，感觉应该从activity-timeout这块儿入手，一直不知道怎么解决，我也看了[saToken多端登录](https://blog.csdn.net/ControlDemo/article/details/122428512)这个文章，感觉不是很优雅。希望作者能给出点解决思路，谢谢！
