### ISSUE TITLE
鉴权与切面问题

### ISSUE THREAD

**Issue by hanjieliao** [dromara/Sa-Token#331]
### 对以下问题有疑问:

我的项目是多租户系统，然后要求每个租户不同数据库， 所以我专门有个Interceptor切面在controller做数据源切换， 但是Sa-token的拦截器是HandlerInterceptoer的， 我的切面拦截器是MethodInterceptor的， 有什么办法可以让Sa-token的拦截器在我的拦截器后面执行吗？ 不然切换不了数据源，权限查的东西不对

**Comment by click33** [comment]
把源码复制出来自己改改
