### ISSUE TITLE
iphone登陆后和每call url, 后台都报NotLoginException

### ISSUE THREAD

**Issue by 98549844** [dromara/Sa-Token#335]
### 使用版本:
1.32

### 报错信息：
thymeleaf + springboot

用普通电脑登陆后, 然后到处点击url, 后台都不会报NotLoginException
但用iphone的chrome / safari login 后
每call url (controller) 都会报 NotLoginException: 未能读取到有效Token
但frand-end / 页面, 什么事都没有, 后台就是一直报 NotLoginException
![image](https://user-images.githubusercontent.com/26402108/201375231-fc06cc70-d931-44f9-97c5-b1ffcd9f5097.png)

### 希望结果：
iphone登陆后, 理应如电脑登入一般的日志
![image](https://user-images.githubusercontent.com/26402108/201375483-f6e6eb71-b8b8-42f6-b10e-4fd1aa784c36.png)

### 复现步骤：
用普通电脑登陆后, 然后到处点击url, 后台都不会报NotLoginException
但用iphone的chrome / safari login 后
每call url (controller) 都会报 NotLoginException: 未能读取到有效Token
但frand-end / 页面, 什么事都没有, 后台就是一直报 NotLoginException

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ly-chn** [comment]
给出的信息无法判断, 建议复制iPhone设备的curl或者fetch api发一下

**Comment by 98549844** [comment]
![image](https://user-images.githubusercontent.com/26402108/203922809-ac60b06e-1b55-434d-ad2b-ed8bb87a5608.png)

这是后台打出来的log

**Comment by 98549844** [comment]
[iphone curl.txt](https://github.com/dromara/Sa-Token/files/10089443/iphone.curl.txt)

iCurlHTTP v1.17

URL: 192.168.2.140:8088/ace/play.html?playId=7bcd72f1-ab00-41db-b5fe-41edd34b2b25
Date: Friday 25 Nov 2022, 3:18 PM

--   Trying 192.168.2.140:8088...
-- Connected to 192.168.2.140 (192.168.2.140) port 8088 (#0)
>> GET /ace/play.html?playId=7bcd72f1-ab00-41db-b5fe-41edd34b2b25 HTTP/1.1
>> Host: 192.168.2.140:8088
>> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
>> Accept: */*
>> Connection: Upgrade, HTTP2-Settings
>> Upgrade: h2c
>> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
>>
>>
-- Mark bundle as not supporting multiuse
HTTP/1.1 200
Content-Type: text/html;charset=UTF-8
Content-Language: zh-TW
Transfer-Encoding: chunked
Date: Fri, 25 Nov 2022 07:17:17 GMT

2000
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>Login Page - Ace Admin</title>

    <meta name="description" content="User login page"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/assets/font-awesome/4.5.0/css/font-awesome.min.css"/>

    
    <link rel="stylesheet" href="/assets/css/fonts.googleapis.com.css"/>

    
    <link rel="stylesheet" href="/assets/css/ace.min.css"/>

    
    <link rel="stylesheet" href="/assets/css/ace-rtl.min.css"/>

    

    

    
    <link rel="shortcut icon" href="/assets/images/favicon.ico">
</head>

<body class="login-layout">
<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="center">
                        <h1>
                            <i class="ace-icon fa fa-leaf green"></i>
                            <span class="red">ACE</span>
                            <span class="white" id="id-text2">APPLICATION</span>
                        </h1>
                        <h4 class="blue" id="id-company-text">&copy; Company Ace</h4>
                    </div>

                    <div class="space-6"></div>

                    <div class="position-relative">
                        <div id="login-box" class="login-box visible widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header blue lighter bigger">
                                        <i class="ace-icon fa fa-coffee green"></i>
                                        Please Enter Your Information
                                    </h4>
                                   


                                    <div class="space-6"></div>

                                    
                                    <form action="/ace/logging.html" method="post">
                                        <fieldset>
                                            <input type="hidden" name="deviceType" id="deviceType"/>
                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="text" class="form-control"
                                                           id="loginAccount" name="userAccount"
                                                           value=""
                                                           placeholder="Account"/>
                                                    <i class="ace-icon fa fa-user"></i>
                                                </span>
                                            </label>

                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="password" class="form-control"
                                                           id="pw" name="password"
                                                           placeholder="Password"/>
                                                    <i class="ace-icon fa fa-lock"></i>
                                                </span>
                                            </label>
                                            <div class="space"></div>
                                            <div class="clearfix">
                                                <label class="inline">
                                                    <input type="checkbox" name="rememberMe" class="ace" checked="checked"/>
                                                    <span class="lbl"> Remember Me </span>
                                                </label>

                                                <button type="submit" id="login-btns"
                                                        class="width-35 pull-right btn btn-sm btn-primary">
                                                    <i class="ace-icon fa fa-key"></i>
                                                    <span class="bigger-110">Login</span>
                                                </button>
                                            </div>

                                            <div class="space-4"></div>
                                        </fieldset>
                                    </form>

                                    <div class="social-or-login center">
                                        <span class="bigger-110">Or Login Using</span>
                                    </div>

                                    <div class="space-6"></div>

                                    <div class="social-login center">
                                        <a href="/resource/list" class="btn btn-primary">
                                            <i class="ace-icon fa fa-facebook"></i>
                                        </a>

                                        <a href="/ace/index.html" class="btn btn-info">
                                            <i class="ace-icon fa fa-twitter"></i>
                                        </a>

                                        <a href="/ace/blank" class="btn btn-danger">
                                            <i class="ace-icon fa fa-google-plus"></i>
                                        </a>
                                    </div>
                                </div>

                                <div class="toolbar clearfix">
                                    <div>
                                        <a href="#" data-target="#forgot-box" class="forgot-password-link">
                                            <i class="ace-icon fa fa-arrow-left"></i>
                                            I forgot my password
                                        </a>
                                    </div>

                                    <div>
                                        <a href="#" data-target="#signup-box" class="user-signup-link">
                                            I want to register
                                            <i class="ace-icon fa fa-arrow-right"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="forgot-box" class="forgot-box widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header red lighter bigger">
                                        <i class="ace-icon fa fa-key"></i>
                                        Retrieve Password
                                    </h4>

                                    <div class="space-6"></div>
                           
2000
        <p>
                                        Enter your email and to receive instructions
                                    </p>

                                    <form action="/ace/password/reset.html" method="post">
                                        <fieldset>
                                            <label class="block clearfix">
<span class="block input-icon input-icon-right">
<input type="email" class="form-control"
                                                                   name="email" placeholder="Email"
                                                                   value=""/>
<i class="ace-icon fa fa-envelope"></i>
</span>
                                            </label>

                                            <div class="clearfix">
                                                <button type="submit" class="width-35 pull-right btn btn-sm btn-danger">
                                                    <i class="ace-icon fa fa-lightbulb-o"></i>
                                                    <span class="bigger-110">Send Me!</span>
                                                </button>
                                            </div>
                                        </fieldset>
                                    </form>
                                </div>

                                <div class="toolbar center">
                                    <a href="#" data-target="#login-box" class="back-to-login-link">
                                        Back to login
                                        <i class="ace-icon fa fa-arrow-right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div id="signup-box" class="signup-box widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header green lighter bigger">
                                        <i class="ace-icon fa fa-users blue"></i>
                                        New User Registration
                                    </h4>
                                    <div class="space-6"></div>
                                    <p> Enter your details to begin: </p>
                                    
                                    <form action="/ace/registration.html" method="post" id="registration">
                                        <fieldset>
                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="email" class="form-control" id="email"
                                                           name="email"
                                                           placeholder="Email"/>
                                                    <i class="ace-icon fa fa-envelope"></i>
                                                </span>
                                            </label>

                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="text" class="form-control" id="user_Account"
                                                           name="userAccount"
                                                           placeholder="Account"/>
                                                    <i class="ace-icon fa fa-user"></i>
                                                </span>
                                            </label>

                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="password" class="form-control" id="pass_word"
                                                           name="password"
                                                           placeholder="Password"/>
                                                    <i class="ace-icon fa fa-lock"></i>
                                                </span>
                                            </label>

                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right">
                                                    <input type="password" class="form-control"
                                                           id="confirm-password" name="confirm-password"
                                                           placeholder="Repeat password"/>
                                                    <i class="ace-icon fa fa-retweet"></i>
                                                </span>
                                            </label>

                                            <label class="block">
                                                <input type="checkbox" class="ace" id="accept-checkbox"/>
                                                <span class="lbl">
I accept the
<a href="#">User Agreement</a>
</span>
                                            </label>

                                            <div class="space-24"></div>

                                            <div class="clearfix">
                                                <button type="reset" class="width-30 pull-left btn btn-sm">
                                                    <i class="ace-icon fa fa-refresh"></i>
                                                    <span class="bigger-110">Reset</span>
                                                </button>

                                                <button type="button" id="register-btn"
                                                        class="width-65 pull-right btn btn-sm btn-success">
                                                    <span class="bigger-110">Register</span>
                                                    <i class="ace-icon fa fa-arrow-right icon-on-right"></i>
                                                </button>
                                            </div>
                                        </fieldset>
                                    </form>
                                </div>

                                <div class="toolbar center">
                                    <a href="#" data-target="#login-box" class="back-to-login-link">
                                        <i class="ace-icon fa fa-arrow-left"></i>
                                        Back to login
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                    </div>

                    <div class="navbar-fixed-top align-right" id="loginTheme">
                        <br/>
                        &nbsp;
                        <a id="btn-login-dark" href="#">Dark</a>
                        &nbsp;
                        <span class="blue">/</span>
                        &nbsp;
                        <a id="btn-login-blur" href="#">Blur</a>
                        &nbsp;
                        <span class="blue">/</span>
                        &nbsp;
                        <a id="btn-login-light"
1233
href="#">Light</a>
                        &nbsp; &nbsp; &nbsp;
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="/assets/js/jquery-2.1.4.min.js"></script>


<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script th:src='@{/assets/js/jquery.mobile.custom.min.js}' >" + "<" + "/script>");
</script>


<script type="text/javascript">
    jQuery(function ($) {
        $(document).on('click', '.toolbar a[data-target]', function (e) {
            e.preventDefault();
            const target = $(this).data('target');
            $('.widget-box.visible').removeClass('visible');//hide others
            $(target).addClass('visible');//show target
        });
    });

    //you don't need this, just used for changing background
    jQuery(function ($) {
        $('#btn-login-dark').on('click', function (e) {
            $('body').attr('class', 'login-layout');
            $('#id-text2').attr('class', 'white');
            $('#id-company-text').attr('class', 'blue');
            e.preventDefault();
        });
        $('#btn-login-light').on('click', function (e) {
            $('body').attr('class', 'login-layout light-login');
            $('#id-text2').attr('class', 'grey');
            $('#id-company-text').attr('class', 'blue');
            e.preventDefault();
        });
        $('#btn-login-blur').on('click', function (e) {
            $('body').attr('class', 'login-layout blur-login');
            $('#id-text2').attr('class', 'white');
            $('#id-company-text').attr('class', 'light-blue');
            e.preventDefault();
        });
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        //页面载入完成时自动加载JavaScript
        //登入
        // $("#login-btn").bind('click', function () {
        //     login();
        // });
        //
        // $("#id,#pw").keydown(function () {//给输入框绑定按键事件
        //     if (event.keyCode == "13") {//判断如果按下的是回车键则执行下面的代码
        //         login();
        //     }
        // });


        $("#deviceType").val(getDevice());
        setLoginTheme();

        //检查注册是否为空并提交
        $("#register-btn").bind("click", function () {
            const email = $("#email").val();
            const userAccount = $("#user_Account").val();
            const password = $("#pass_word").val();
            const confirm_pw = $("#confirm-password").val();

            if (email == null || email === "") {
                alert("请输入Email");
                return;
            }
            //@不存在
            if (email.indexOf("@") === -1) {
                alert("Email格式不正确");
                return;
            }
            if (userAccount == null || userAccount === "") {
                alert("请输入User Account");
                return;
            }
            if (password == null || password === "") {
                alert("请输入password");
                return;
            }
            if (confirm_pw == null || confirm_pw === "") {
                alert("请重输入confirm_pw");
                return;
            }
            if ($.trim(password) !== $.trim(confirm_pw)) {
                alert("密码不匹配");
                return;
            }
            if (!$("#accept-checkbox").prop('checked')) {
                alert("Please read the agreement");
                return;
            }
            //map id to submit
            $("#registration").submit();
        })
    });

    function getDevice() {
        if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
            //alert(navigator.userAgent);
            //苹果端
            return 'ios'
        } else if (/(Android)/i.test(navigator.userAgent)) {
            //alert(navigator.userAgent);
            //安卓端
            return 'android'
        } else {
            //pc端
            return 'pc'
        }
    }

    function setLoginTheme() {
        const device = getDevice();
        if (device !== "pc") {
            $("#loginTheme").remove();
        }
    }
</script>
</body>
</html>

0

-- Closing connection 0

** Timing Details **
-- Name Lookup: 0.00s
-- TCP Connect: 0.12s
-- First Byte: 0.32s
-- Total Download: 1.28s
-- Size: 21043 bytes
-- Speed: 16414 bytes/sec
-- Using: HTTP/1.1
** RESULT CODE: 200**

**Comment by click33** [comment]
可能1、你的 iphone 自动访问了一些地址
可能2、你的项目没有处理全局异常
可能3、你的项目除了全局异常，但是没有处理全局404

根据log信息，可以看出报错的path是 /error ，你需要自己找出为啥项目访问了 /error ，我们没法帮你远程调试，这种问题得你自己慢慢找

**Comment by 98549844** [comment]
可能3、你的项目处理了全局异常，但是没有处理全局404

因为controller的url要拼video的id才知道播哪一条video, 但是经iphone去访问dplayer怎样粘都粘不上url+videoId, 粘不上, 自然找不到url的controller, 那就肯定报404 page not found, 但是我用电脑的话, url+videoId是没问题, 所以只是iphone播不到..............

**Comment by 98549844** [comment]
![image](https://user-images.githubusercontent.com/26402108/203945335-3c617e08-ce62-445a-98bc-aece94ee147c.png)

![image](https://user-images.githubusercontent.com/26402108/203945786-7d96399b-e5fc-4dde-99b2-76b59063b4e2.png)
