### ISSUE TITLE
文档中通过代码配置(模式2)， 示例的配置方法有误

### ISSUE THREAD

**Issue by kylewka** [dromara/Sa-Token#336]
文档中通过代码配置(模式2)， 示例的配置方法有误。

### 使用版本:

https://sa-token.dev33.cn/doc.html#/use/config?id=方式2、通过代码配置

![image](https://user-images.githubusercontent.com/66908361/201386092-769bfffe-550b-4d76-9e01-66f69ce41ca6.png)

请问，是我的理解不对，还是文档出了问题？

**Comment by click33** [comment]
收到
