### ISSUE TITLE
Token生成重复字符串导致登录信息混乱

### ISSUE THREAD

**Issue by Mrlantian** [dromara/Sa-Token#338]
### 使用版本:
1.32.0

### 报错信息：
重复生成 “oV_cdI21l5DyeUu3e_zlmAp0ln5d8vuvbW__”这个字符串作为token，导致用户登录信息混乱

与下面的issue/333情况相同
[issues/333](https://github.com/dromara/Sa-Token/issues/333)

### 复现步骤：
每次登录生成token时可复现
![db20cf05bafd546d19dacc88989d56f](https://user-images.githubusercontent.com/87525328/202074900-243518c6-b850-4fb7-8e6d-39c33830805c.png)

### 暂时解决方法：
 使用uuid作为token而不是sa-token生成的随机字符串

**Comment by Mrlantian** [comment]
好像使用SaFoxUtil.getRandomString()生成生成的随机字符串均涉及此问题

**Comment by click33** [comment]
怎么复现？

**Comment by click33** [comment]
已发布新版 v1.33.0 修复此问题，更新一下吧
