### ISSUE TITLE
复写Sa-Token-OAuth2 与登录会话实现数据互通后，登录侦听功能会调用2次。

### ISSUE THREAD

**Issue by JhonCX** [dromara/Sa-Token#339]
### 使用版本:
1.32.0

### 涉及的功能模块：
[Sa-Token-OAuth2 与登录会话实现数据互通](https://sa-token.cc/doc.html#/oauth2/oauth2-interworking?id=sa-token-oauth2-%e4%b8%8e%e7%99%bb%e5%bd%95%e4%bc%9a%e8%af%9d%e5%ae%9e%e7%8e%b0%e6%95%b0%e6%8d%ae%e4%ba%92%e9%80%9a)

### 测试步骤：
+ 我经过以下步骤测试：
复写Sa-Token-OAuth2 与登录会话实现数据互通后，登录侦听功能会调用2次。
默认登录功能StpUtil.login(xx,xx)与复写randomAccessToken(xx,xx,xx)使用StpUtil.createLoginSession(loginId, new SaLoginModel().setDevice(clientId))都会调用StpLogic.createLoginSession(Object id, SaLoginModel loginModel)方法，导致方法内	SaTokenEventCenter.doLogin(loginType, id, tokenValue, loginModel) 事件重复发布

+ 得出以下结果：
当前Sa-Token-OAuth2 与登录会话实现数据互通使用StpUtil.createLoginSession(loginId, new SaLoginModel().setDevice(clientId))在登录逻辑中会调用2次登录侦听方法，希望能够将其分开。

**Comment by click33** [comment]
可以用 StpUtil.getTokenValueByLoginId(loginId) 判断一下，如果能获取到值说明这个 loginId 已经处于登录状态，直接返回这个 token 即可
在 StpUtil.getTokenValueByLoginId(loginId) 获取不到值时再使用 StpLogic.createLoginSession(Object id, SaLoginModel loginModel) 新建会话
