### ISSUE TITLE
StpLogic 是不是存在逻辑问题

### ISSUE THREAD

**Issue by killfen** [dromara/Sa-Token#340]
### 测试步骤：
+ 我经过以下步骤测试：
 tokenValue = request.getHeader(keyTokenName); //这里应该返回null ，而不是字符串"null"
+ 得出以下结果：
返回 "null" 字符串
导致，
if(tokenValue == null && config.getIsReadCookie()) 条件不成立，不能正确获取，导致直接 返回 tokenValue 为 "null"，

请问，是我的理解不对，还是了问题？

**Comment by click33** [comment]
是不是你前端提交了一个字符串null?

**Comment by killfen** [comment]
没有提交null字符串

**Comment by click33** [comment]
没有复现
