### ISSUE TITLE
单点注销问题

### ISSUE THREAD

**Issue by 643562798** [dromara/Sa-Token#342]
### 对以下问题有疑问:
模式二，不同域名，在 is-share=false 时，无法单点注销

**Comment by click33** [comment]
请按照 issue 模板反馈

### 使用版本:


### 涉及的功能模块：


### 测试步骤：
+ 我经过以下步骤测试：

+ 得出以下结果：

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：

+ 我的理解是：

请问，是我的理解不对，还是文档出了问题？

**Comment by 643562798** [comment]
### 使用版本:
1.33.0

### 涉及的功能模块：
单点登录模块

### 测试步骤：
+ 我经过以下步骤测试：
模式二，配置 is-share=false，单点登录server和客户端使用不同的域名

+ 得出以下结果：
单点登录server和客户端均生成了token，客户端的退出，只是销毁了客户端的token，单点登录server并不会退出

+ 我的理解是：
本来就是这样设计的吗？我希望单点登录server同时失效。

**Comment by click33** [comment]
你是调用的哪个接口执行的注销功能？亮一下代码

**Comment by 643562798** [comment]
客户端的/sso/logout接口

**Comment by click33** [comment]
是否有重写这个接口？

**Comment by 643562798** [comment]
跟重写没关系，我在交流群3，不想在这里贴代码，咱单独交流下

**Comment by 643562798** [comment]
一个账号在两个浏览器上都登陆，A浏览器上退出不影响B浏览器，这样的话需要is-share=false
在不同域的情况下，客户端通过ticket登录调用的是这个
stpLogic.login(loginId);
客户端单独生成了token，在客户端点击退出登录调用客户端的/sso/logout，只能把客户端的token注销掉
上面说的都是SSO模式二

**Comment by 643562798** [comment]
同一个账号在多个浏览器同时登录互不影响

**Comment by click33** [comment]
StpUitl.logout(10001) 是注销 10001 的所有登录

 StpUitl.logout() 是注销当前客户端登录

你看看你执行的是哪个

**Comment by 643562798** [comment]
建议在这种情况下，客户端通过ticket生成的token作为server对应的token的子token，或者存在映射关系，这样在退出的时候相关的token都删除。
