### ISSUE TITLE
数据级别权限控制

### ISSUE THREAD

**Issue by qiuyueovo** [dromara/Sa-Token#345]
### 对以下问题有疑问:

如何进行权限控制：
例：我有A用户，A能对于数据1能编辑能查看，对于数据2只能查看，是数据级别的权限控制，感觉这块位置没有太大思路

**Comment by click33** [comment]
手动 if 判断，
Sa-Token 不提供这种功能

**Comment by leanderli** [comment]
可以看看Spring Security Acl
