### ISSUE TITLE
多前端地址的跨域问题如何解决

### ISSUE THREAD

**Issue by runtongye** [dromara/Sa-Token#349]
### 对以下问题有疑问:
[跨域问题](https://sa-token.dev33.cn/doc.html#/fun/cors-filter?id=%e8%a7%a3%e5%86%b3%e8%b7%a8%e5%9f%9f%e9%97%ae%e9%a2%98)

根据文档中的文章链接地址微调之后可以正常运行，但是Access-Control-Allow-Origin只能支持单一地址。

对于被排除掉的路径可以通过WebMvcConfigurer设置一个List，但是SaHolder.getResponse().setHeader()只接收String,String参数，那么对于有多个前端地址访问导致的跨域问题该怎么处理呢？

**Comment by click33** [comment]
你可以调用 SpringMVCUtil.getResponse() 获取 response 对象手动设置，不用仅局限在 SaHolder.getResponse().setHeader() 上
