### ISSUE TITLE
建议SaSession的所有字段开放getter,setter，自定义SaTokenDao的时候使用fastjson不能反序列化

### ISSUE THREAD

**Issue by mtzqc** [dromara/sa-token#35]
使用fastjson无法反序列化id和createTime，应为没有setter，需要手动处理;
建议改成更智能一点，SaSession改为接口的方式提供，具体实现类通过配置的方式实现

**Comment by click33** [comment]
已添加

**Comment by shuaohan** [comment]
升级 jasfjson的版本可以解决 目前我使用2.0.7可以

**Comment by shuaohan** [comment]
或者重写TokenSign.class 添加所有的getset方法
