### ISSUE TITLE
非Web上下文无法获取Request

### ISSUE THREAD

**Issue by mark0614** [dromara/Sa-Token#350]
### 对以下问题有疑问:

我在mybatis-plus中的insertFill中使用了StpUtil中的API，报“非Web上下文无法获取Request”，我查看了官方中的常见问题说明：先获取你想要的值，再把这个值当做一个参数传递到这些方法中，而不是直接从方法内调用 Sa-Token 的API；

能否详细说明这个问题的解决思路？  另外，如果使用了@Async，该问题如何解决？谢谢！

**Comment by click33** [comment]
目前没有解决方案，应该避免在这些方法中调用 Sa-Token 的 API
