### ISSUE TITLE
SaInterceptor 拦截以及Undertow下使用的问题 

### ISSUE THREAD

**Issue by tonycody** [dromara/Sa-Token#355]
1.30.0，版本验证。
1.SaInterceptor 拦截存在的问题，Spring Boot 在后期的版本中，ResourceHttpRequestHandler 会在拦截器中触发，导致资源相关的Handler 也会走 SaInterceptor，不影响功能，但无意义。
2.Undertow 在Sa拦截之后，拦截器会重定向，但拦截器返回true，会导致 Undertow 抛：UT015023: This Context has been already committed.

**Comment by click33** [comment]
1、这本就是基于 Spring 拦截器的封装，底层逻辑肯定得跟着 Spring 的走
2、暂未适配 Undertow
