### ISSUE TITLE
为什么不将SaSession交由HttpSession托管，从而避免Session误用？

### ISSUE THREAD

**Issue by einsitang** [dromara/Sa-Token#356]
https://sa-token.cc/doc.html#/use/session?id=session%e7%8e%af%e5%a2%83%e9%9a%94%e7%a6%bb%e8%af%b4%e6%98%8e
文档中的内容：

> 要点：
> 
> - SaSession 与 HttpSession 没有任何关系，在HttpSession上写入的值，在SaSession中无法取出
> - HttpSession并未被框架接管，在使用Sa-Token时，请在任何情况下均使用SaSession，不要使用HttpSession

sa-token在api上和使用理解上都易用于shiro，但是shiro在session的处理上是直接和httpsession共用，这样无论是从SecurityUtils上获取还是从HttpServletRequest上获取的session，都是同一个，容易理解也避免误用。

另外，我查看了一下[sa-token-plugin](https://github.com/dromara/Sa-Token/tree/dev/sa-token-plugin)/[sa-token-dao-redis-jackson](https://github.com/dromara/Sa-Token/tree/dev/sa-token-plugin/sa-token-dao-redis-jackson)的代码，我在想有没有一个办法可以将SaSession交由HttpSession进行托管处理，然后HttpSession自行考虑是否需要进行Redis存储还是单纯的内存驻留，成就一个 `sa-token-dao-httpsession`这样的plugin，这样做是否会优雅一点？

**Comment by click33** [comment]
HttpSession 的方法太少，基本上除了存取值啥也干不了，而且强依赖 Servlet 规范，没法适配更多的需求，所以需要自造 SaSession 对象

**Comment by einsitang** [comment]
所以 SaSession是HttpSession的增强，并且是全包含的方式？
