### ISSUE TITLE
前后端分离，如何根据id检查是否登录？

### ISSUE THREAD

**Issue by ddxl123** [dromara/Sa-Token#363]
`StpUtil.isLogin()` 只能查询当前会话是否登录，但是查询不了指定id是否登录。

**Comment by lionelkali** [comment]
这个方法判断有没有登录，只不过返回值是个boolean值罢了相似的API还有很多，如下：
`// 获取当前会话账号id, 如果未登录，则抛出异常：`NotLoginException`
StpUtil.getLoginId();

// 类似查询API还有：
StpUtil.getLoginIdAsString();    // 获取当前会话账号id, 并转化为`String`类型
StpUtil.getLoginIdAsInt();       // 获取当前会话账号id, 并转化为`int`类型
StpUtil.getLoginIdAsLong();      // 获取当前会话账号id, 并转化为`long`类型

// ---------- 指定未登录情形下返回的默认值 ----------

// 获取当前会话账号id, 如果未登录，则返回null 
StpUtil.getLoginIdDefaultNull();

// 获取当前会话账号id, 如果未登录，则返回默认值 （`defaultValue`可以为任意类型）
StpUtil.getLoginId(T defaultValue);`

**Comment by click33** [comment]
``` java
if(StpUtil.getTokenValueByLoginId(10001) != null) {
			
		}
```
