### ISSUE TITLE
getTokenValueListByLoginId 返回的数组是根据什么排序的？

### ISSUE THREAD

**Issue by ddxl123** [dromara/Sa-Token#364]
### 对以下问题有疑问:
```
is-concurrent: true
is-share: false
```
`StpUtil.getTokenValueListByLoginId( userId )` 返回的数组，是按照添加先后顺序排序的，还是按照首字母排序的？
我想获取到最近的一个登录，直接 `.last` 就可以还是？

**Comment by click33** [comment]
登录时间顺序，索引最后一个就是最近登录的
