### ISSUE TITLE
sa-token-reactor-spring-boot-starter:1.34.0 少添加了org.springframework.boot.autoconfigure.AutoConfiguration.imports文件

### ISSUE THREAD

**Issue by wlf1995** [dromara/Sa-Token#368]
### 使用版本:sa-token-reactor-spring-boot-starter:1.34.0

META-INF 中没有添加 org.springframework.boot.autoconfigure.AutoConfiguration.imports文件
![image](https://user-images.githubusercontent.com/37922881/211767054-ce457c1a-3023-44d5-884f-e030dee32a4a.png)

**Comment by click33** [comment]
![Uploading image.png…]()

**Comment by click33** [comment]
将 sa-token-spring-boot-starter 修改为 sa-token-spring-boot3-starter

**Comment by wlf1995** [comment]
好的，谢谢
