### ISSUE TITLE
特殊情况下SaIgnore无法正常执行

### ISSUE THREAD

**Issue by yixiaco** [dromara/Sa-Token#370]
### 使用版本:
1.34.0
### 复现步骤：
```java
@SaIgnore
@RestController
@RequestMapping("/config")
public class TestController {

    /**
     * 如果该路径是一个/,则SaIgnore会失效
     *
     */
    @GetMapping("/")
    public R<Map<String, String>> getInfoByGroup(String group) {
        ...
    }
}
```

**Comment by click33** [comment]
收到

**Comment by ly-chn** [comment]
springboot版本是3的话,"/config"和"/config/"是两个不同的路径, 请确认一下版本

**Comment by yixiaco** [comment]
> springboot版本是3的话,"/config"和"/config/"是两个不同的路径, 请确认一下版本

springboot版本是2.7.7

**Comment by ly-chn** [comment]
如果Controller类上有@RequestMapping注解的话, 方法上的斜杠会严格匹配, 如上, 你应当访问"/config/"才对, 上述错误我猜是404页面未授权, 故而报错, 此spring匹配机制问题

(2.7前后貌似有差异, 未核对, 3.0同理, 具体有兴趣的话可以继续探讨)

**Comment by ly-chn** [comment]
如无疑问, 将关闭

**Comment by yixiaco** [comment]
> 如无疑问, 将关闭

好的，后续有问题我会重新反馈
