### ISSUE TITLE
SpringBoot3下SaInterceptor无法继承

### ISSUE THREAD

**Issue by Enaium** [dromara/Sa-Token#371]
### 使用版本:

1.34.0
### 涉及的功能模块：

SaInterceptor
### 测试步骤：
```java
@Component
public class SaTokenInterceptor extends SaInterceptor {
    public SaTokenInterceptor() {
        super(auth -> SaRouter.match("/**")
                .notMatchMethod("OPTIONS")
                .check(check -> StpUtil.checkLogin()));
    }
}
```

```
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.3.jar:6.0.3]
	... 22 common frames omitted
```

**Comment by chenghm123** [comment]
> ### 使用版本:
> 1.34.0
> 
> ### 涉及的功能模块：
> SaInterceptor
> 
> ### 测试步骤：
> ```java
> @Component
> public class SaTokenInterceptor extends SaInterceptor {
>     public SaTokenInterceptor() {
>         super(auth -> SaRouter.match("/**")
>                 .notMatchMethod("OPTIONS")
>                 .check(check -> StpUtil.checkLogin()));
>     }
> }
> ```
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
> 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
> 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
> 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
> 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.3.jar:6.0.3]
> 	... 22 common frames omitted
> ```

这个是HttpServletRequest包没有引入

**Comment by Enaium** [comment]
> > ### 使用版本:
> > 1.34.0
> > 
> > ### 涉及的功能模块：
> > SaInterceptor
> > 
> > ### 测试步骤：
> > ```java
> > @Component
> > public class SaTokenInterceptor extends SaInterceptor {
> >     public SaTokenInterceptor() {
> >         super(auth -> SaRouter.match("/**")
> >                 .notMatchMethod("OPTIONS")
> >                 .check(check -> StpUtil.checkLogin()));
> >     }
> > }
> > ```
> > 
> > ```
> > Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
> > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
> > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
> > 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
> > 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.3.jar:6.0.3]
> > 	... 22 common frames omitted
> > ```
> 
> 这个是HttpServletRequest包没有引入

springboot3是Jakarta

**Comment by chenghm123** [comment]
> > > ### 使用版本:
> > > 1.34.0
> > > ### 涉及的功能模块：
> > > SaInterceptor
> > > ### 测试步骤：
> > > ```java
> > > @Component
> > > public class SaTokenInterceptor extends SaInterceptor {
> > >     public SaTokenInterceptor() {
> > >         super(auth -> SaRouter.match("/**")
> > >                 .notMatchMethod("OPTIONS")
> > >                 .check(check -> StpUtil.checkLogin()));
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
> > > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
> > > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
> > > 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
> > > 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.3.jar:6.0.3]
> > > 	... 22 common frames omitted
> > > ```
> > 
> > 
> > 这个是HttpServletRequest包没有引入
> 
> springboot3是Jakarta

请使用依赖

**Comment by chenghm123** [comment]
> > > ### 使用版本:
> > > 1.34.0
> > > ### 涉及的功能模块：
> > > SaInterceptor
> > > ### 测试步骤：
> > > ```java
> > > @Component
> > > public class SaTokenInterceptor extends SaInterceptor {
> > >     public SaTokenInterceptor() {
> > >         super(auth -> SaRouter.match("/**")
> > >                 .notMatchMethod("OPTIONS")
> > >                 .check(check -> StpUtil.checkLogin()));
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
> > > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
> > > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
> > > 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
> > > 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.3.jar:6.0.3]
> > > 	... 22 common frames omitted
> > > ```
> > 
> > 
> > 这个是HttpServletRequest包没有引入
> 
> springboot3是Jakarta

请使用依赖：
<dependency>
    <groupId>cn.dev33</groupId>
    <artifactId>sa-token-spring-boot3-starter</artifactId>
    <version>1.34.0</version>
</dependency>

**Comment by chenghm123** [comment]
```
<dependency>
    <groupId>cn.dev33</groupId>
    <artifactId>sa-token-spring-boot3-starter</artifactId>
    <version>1.34.0</version>
</dependency>

```
