### ISSUE TITLE
如何根据tokenValue获取TokenInfo

### ISSUE THREAD

**Issue by miaoyinjun** [dromara/Sa-Token#372]
### 使用版本:
1.34.0

### 涉及的功能模块：
StpUtil.searchTokenValue(filter, start, end, false);

### 测试步骤：
+ 我经过以下步骤测试：
StpUtil类没有找到可以根据tokenValue获取TokenInfo的方法

+ 得出以下结果：

+ 无

+ 我的理解是：

我需要查询在线用户的信息，如用户名、登录设备、最后一次操作时间 等。

**Comment by chenghm123** [comment]
> 

目前确实没有这个API，可以通过现有API自己封装这个对象

**Comment by chenghm123** [comment]
> ### 使用版本:
> 1.34.0
> 
> ### 涉及的功能模块：
> StpUtil.searchTokenValue(filter, start, end, false);
> 
> ### 测试步骤：
> * 我经过以下步骤测试：
>   StpUtil类没有找到可以根据tokenValue获取TokenInfo的方法
> * 得出以下结果：
> * 无
> * 我的理解是：
> 
> 我需要查询在线用户的信息，如用户名、登录设备、最后一次操作时间 等。

目前确实没有这个API，可以通过现有API自己封装这个对象

**Comment by miaoyinjun** [comment]
作者可以考虑下封装下这个方法
