### ISSUE TITLE
token过期时间问题

### ISSUE THREAD

**Issue by miaoyinjun** [dromara/Sa-Token#374]
### 使用版本:
1.34.0

### 涉及的功能模块：
配置timeout和activity-timeout

### 测试步骤：
+ 我经过以下步骤测试：
需求：用户登录Token保存2个小时，30分钟无操作则Token退出，Token有效期间内续期

+ 得出以下结果：
配置方案1：
    timeout: 2 小时，activity-timeout: 30分钟
    问题：不超过30分钟操作一次，2个小时后Token过期了，用户会疑惑被退出
配置方案2：
    timeout: 永不过期，activity-timeout: 30分钟
    问题：可以解决，但缓存中的Token永远不过期

**Comment by click33** [comment]
可以采用 StpUtil.renewTimeout(x) 续期

**Comment by click33** [comment]
参考：https://sa-token.cc/doc.html#/fun/token-timeout

**Comment by miaoyinjun** [comment]
好的，谢谢

**Comment by lizhuquan0769** [comment]
我一开始也以为auto-renew是续timeout的，后面看源码，才知道那个配置是续activity-timeout的；
  需求是用户如果连续24小时不操作token就作废，没有限定token能用多久，请问建议什么时候续期好，如果每次请求都续期，会不会IO消耗比较大。

> 参考：https://sa-token.cc/doc.html#/fun/token-timeout

**Comment by lizhuquan0769** [comment]
> 可以采用 StpUtil.renewTimeout(x) 续期

我一开始也以为auto-renew是续timeout的，后面看源码，才知道那个配置是续activity-timeout的；
需求是用户如果连续24小时不操作token就作废，没有限定token能用多久，请问建议什么时候续期好，如果每次请求都续期，会不会IO消耗比较大。
