### ISSUE TITLE
【建议】增加：自定义redis键的前缀

### ISSUE THREAD

**Issue by miaoyinjun** [dromara/Sa-Token#375]
### 建议增加的新功能:
    自定义redis键的前缀

### 应用场景阐述：
    不同的应用或模块连接同一个redis，使用应用或模块名归类到同一个key中

**Comment by click33** [comment]
为啥不用 database 来区分呢

**Comment by ly-chn** [comment]
不同应用连接同一个库是不可取的行为, 但是自定义键前缀功能是可以考虑的, 感谢建议

**Comment by JoieLu** [comment]
> 为啥不用数据库来区分呢

只有一台大型redis服务器，然后很多场景是10几个项目连一个database，然后每个database都有10几个项目

**Comment by eddiclin** [comment]
这是个痛点。
1. 小项目 或者 测试环境 等资源不足的情况，多项目共用 Redis 实例 或者 不想维护多一套 Redis 实例，database 数量不足。
2. database 从 0, 1, 2 编号看不出归属项目，容易弄混。
