### ISSUE TITLE
tokenSessionCheckLogin 为 true 配置不生效

### ISSUE THREAD

**Issue by mj19910923** [dromara/Sa-Token#380]
环境：
sa-token:1.34.0
SpringBoot:2.3.12.RELEASE

描述：

1. 配置 sa-token.token-session-checkLogin=true
2. 在自定义参数解析器（实现HandlerMethodArgumentResolver接口）中调用如下方法：

`
Object obj = StpUtil.getTokenSession().get("userInfo");
`

报 NullPointerException 异常，如果执行登录检查的话，应该提示未登录才对

**Comment by Gabriel-1023** [comment]
个人见解：
cn.dev33.satoken.stp.StpLogic.getTokenSession() 中的代码（如下）显示，getTokenSession()会先判断tokenValue是否为空，是空直接返回 null，不是空才会根据是否配置了token-session-checkLogin为True来检查是否登录。按照这个逻辑，只有tokenValue不为空并且无效才会抛出异常，算作未登录。tokenValue为空时的未登录可以用StpUtil.getTokenSession() == null 这个条件来判断。
``` java
public SaSession getTokenSession(boolean isCreate) {
        String tokenValue = this.getTokenValue();
        if (SaFoxUtil.isEmpty(tokenValue)) {
            return null;
        } else {
            if (this.getConfig().getTokenSessionCheckLogin()) {
                this.checkLogin();
            }

            ...
```

**Comment by click33** [comment]
“报 NullPointerException 异常”

能否把异常堆栈信息贴一下

**Comment by click33** [comment]
我本地尝试了一下，确实复现了这问题，此处确实抛出未登录要比返回 null 更合理一些，下个版本会考虑优化一下这里
