### ISSUE TITLE
Oauth2 spring 3.0还不支持

### ISSUE THREAD

**Issue by funs690** [dromara/Sa-Token#382]
请在以下地址复制 issue 模板进行提交：
https://sa-token.cc/doc.html#/fun/issue-template

参考示例文档基于springboot 3.0构建授权服务，请求authorize 接口提示，获取到上下文

**Comment by click33** [comment]
![image](https://user-images.githubusercontent.com/36243476/219556286-b9ed14ff-00e6-4dd9-912a-aabdf6b43d91.png)
