### ISSUE TITLE
请教一下ticket的问题

### ISSUE THREAD

**Issue by 1369521908** [dromara/Sa-Token#384]
### 对以下问题有疑问:
在单点登录 模式二中(https://sa-token.cc/doc.html#/sso/sso-type2)
1.已经操作完client1的登录
2.打开client2窗口 按F12打开控制台 清空cookies
3.打开client1窗口 按F12打开控制台 清空cookies
4.打开client2窗口 点击登录按钮进行登录
5.client2登录成功

在4时候我在这里断点看了 为什么request.getCookies()还能取回来数据 然后生成新的ticket  菜鸡求解惑
sa-token-demo-sso-server 服务 cn.dev33.satoken.servlet.model.SaRequestForServlet#getCookieValue

还有请问client2是如何做到关联client1登录的信息的

< 备注：请尽量详细描述问题所在 >

**Comment by click33** [comment]
“请问client2是如何做到关联client1登录的信息”
client2 没有去关联 client1 的信息，client2 和 client1 都是关联的 sso-server 的信息
