### ISSUE TITLE
希望新增oidc协议支持

### ISSUE THREAD

**Issue by redDevis** [dromara/Sa-Token#385]
### 建议增加的新功能:
希望新增oidc协议，因为这个目前是非常流行得
### 应用场景阐述：
oauth2.0过于简单，对接好多第三方，都是支持oidc协议得，不如harbor等

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
目前有针对 oidc 的简单实现，未来会逐步完善这块

**Comment by redDevis** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Alleninggx** [comment]
> 目前有针对 oidc 的简单实现，未来会逐步完善这块

你好，请问有实现例子吗？

**Comment by Alleninggx** [comment]
邮件已收到！
