### ISSUE TITLE
关于tokenValue持久化redis的问题

### ISSUE THREAD

**Issue by ahgaoyong** [dromara/Sa-Token#386]
### 使用版本:
1.34.0

### 涉及的功能模块：
tokenValue持久化redis
辅助模块: sa-token-dao-redis-jackson 1.34.0

### 测试步骤：
+ 我经过以下步骤测试：

我的代码如下:
`StpUtil.getTokenSession().set(LOGIN_USER_KEY, loginUser);`

**以下是逐步看源码的步骤:**

首先跟进set方法:

```
public SaSession set(String key, Object value) {
        this.dataMap.put(key, value);
        this.update();
        return this;
    }
```
再次跟进:  `this.update();`
得到: `SaManager.getSaTokenDao().updateSession(this);`
再次跟进: 
```
public void updateObject(String key, Object object) {
        long expire = this.getObjectTimeout(key);
        if (expire != -2L) {
            this.setObject(key, object, expire);
        }
    }
```

**此处好像是根据redis已有数据的过期时间来更新数据, 如果redis里面没有这个数据, 则不会设置数据到redis, 那么我想问下:redis是在什么时候set数据进去的呢?**

**Comment by click33** [comment]
User-Session 在登录时创建，Token-Session 在首次获取时创建
