### ISSUE TITLE
关于isUrl的问题

### ISSUE THREAD

**Issue by zhh0000zhh** [dromara/Sa-Token#387]
相对路径跳转的时候，http/https/ftp/file等前缀不存在
需要添加对相对路径的跳转支持
SaFoxUtil.isUrl判断时候应当将("/login_suc")等相对路径识别为合法路径
可参考RFC规范
https://www.rfc-editor.org/rfc/rfc3986#section-4.2

**Comment by click33** [comment]
这个方法只是为了在 sso、oauth2 跳转时检查一下 url 合法性的，其要做到的目的和此 RFC 并不一致，因此不需要按照这个 RFC 规范来实现
