### ISSUE TITLE
sa-token如何实现spring security中@PreAuthorize的spring el功能？

### ISSUE THREAD

**Issue by pcdd-group** [dromara/Sa-Token#390]
### 对以下问题有疑问:

sa-token 是否提供了相关注解或方法实现如下功能？

![image](https://user-images.githubusercontent.com/51998152/223382843-1432f6fc-e13f-44a1-ab9d-1ccb02df35cb.png)

**Comment by ly-chn** [comment]
这个功能实现不难, 但是即便是实现了, IDEA等开发工具也不会提供el表达式代码提示的支持. 所以有些难办

**Comment by ly-chn** [comment]
补充, IDEA对SpEL支持的配置方式https://www.jetbrains.com/help/idea/using-language-injections.html#configure-injection-rules

**Comment by click33** [comment]
有这方面的规划，但是短时间内应该不会增加这个功能
