### ISSUE TITLE
请问，能与casbin权限框架集成么，就用satoken的认证能力，鉴权能力调用casbin api

### ISSUE THREAD

**Issue by yl-yue** [dromara/Sa-Token#392]
请问，能与casbin权限框架集成么，就用satoken的认证能力，鉴权能力调用casbin api

**Comment by click33** [comment]
应该能，但是我没有试过。
理论上，只要你在登录时能够获取到用户的 userId，然后调用 Sa-Token 的 `StpUtil.login(id)` 来登录。
就能将 Sa-Token 和任意框架集成。

**Comment by yl-yue** [comment]
应该是可以的，先已入坑 satoken，只用satoken的认证能力，鉴权交给casbin。理论上可以。后面我试成功了，再在此记录
