### ISSUE TITLE
使用spring boot 2.6.4 + spring gateway 3.1.1，在调用StpUtil.getSession()的时候，报未成功初始化上下文

### ISSUE THREAD

**Issue by lishiyu** [dromara/Sa-Token#395]
@Slf4j
@Configuration
public class MyGlobalFilterFilter implements GlobalFilter{

    
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {

        ServerHttpRequest request = exchange.getRequest();
        ServerHttpRequest.Builder mutate = request.mutate();

        SaSession session = StpUtil.getSession();
        mutate.headers(h -> h.put("id", Collections.singletonList(session.get("id").toString())));
        mutate.headers(h -> h.put("UIP", Collections.singletonList(IpUtil.getRequestIpAddr(request))));

        mutate.headers(h -> h.remove(HttpHeaders.CONTENT_LENGTH));

        return chain.filter(exchange.mutate().request(mutate.build()).build());
    }

}

**Comment by click33** [comment]
参考：

![image](https://user-images.githubusercontent.com/36243476/226169216-a15137c4-3e31-4930-a33b-5be2ff622db8.png)
