### ISSUE TITLE
springboot3.x 出现SaHolder.getResponse() null 指针

### ISSUE THREAD

**Issue by zhouyun885** [dromara/Sa-Token#396]
如何解决？服务之前调用验证，多个获取response的方法都不行？如何解决？？？在线等
![image](https://user-images.githubusercontent.com/19903251/224535334-dada3e55-5185-42c2-8fe9-3035bf61ad7a.png)
![image](https://user-images.githubusercontent.com/19903251/224535429-c63667a9-5829-48e5-90c3-0cb09406b473.png)
![image](https://user-images.githubusercontent.com/19903251/224587795-2bd90d78-b7f9-4cbd-86e2-be0014de6301.png)

**Comment by click33** [comment]
检查是否引入了依赖

![image](https://user-images.githubusercontent.com/36243476/226169499-db2e6b30-5e55-43c2-b602-133408a6dbee.png)
