### ISSUE TITLE
有计划适配java17吗

### ISSUE THREAD

**Issue by yantx** [dromara/Sa-Token#400]
啥时候适配java17，springboot3.X

**Comment by ly-chn** [comment]
已适配, 详见文档https://sa-token.cc/doc.html#/more/update-log?id=_2023-1-11-v1340

使用方面, 在文档中搜索3.x就能更快找到相关改动

**Comment by ly-chn** [comment]
不是兄弟你这大早上的就开搞了吗(早上7点?)
