### ISSUE TITLE
springboot3 + redis 序列号失败

### ISSUE THREAD

**Issue by jianhao2010303** [dromara/Sa-Token#402]
### 使用版本:

1.34.0

### 涉及的功能模块：

sa-token-dao-redis-jackson

### 测试步骤：
+ 我经过以下步骤测试：

1. 使用springboot3 集成 spring-boot-starter-data-redis.
2. 集成redis 配置为：

spring:
   data:
      redis:

3. 保存时报错：

未能获取有效的上下文处理器

+ 得出以下结果：

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：

 StpUtil.login(id)
![f154e423-e9bd-4c92-a69c-9ee980b88814](https://user-images.githubusercontent.com/22093101/226116064-e9b11646-954d-4511-b5d5-24249b4d7cad.jpg)

+ 我的理解是：

请问，是我的理解不对，还是文档出了问题？

**Comment by click33** [comment]
检查一下 引入的是否为：sa-token-spring-boot3-starter

![image](https://user-images.githubusercontent.com/36243476/226116128-f07a1b0b-ea6b-4f85-9aa5-8dc10c3b77e1.png)

**Comment by jianhao2010303** [comment]
感谢！
