### ISSUE TITLE
前后端分离SSO疑问

### ISSUE THREAD

**Issue by strongyc** [dromara/Sa-Token#404]
请在以下地址复制 issue 模板进行提交：
https://sa-token.cc/doc.html#/fun/issue-template
按照目前的发展形势，前后端分离成为常态，SSO模式下是否还需要sso-server，sso-server中的/sso/auth中怎么能够可以使用自定义的前端比如VUE等，而不是通过 return new ModelAndView("xxx.html");

**Comment by click33** [comment]
参考：https://sa-token.cc/doc.html#/sso/sso-h5
