### ISSUE TITLE
一个java应用、部署集群模式下、使用redis存储session等关系、信息不一致问题

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#409]
### 对以下问题有疑问:
一个java应用、部署集群模式下、使用redis存储session等关系
多个集群服务中的SaSession中tokenSignList内容不一致的问题

< 备注：请尽量详细描述问题所在 >
一般生产环境下、我们同一个服务部署两个节点作为集群、公用一个redis作为缓存、然后在两个服务之前会放一个nginx做请求负债均衡
假设这两个服务为a、b
在a节点中、sa-token接收到产生新的token请求时候、参考Sasession addTokenSign方法、会更新本服务内存中SaSession的tokenSignList、同时update到redis中
然后b节点中、也接收到一个产生新的token请求时候、也会进行同样的操作
这样是否会产生b的信息覆盖掉a update到redis的内容、且两服务节点内存中的内容不一致

**Comment by click33** [comment]
addTokenSign 只在登录时会有变动，只要你的业务不会有两个客户端毫秒级同时登录成功同一账号，就不会出现这个问题

**Comment by baichangda** [comment]
我查看源代码，没有看到在构造SaSession时候、从redis中加载关系到本地内存中
我使用的是sa-token-dao-redis-jackson:1.34.0、其中SaSessionForJacksonCustomized作为SaStrategy.me.createSession的实现

**Comment by click33** [comment]
![image](https://user-images.githubusercontent.com/36243476/226802899-55403383-a1f0-4438-a180-6044762fa940.png)

![image](https://user-images.githubusercontent.com/36243476/226802964-02510350-52a4-4d8b-9b5e-42e0a906a3db.png)

**Comment by baichangda** [comment]
非常感谢
