### ISSUE TITLE
登陆校验和注解权限校验优先级问题

### ISSUE THREAD

**Issue by baichangda** [dromara/Sa-Token#410]
### 对以下问题有疑问:
在使用集成sa-token-spring-boot3-starter时候、一般情况下、会对某一些controller接口实现登陆校验和权限校验
登陆校验通过配置拦截器完成
权限检验通过注解完成
如下图配置了一个拦截器、在这种情况下
SaInterceptor内部逻辑首先会进行注解的校验、然后才会进行自定方法auth校验
这样会导致、先校验权限、然后在校验是否登陆
![image](https://user-images.githubusercontent.com/24662536/227082419-c998fceb-8a8f-4167-864e-3bfbc8cec762.png)

当然可以定义两个拦截器完成工作、如下图
![image](https://user-images.githubusercontent.com/24662536/227082124-d7d6368e-369f-4dcd-97d2-52d9108de8a6.png)

是否有更优雅的方式、或者是否修改SaInterceptor类中preHandle、将Auth 校验 放在注解校验之前

< 备注：请尽量详细描述问题所在 >

**Comment by AppleOfGray** [comment]
校验权限的时候必须先获取当前登录id, 这意味必须登录后才能校验权限

**Comment by AppleOfGray** [comment]
校验权限的时候必须先获取当前登录id, 这意味必须登录后才能校验权限

**Comment by baichangda** [comment]
我追踪源代码是会获取loginId、但是在获取loginId为null后、抛出异常、被getPermissionList捕获、返回空集合权限
在getPermissionList是否该考虑不捕获异常、以便在外面应用程序可以捕获到异常转换为正确的错误信息
![image](https://user-images.githubusercontent.com/24662536/227134870-f503c1e1-3629-4b88-a7bf-1ee0762efc38.png)

**Comment by AppleOfGray** [comment]
空集合代表没有任何权限, 依旧无法进入当前接口, 报错的就是无权限异常, 在全局异常拦截里面也能拦截到

**Comment by baichangda** [comment]
但是返回的信息及异常是有问题的、这种情况下应该告诉客户先登陆、而不是告知他没有xxx权限

**Comment by AppleOfGray** [comment]
你可以重写一下[SaInterceptor](https://gitee.com/dromara/sa-token/blob/dev/sa-token-starter/sa-token-spring-boot-starter/src/main/java/cn/dev33/satoken/interceptor/SaInterceptor.java#L91)类里面的boolean preHandle方法, 将下面的两个位置换一下
![图片](https://user-images.githubusercontent.com/40094040/227139010-55314cbe-3f63-42a2-862c-3f4737e6855c.png)
然后拦截器里面配置这个类对象应该就可以做到你说的效果, 关于是否修改源码, 我需要和其他维护者商议一下

**Comment by baichangda** [comment]
ok

**Comment by AppleOfGray** [comment]
我刚才测试了一下, 注解鉴权里面是会抛出未登陆异常的
![图片](https://user-images.githubusercontent.com/40094040/227142141-c993de2e-1df4-4ebd-bb94-3954cf31f41f.png)
这是源码:
![图片2](https://user-images.githubusercontent.com/40094040/227142330-5efd9c90-2cc2-4ea3-b9ec-2d8328ff4381.png)
你给的截图我找了, 是当开发者手动调用 StpUtil.getPermissionList();(注解鉴权调用的不是这个) 方法的时候, 才会捕获未登陆异常, 但既然你都手动调用了, 肯定是要提前手动判断当前用户是否登录的呀.

**Comment by baichangda** [comment]
我实际上是模仿了SaCheckPermission实现自定义的注解
调用鉴权方法是checkPermission
刚刚换成checkPermissionAnd就没有这个问题了
这两个方法有一些细微差别

**Comment by AppleOfGray** [comment]
你居然自定义没有告诉我.....................................................
