### ISSUE TITLE
如何实现每次登录重新输入密码

### ISSUE THREAD

**Issue by ClearSeve** [dromara/Sa-Token#412]
登录完一个系统, 不关闭浏览器, 再打开另一个系统跳转到不想直接登录, 想让用户再次输入账号密码, 才能进行登录, 有点类似于QQ快速登录, StpUtil.login, 第二个参数是针对是否关闭浏览器

我想要的是登陆完, 再次打开这个登录页重新登录

有什么方法麻烦大家了

**Comment by ly-chn** [comment]
登录页先执行一下登出事件不就行了吗，这是前端的问题，与后端无关吧
