### ISSUE TITLE
子服务的@SaIgnore注解失效

### ISSUE THREAD

**Issue by tongjiann** [dromara/Sa-Token#415]
### 对以下问题有疑问:
所有请求均通过网关服务到达下游服务，但是网关服务无法获取到下游服务中目标接口对应的方法是否被@SaIgnore注解，只能在网关服务中通过下图的方法进行鉴权
<img width="505" alt="image" src="https://user-images.githubusercontent.com/45749358/229067931-7fc3b375-102e-4d37-8566-d6159bf255c5.png">

那是否意味着在微服务架构下，下游服务@SaIgnore注解是失效的(所有请求经过网关服务转发)

< 备注：请尽量详细描述问题所在 >

**Comment by ly-chn** [comment]
网关这不是仅校验登录嘛, 下游我这边没问题

**Comment by tongjiann** [comment]
比如下游服务有一个接口`/api/public/get-variables`，作用是获取公共变量，理论上不需要登陆即可访问。
但是必须要在网关服务添加`SaRouter.notMathch("/api/public/get-variables")`才能跳过鉴权，不能在下游服务通过注解鉴权的方式跳过鉴权。

**Comment by tongjiann** [comment]
假设：请求R进入网关服务，然后进入下游服务。
代码的情况：请求R对应的方法在下游服务中被@SaIgnore注解了，但是未在网关服务排除鉴权。
结果：请求R在网关服务这一层被拦截下来了，下游服务的@SaIgnore注解失效(没达到预期的效果)
预期：上游服务可以获取到接口对应方法是否被@SaIgnore方法注解

**Comment by ly-chn** [comment]
抱歉, 是我看错了, 你说的没错, 网关无法判断下游服务是否需要鉴权, 一般来说需要做白名单处理. 建议notMatch内容放在配置中心

**Comment by tongjiann** [comment]
好的，感谢

**Comment by ly-chn** [comment]
关于这个问题, 我整理了一下思路, 可暂时尝试以下解决方案: 

忽略[网关鉴权](https://sa-token.cc/doc.html#/micro/gateway-auth?id=_3%e3%80%81%e6%b3%a8%e5%86%8c%e5%85%a8%e5%b1%80%e8%bf%87%e6%bb%a4%e5%99%a8)这一步骤

其余不变, 这样登录校验和权限校验均由子服务完成. 

如果请求量不大且子服务均使用sa-token的话, 性能缺点可以忽略不计

如果有网关统一鉴权的需求的话, 则上述方法不可用, 因为网关相当于一个单独的服务, 无法对子服务进行有效处理(因为子服务可能是nginx等其他非sa-token服务)

而针对SaIgnore注解无法在网关使用的问题, 将不作为bug处理. 后续添加适配的可能性也较低.

**Comment by click33** [comment]
暂时不考虑这种方案，链路太长
