### ISSUE TITLE
 cn.dev33.satoken.application.SaSetValueInterface 中get()方法泛型约束不到位

### ISSUE THREAD

**Issue by ZtfCoder** [dromara/Sa-Token#416]
```java
public default <T> T get(String key, SaRetFunction fun) {
  Object value = get(key);
  if(value == null) {
	  value = fun.run();
	  set(key, value);
  }
  return (T) value;
}
```
对于SaRetFunction  没有泛型约束,我觉得很奇怪,因为,如果这里参数没有加上泛型约束,返回值,可以写任意类型
也不会报错,我觉得应该加上泛型约束 ,例如` Supplier<T> t`,这样保证代码的健壮性

**Comment by click33** [comment]
“对于SaRetFunction 没有泛型约束，可以写任意类型”
就是为了达到 “可以写任意类型” 的目的，才没有加泛型约束。

这就是小小封装的一个语法糖，如果强制指定类型的话反而失去了糖的意义。
