### ISSUE TITLE
前后端分离下如何使用注解鉴权

### ISSUE THREAD

**Issue by duanyhui** [dromara/Sa-Token#427]
### 对以下问题有疑问:
1. 前后端分离下，如何使用StpUtil.getPermissionList()方法通过token查出用户所具有的权限？
2. 前后端分离下，没有Session如何使用注解鉴权？

**Comment by Enaium** [comment]
https://sa-token.cc/doc.html#/use/jur-auth?id=%e8%8e%b7%e5%8f%96%e5%bd%93%e5%89%8d%e8%b4%a6%e5%8f%b7%e6%9d%83%e9%99%90%e7%a0%81%e9%9b%86%e5%90%88
