### ISSUE TITLE
关于 同一账号多次登陆问题

### ISSUE THREAD

**Issue by fishered** [dromara/Sa-Token#428]
### 对以下问题有疑问:

同一账号 多次登陆 调用login 会生成不同的token 并且每一个token都可以创建一个tokensession 如果我只想创建一个呢？token和tokensession 都属于一个satoken:login:session:{userid}的值吗 ？
redis 持久化key  例如：token的key是satoken:login:token:{value} session的key是satoken:login:token-session:{token} 这个key生成的方式我能修改么
< 备注：请尽量详细描述问题所在 >

**Comment by ly-chn** [comment]
使用[UserSession](https://sa-token.cc/doc.html#/fun/session-model?id=_1%e3%80%81user-session)

**Comment by ly-chn** [comment]
长时间未回复, 暂时关闭, 如有疑问欢迎继续讨论
