### ISSUE TITLE
[功能建议] 一次性Token检验的统一实现

### ISSUE THREAD

**Issue by tihSdoolB** [dromara/Sa-Token#430]
### 建议增加的新功能:
建议添加用于 一次性Token检验 的统一实现，类似微信的appId/secret使用方法。
功能可以满足基于时间戳或其他方式的防止重放请求的安全要求。
配置可以从配置文件/内存/数据库等一种或多种的方式读取。

### 应用场景阐述：
复杂应用可能存在向外部应用暴露API接口的需求。
如果外部应用使用登录的方式获取Token验证，会产生额外的登录请求，少数情况会造成延时情况。
如果外部应用改为使用一次性Token验证，第一可以提供额外的安全用于抵抗中间人攻击，第二减少潜在的请求登录次数，第三使得鉴权方式更灵活。

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
你是否在找：[临时Token令牌认证](https://sa-token.cc/doc.html#/plugin/temp-token?id=%e4%b8%b4%e6%97%b6token%e4%bb%a4%e7%89%8c%e8%ae%a4%e8%af%81)?
