### ISSUE TITLE
(Long)StpUtil.getExtra(ID) 返回 Cannot cast cn.hutool.core.convert.NumberWithFormat to java.lang.Long

### ISSUE THREAD

**Issue by zhuangzibin** [dromara/Sa-Token#432]
(Long)StpUtil.getExtra(ID) 返回 Cannot cast cn.hutool.core.convert.NumberWithFormat to java.lang.Long
不知道是哪一步序列化用了hutool，set了Long值进去，拿的时候打印class类是class cn.hutool.core.convert.NumberWithFormat

**Comment by zhuangzibin** [comment]
去掉了自己项目依赖的hutool-all 5.8.16，现在报的错误是class java.lang.Integer cannot be cast to class java.lang.Long

**Comment by ly-chn** [comment]
建议贴一下set时的写法

**Comment by zhuangzibin** [comment]
抱歉，我贴一下完整的demo

**Comment by ly-chn** [comment]
初步判断为hutool的jwt序列化造成, 由字符串序列化无法保留类型, 反序列化时自动推断错误产生.

见[hutool issue#2581](https://github.com/dromara/hutool/issues/2581)
