### ISSUE TITLE
sa-token jwt StpLogicJwtForStateless

### ISSUE THREAD

**Issue by lijianyu** [dromara/Sa-Token#434]
### 使用版本:
<dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot3-starter</artifactId>
            <version>1.34.0</version>
 </dependency>

### 配置信息
#token名称 (同时也是cookie名称)
sa-token.token-name=AccessToken
#token有效期，单位s 默认30天, -1代表永不过期
sa-token.timeout=2592000
#token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
sa-token.activity-timeout=21600
#是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
sa-token.is-concurrent=true
#在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
sa-token.is-share=true
#token风格
#sa-token.token-style=uuid
#是否输出操作日志
sa-token.is-log=true

### 报错信息：
集成了 JWT 使用的 StpLogicJwtForStateless模式
在执行checkLogin 时，提示 cn.dev33.satoken.exception.ApiDisabledException: this api is disabled
at cn.dev33.satoken.jwt.StpLogicJwtForStateless.getSaTokenDao(StpLogicJwtForStateless.java:197)
	at cn.dev33.satoken.stp.StpLogic.getTokenActivityTimeoutByToken(StpLogic.java:1206)
	at cn.dev33.satoken.stp.StpLogic.checkActivityTimeout(StpLogic.java:1085)
	at cn.dev33.satoken.stp.StpLogic.getLoginId(StpLogic.java:693)
	at cn.dev33.satoken.stp.StpLogic.checkLogin(StpLogic.java:658)
	at cn.dev33.satoken.stp.StpUtil.checkLogin(StpUtil.java:289)

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ly-chn** [comment]
把用法贴一下

**Comment by click33** [comment]
StpLogicJwtForStateless 会禁用掉部分功能，你如果在集成 StpLogicJwtForStateless 模式的前提下调用这些功能就会触发 `ApiDisabledException: this api is disabled` 异常

参考：
![image](https://user-images.githubusercontent.com/36243476/233884899-6ed4b4b0-cb10-4411-992b-30d462b7bb43.png)

**Comment by Jinsist** [comment]
StpLogicJwtForStateless模式下为啥不支持checkLogin呀，应该使用什么方式校验JWT有效期
