### ISSUE TITLE
调用getLoginId()方法成功后，执行updateLastActivityToNow方法时加个频率限制

### ISSUE THREAD

**Issue by xingye311** [dromara/Sa-Token#435]
### 建议增加的新功能:
cn.dev33.satoken.stp.StpLogic.getLoginId方法，在获取LoginId成功后，调用updateLastActivityToNow的时候做个频率限制，比如说一秒内只更新一次

### 应用场景阐述：
在Controller层接口处添加SaCheckPermission注解后，实测每调用一次接口，在权限判断的时候会多次调用getLoginId方法，如果开启auto-renew，会在短时间内会多次调用updateLastActivityToNow方法，updateLastActivityToNow虽说是调用redis去做更新操作，但是短时间内多次调用redis的更新方法，一是会拉长权限判断的总时间；如果接口并发比较高的话，频繁调用redis的更新方法，对redis服务器的压力也会比较大。建议在调用updateLastActivityToNow方法时，加个频率限制，比如一秒内只更新一次；从业务层面上来看，短时间内多次调用updateLastActivityToNow也是无意义的
![image](https://user-images.githubusercontent.com/13564435/233608767-c0d7fe0b-9822-4a5f-a43a-eeca1afc2813.png)

**Comment by ly-chn** [comment]
不错的简易, 将考虑采纳

**Comment by click33** [comment]
会认真考虑一下

**Comment by click33** [comment]
目前你可以关闭自动续签，加个全局拦截器 手动续签，来避免这个问题
