### ISSUE TITLE
是否考虑支持SpringData Rest

### ISSUE THREAD

**Issue by yxr2333** [dromara/Sa-Token#440]
### 建议增加的新功能:

添加对SpringData Rest的权限控制支持。

### 应用场景阐述：
SpringData Rest可以根据Repository来“生成”Controller，从而简化开发。

我在代码中注册了路由拦截器，如下所示：
![image](https://user-images.githubusercontent.com/75789516/235690333-b24e36c9-abab-4f40-bcc7-4213a0d88d5d.png)
但是当我在浏览器中访问路径时，发现拦截器似乎并未起到作用，如下图所示：
![image](https://user-images.githubusercontent.com/75789516/235689961-a703806d-5098-49b3-bf76-7eb714cee485.png)
由于我注册了API监控器，IDEA控制台下报错如下所示：
![image](https://user-images.githubusercontent.com/75789516/235690669-980957c1-c8e0-4ccc-84a0-522794a74ba4.png)

这看上去有些奇怪，Sa-Token确实检测到了没有携带token的访问，但是接口可以正常返回内容。

**Comment by click33** [comment]
来个复现demo吧

**Comment by yxr2333** [comment]
> 

https://github.com/yxr2333/satoken_test_demo

**Comment by click33** [comment]
未能复现你说的问题

![image](https://github.com/dromara/Sa-Token/assets/36243476/de28c426-abac-4b11-8011-afd813c23790)

![image](https://github.com/dromara/Sa-Token/assets/36243476/6fae3892-94f2-4e69-ba43-ec4ea12702f0)
