### ISSUE TITLE
Sa-Token攔截器,無法排除預設的路徑

### ISSUE THREAD

**Issue by vt167098** [dromara/Sa-Token#441]
### Sa-token設置排除路徑,但運作無效

我在 registry.addInterceptor是這樣寫的

```
registry.addInterceptor(new SaInterceptor()).addPathPatterns("/**").excludePathPatterns("/swagger-ui");
```
在 SaServletFilter
```
new SaServletFilter()
        // 攔截與排除 path
        .addInclude("/**")
        .addExclude("/swagger-ui/**");
```

我是想將opendoc這個路徑,不需由sa-token處理, 但結果都回傳都是json內容 {"msg": "not handle"},
我想這還是有經過sa-token處理了, 不知道要在那裡寫才能排除/swagger-ui這個路徑.

**Comment by click33** [comment]
1、
swagger 请尝试排除 "/swagger-resources/**", "/webjars/**", "/v2/**", "/swagger-ui.html/**" ,"/doc.html/**","/error","/favicon.ico"
这些路径。（Interceptor 和 Filter 都要排除）

2、
不过根据你上面提供的信息，返回 {"msg": "not handle"}，这是在集成 SSO 或者 OAuth2  时才有可能返回的信息，所以你的问题很可能不是仅仅遗漏了部分路径那么简单。

所以你可以先按照 1 中的方案尝试一下，如果不行，再提供更加详细的信息，或者一个可以复现此问题的 demo 地址。

**Comment by vt167098** [comment]
我試過方案一, 還是不行.
您說的沒錯, 我在此方案確實有集成sso client 與oauth2, 我本以為只要在這樣排除掉路徑就可以了.
因為環境是在內網, 無法提供demo網址

**Comment by click33** [comment]
那你需要对 Sa-Token 有一定的了解才能排查此错误了，以下是框架为什么会返回 {"msg": "not handle"} 的原因：

![image](https://user-images.githubusercontent.com/36243476/235817150-67e97d43-d99c-413e-8cfc-a08d52acbe0c.png)

**Comment by click33** [comment]
你可以先从常见报错速查表里自我排查一下

Sa-Token 常见问题排查：
https://sa-token.cc/doc.html#/more/common-questions

Sa-Token SSO 常见问题排查：
https://sa-token.cc/doc.html#/sso/sso-questions

**Comment by vt167098** [comment]
好, 謝謝, 我自己再查看看.
