### ISSUE TITLE
Webflux websocket 如何加载 sa-token ？

### ISSUE THREAD

**Issue by StringKe** [dromara/Sa-Token#443]
### 对以下问题有疑问:

我在使用 spring-graphql ，默认使用 webflux 来实现 websocket 订阅，想知道如何在 websocket 连接的时候加载 sa-token 。

提供的 demo 是来自 web 的实现，webflux 中 websocket 实现不太一样

**Comment by StringKe** [comment]
![CleanShot 2023-05-06 at 11 43 29@2x](https://user-images.githubusercontent.com/31089228/236597909-8c17f394-fe00-403e-bbd5-c3c494f52340.png)

需要去实现 websocket 的 上下文么，我目前实现了，但是不知道如何切换 dubbo 和 websocket 的上下文

**Comment by zhuangzibin** [comment]
应该只能自己放到contextWrite

**Comment by click33** [comment]
如果问题尚未解决，加群艾特管理员解决吧
