### ISSUE TITLE
ssm 整合 sa-token-oauth2

### ISSUE THREAD

**Issue by qiao1101201300** [dromara/Sa-Token#447]
您好，目前我在使用ssm整合sa-token-oauth2, SaOAuth2Util 中的saOAuth2Template是创建的静态对象，在ssm中一直获取到的就是这个静态对象，但是在springboot中则是我自定义的模板，所以我很好奇在springboot中是如何处理才把这个静态对象改为了自定义模板对象

**Comment by click33** [comment]
直接赋值：SaOAuth2Util.saOAuth2Template = new 你自己的实现类()
