### ISSUE TITLE
请问如果在登录过程中使用验证码，应该怎么交互？

### ISSUE THREAD

**Issue by freshgeek** [dromara/Sa-Token#450]
### 对以下问题有疑问:
1. 首先验证码接口，开放白名单，这个ok
2. 然后是验证码接口需要返回验证码图片等信息、这个时候session中需要存放验证码的code（此处尝试session 、 token session 均会报错，提示未提供token）（此时还未登录自然前端也没有token可拿，目前是在这里卡住了）
3. 然后在登录接口获取会话的code和用户输入的对比，然后成功之后移除

**Comment by click33** [comment]
使用 StpUtil.getAnonTokenSession();

**Comment by click33** [comment]
![image](https://github.com/dromara/Sa-Token/assets/36243476/fe1cb65e-b12a-4283-bae7-3307005edbf3)

**Comment by freshgeek** [comment]
好的 感谢哈~ 即时通讯般的响应速度~
