### ISSUE TITLE
新登录挤掉旧登录问题

### ISSUE THREAD

**Issue by mmdlsu** [dromara/Sa-Token#451]
### 对以下问题有疑问:
旧登录的token没有从redis中去掉，这样两个端来回挤掉，会一直增加token。虽然有过期时间，但是这样一直增加token是否合理？

**Comment by click33** [comment]
可以在先注销一下再登录

// 登录前先注销一下这个账号的所有旧登录
		StpUtil.logout(10001);
		
		// 再登录这个账号
		StpUtil.login(10001);
