### ISSUE TITLE
StpUtil.login报RpcContext.getServerContext()方法异常

### ISSUE THREAD

**Issue by fc88804DOTcn** [dromara/Sa-Token#452]
### 对以下问题有疑问:

如题。
现有项目中使用最新v1.34.0的sa-token版本，Dubbo3.1.7。已经正常使用 登录注销注解鉴权等功能。但是在接入xxl-job时，希望使用到登录功能：StpUtil.login(userID) 报：
![image](https://github.com/dromara/Sa-Token/assets/59227215/2a06e0b2-46a4-4d35-b28e-7483367ec1ff)
异常。
排查了三四个小时候未能解决，一直是这个错误。项目中有引入  插件 
![image](https://github.com/dromara/Sa-Token/assets/59227215/6df0131e-98dd-4071-8922-094881672293)

这个方法在其他系统模块中正常使用登录存储，在xxl中不行 ，求解答。

**Comment by ly-chn** [comment]
由于提供内容太少, 无法复现, 提供一个可能的原因: 
非web上下文中无法执行登录操作, xxl-job中的异步方法非web上下文
相关排查方案: https://sa-token.cc/doc.html#/more/common-questions?id=q%ef%bc%9a%e6%8a%a5%e9%94%99%ef%bc%9a%e9%9d%9eweb%e4%b8%8a%e4%b8%8b%e6%96%87%e6%97%a0%e6%b3%95%e8%8e%b7%e5%8f%96request%e3%80%82
