### ISSUE TITLE
未能捕获NotLoginException异常

### ISSUE THREAD

**Issue by LjyLab** [dromara/Sa-Token#453]
### 对以下问题有疑问:
![image](https://github.com/dromara/Sa-Token/assets/36144129/2d435700-e9f6-434f-b4fd-7f7df047fc9f)

希望是这样
![image](https://github.com/dromara/Sa-Token/assets/36144129/6e4ad62a-5bf5-4950-9b43-7b5f95e14e1c)
但现在是
![image](https://github.com/dromara/Sa-Token/assets/36144129/c3d845ab-f227-4e8d-b8c9-474fe6f6b4df)

在全局异常处理中写了
![image](https://github.com/dromara/Sa-Token/assets/36144129/85f4d6d2-4c74-468b-81fb-01f833789dfa)

< 备注：请尽量详细描述问题所在 >

**Comment by ly-chn** [comment]
大概率是你GlobalException类(另外建议改名叫GlobalExceptionHandler / GlobalExceptionAdvice)没生效, 如果不是的话, 请提供最小复现demo

**Comment by ly-chn** [comment]
快速判断是否生效, 只需要在printStackTrace下面打印一行别的内容就知道了

**Comment by LjyLab** [comment]
`/**
 * 全局异常处理
 */
@RestControllerAdvice
public class GlobalException {
    // 拦截：未登录异常
    @ExceptionHandler(NotLoginException.class)
    public SaResult handlerException(NotLoginException e) {

        // 打印堆栈，以供调试
        e.printStackTrace();

        // 返回给前端
        return SaResult.error(e.getMessage());
    }

    // 拦截：缺少权限异常
    @ExceptionHandler(NotPermissionException.class)
    public SaResult handlerException(NotPermissionException e) {
        e.printStackTrace();
        return SaResult.error("缺少权限：" + e.getPermission());
    }

    // 拦截：缺少角色异常
    @ExceptionHandler(NotRoleException.class)
    public SaResult handlerException(NotRoleException e) {
        e.printStackTrace();
        return SaResult.error("缺少角色：" + e.getRole());
    }

    // 拦截：二级认证校验失败异常
    @ExceptionHandler(NotSafeException.class)
    public SaResult handlerException(NotSafeException e) {
        e.printStackTrace();
        return SaResult.error("二级认证校验失败：" + e.getService());
    }

    // 拦截：服务封禁异常
    @ExceptionHandler(DisableServiceException.class)
    public SaResult handlerException(DisableServiceException e) {
        e.printStackTrace();
        return SaResult.error("当前账号 " + e.getService() + " 服务已被封禁 (level=" + e.getLevel() + ")：" + e.getDisableTime() + "秒后解封");
    }

    // 拦截：Http Basic 校验失败异常
    @ExceptionHandler(NotBasicAuthException.class)
    public SaResult handlerException(NotBasicAuthException e) {
        e.printStackTrace();
        return SaResult.error(e.getMessage());
    }

    // 拦截：其它所有异常
    @ExceptionHandler(Exception.class)
    public SaResult handlerException(Exception e) {
        e.printStackTrace();
        return SaResult.error(e.getMessage());
    }

}`

**Comment by LjyLab** [comment]
> 快速判断是否生效, 只需要在printStackTrace下面打印一行别的内容就知道了

```java
/**
 * 全局异常处理
 */
@RestControllerAdvice
public class GlobalException {
    // 拦截：未登录异常
    @ExceptionHandler(NotLoginException.class)
    public SaResult handlerException(NotLoginException e) {

        // 打印堆栈，以供调试
        e.printStackTrace();

        // 返回给前端
        return SaResult.error(e.getMessage());
    }

    // 拦截：缺少权限异常
    @ExceptionHandler(NotPermissionException.class)
    public SaResult handlerException(NotPermissionException e) {
        e.printStackTrace();
        return SaResult.error("缺少权限：" + e.getPermission());
    }

    // 拦截：缺少角色异常
    @ExceptionHandler(NotRoleException.class)
    public SaResult handlerException(NotRoleException e) {
        e.printStackTrace();
        return SaResult.error("缺少角色：" + e.getRole());
    }

    // 拦截：二级认证校验失败异常
    @ExceptionHandler(NotSafeException.class)
    public SaResult handlerException(NotSafeException e) {
        e.printStackTrace();
        return SaResult.error("二级认证校验失败：" + e.getService());
    }

    // 拦截：服务封禁异常
    @ExceptionHandler(DisableServiceException.class)
    public SaResult handlerException(DisableServiceException e) {
        e.printStackTrace();
        return SaResult.error("当前账号 " + e.getService() + " 服务已被封禁 (level=" + e.getLevel() + ")：" + e.getDisableTime() + "秒后解封");
    }

    // 拦截：Http Basic 校验失败异常
    @ExceptionHandler(NotBasicAuthException.class)
    public SaResult handlerException(NotBasicAuthException e) {
        e.printStackTrace();
        return SaResult.error(e.getMessage());
    }

    // 拦截：其它所有异常
    @ExceptionHandler(Exception.class)
    public SaResult handlerException(Exception e) {
        e.printStackTrace();
        return SaResult.error(e.getMessage());
    }

}
```

**Comment by ly-chn** [comment]
> > 快速判断是否生效, 只需要在printStackTrace下面打印一行别的内容就知道了
> 
> ```java
> /**
>  * 全局异常处理
>  */
> @RestControllerAdvice
> public class GlobalException {
>     // 拦截：未登录异常
>     @ExceptionHandler(NotLoginException.class)
>     public SaResult handlerException(NotLoginException e) {
> 
>         // 打印堆栈，以供调试
>         e.printStackTrace();
> 
>         // 返回给前端
>         return SaResult.error(e.getMessage());
>     }
> 
>     // 拦截：缺少权限异常
>     @ExceptionHandler(NotPermissionException.class)
>     public SaResult handlerException(NotPermissionException e) {
>         e.printStackTrace();
>         return SaResult.error("缺少权限：" + e.getPermission());
>     }
> 
>     // 拦截：缺少角色异常
>     @ExceptionHandler(NotRoleException.class)
>     public SaResult handlerException(NotRoleException e) {
>         e.printStackTrace();
>         return SaResult.error("缺少角色：" + e.getRole());
>     }
> 
>     // 拦截：二级认证校验失败异常
>     @ExceptionHandler(NotSafeException.class)
>     public SaResult handlerException(NotSafeException e) {
>         e.printStackTrace();
>         return SaResult.error("二级认证校验失败：" + e.getService());
>     }
> 
>     // 拦截：服务封禁异常
>     @ExceptionHandler(DisableServiceException.class)
>     public SaResult handlerException(DisableServiceException e) {
>         e.printStackTrace();
>         return SaResult.error("当前账号 " + e.getService() + " 服务已被封禁 (level=" + e.getLevel() + ")：" + e.getDisableTime() + "秒后解封");
>     }
> 
>     // 拦截：Http Basic 校验失败异常
>     @ExceptionHandler(NotBasicAuthException.class)
>     public SaResult handlerException(NotBasicAuthException e) {
>         e.printStackTrace();
>         return SaResult.error(e.getMessage());
>     }
> 
>     // 拦截：其它所有异常
>     @ExceptionHandler(Exception.class)
>     public SaResult handlerException(Exception e) {
>         e.printStackTrace();
>         return SaResult.error(e.getMessage());
>     }
> 
> }
> ```

	// 拦截：未登录异常
    @ExceptionHandler(NotLoginException.class)
    public SaResult handlerException(NotLoginException e) {
		//  e.printStackTrace();效果与未捕获异常效果一样, 换成sout, 判断一下到底走了这个方法没有
		System.out.println("未登录");

        // 返回给前端
        return SaResult.error(e.getMessage());
    }

**Comment by LjyLab** [comment]
> > > 快速判断是否生效, 只需要在printStackTrace下面打印一行别的内容就知道了
> > 
> > 
> > ```java
> > /**
> >  * 全局异常处理
> >  */
> > @RestControllerAdvice
> > public class GlobalException {
> >     // 拦截：未登录异常
> >     @ExceptionHandler(NotLoginException.class)
> >     public SaResult handlerException(NotLoginException e) {
> > 
> >         // 打印堆栈，以供调试
> >         e.printStackTrace();
> > 
> >         // 返回给前端
> >         return SaResult.error(e.getMessage());
> >     }
> > 
> >     // 拦截：缺少权限异常
> >     @ExceptionHandler(NotPermissionException.class)
> >     public SaResult handlerException(NotPermissionException e) {
> >         e.printStackTrace();
> >         return SaResult.error("缺少权限：" + e.getPermission());
> >     }
> > 
> >     // 拦截：缺少角色异常
> >     @ExceptionHandler(NotRoleException.class)
> >     public SaResult handlerException(NotRoleException e) {
> >         e.printStackTrace();
> >         return SaResult.error("缺少角色：" + e.getRole());
> >     }
> > 
> >     // 拦截：二级认证校验失败异常
> >     @ExceptionHandler(NotSafeException.class)
> >     public SaResult handlerException(NotSafeException e) {
> >         e.printStackTrace();
> >         return SaResult.error("二级认证校验失败：" + e.getService());
> >     }
> > 
> >     // 拦截：服务封禁异常
> >     @ExceptionHandler(DisableServiceException.class)
> >     public SaResult handlerException(DisableServiceException e) {
> >         e.printStackTrace();
> >         return SaResult.error("当前账号 " + e.getService() + " 服务已被封禁 (level=" + e.getLevel() + ")：" + e.getDisableTime() + "秒后解封");
> >     }
> > 
> >     // 拦截：Http Basic 校验失败异常
> >     @ExceptionHandler(NotBasicAuthException.class)
> >     public SaResult handlerException(NotBasicAuthException e) {
> >         e.printStackTrace();
> >         return SaResult.error(e.getMessage());
> >     }
> > 
> >     // 拦截：其它所有异常
> >     @ExceptionHandler(Exception.class)
> >     public SaResult handlerException(Exception e) {
> >         e.printStackTrace();
> >         return SaResult.error(e.getMessage());
> >     }
> > 
> > }
> > ```
> 
> ```
> // 拦截：未登录异常
> @ExceptionHandler(NotLoginException.class)
> public SaResult handlerException(NotLoginException e) {
> 	//  e.printStackTrace();效果与未捕获异常效果一样, 换成sout, 判断一下到底走了这个方法没有
> 	System.out.println("未登录");
> 
>     // 返回给前端
>     return SaResult.error(e.getMessage());
> }
> ```

大佬你看 好像确实未生效 
![image](https://github.com/dromara/Sa-Token/assets/36144129/51052b41-cc28-404e-9266-d4c25296d8f5)

**Comment by ly-chn** [comment]
那就排除sa-token的问题了, 是spring配置问题, 具体原因没有源码不好排查, 你可以看看是不是打包方式出了问题, 还是没有没ComponentScan扫描到

**Comment by LjyLab** [comment]
> 那就排除sa-token的问题了, 是spring配置问题, 具体原因没有源码不好排查, 你可以看看是不是打包方式出了问题, 还是没有没ComponentScan扫描到
需要扫描哪些呀

**Comment by ly-chn** [comment]
至少要扫描到你的GlobalException类

排查的话, 首先可以试试将GlobalException类放在与main函数所在的包下, 至少包的前缀要相同

其次maven也可以会导致打包问题, 可以执行一下maven clean再打包试试

不排除你做了这两项以后问题仍然存在的可能

**Comment by LjyLab** [comment]
> 至少要扫描到你的GlobalException类
> 
> 排查的话, 首先可以试试将GlobalException类放在与main函数所在的包下, 至少包的前缀要相同
> 
> 其次maven也可以会导致打包问题, 可以执行一下maven clean再打包试试
> 
> 不排除你做了这两项以后问题仍然存在的可能

**好的好的**
