### ISSUE TITLE
请教一下如何拦截鉴权/actuator端点？

### ISSUE THREAD

**Issue by zhangdp** [dromara/Sa-Token#454]
项目使用了spring-boot-starter-actuator，为了安全期望对/actuator/**进行http basic鉴权，其余/**走正常的登录鉴权。尝试了使用拦截器SaInterceptor来拦截，发现无法拦截到/actuator/**请求，且/actuator/**端点不是自己写的controler方法也无法添加注解。请问各位大佬要怎么实现？

**Comment by JaneYork** [comment]
@zhangdp 后来如何处理的？
