### ISSUE TITLE
多租户系统中redis key前缀问题

### ISSUE THREAD

**Issue by zengyufei** [dromara/Sa-Token#455]
### 建议增加的新功能:
建议加新配置，允许用户自定义 redis 的 key 前缀

### 应用场景阐述：
多租户下，为了好管理租户redis 缓存数据，会利用租户id作为key前缀存放，但是 sa-token 似乎不支持。

希望作者能够新增这类功能，搜索 issues 发现作者不建议此功能，但我觉得这个功能很现实（一个团队多项目或多租户单redis管理），也很常见。

希望作者能够采纳，谢谢！

**Comment by ly-chn** [comment]
1. 一个团队多个项目读写同一个库是不合理的, redis支持分库
2. 利用租户id作为key前缀, 从redis大key方面考虑, 也是不合理的, 真心不推荐
3. 用户id作为用户在系统中唯一标识, 而租户只是用户的其中一个属性, 将租户id作为key前缀, 每次查询用户登录, 需要先查用户租户id, 而查用户租户id, 需要先查用户, 感觉有些矛盾
