### ISSUE TITLE
LoginId 是一个自定义的结构，如何反序列化

### ISSUE THREAD

**Issue by einsitang** [dromara/Sa-Token#456]
### 对以下问题有疑问:

在调用 `StpUtil.login` 方法时，我传入的是自己包装的LoginId结构，里面包含用户ID以及类型
```
class LoginId{
 String id;
 Integer type;
}
```

在其他鉴权接口从 `StpUtil.getLoginId` 方法中拿到的结果只能转换成 `LoginId(id=x,type=y)` 这样的字符串，请问有什么办法可以转换回预期的效果？

**Comment by zhyblack** [comment]
```
 	/** 
 	 * 获取当前会话账号id, 如果未登录，则抛出异常 
 	 * @return 账号id
 	 */
	public static Object getLoginId() {
		return stpLogic.getLoginId();
	}

	/** 
	 * 获取当前会话账号id, 如果未登录，则返回默认值 
	 * @param <T> 返回类型 
	 * @param defaultValue 默认值
	 * @return 登录id 
	 */
	public static <T> T getLoginId(T defaultValue) {
		return stpLogic.getLoginId(defaultValue);
	}
```
你可以试一下下面那个方法

**Comment by zhyblack** [comment]
```
	/**
	 * 存储 Token-Id 映射 
	 * @param tokenValue token值 
	 * @param loginId 账号id 
	 * @param timeout 会话有效期 (单位: 秒) 
	 */
	public void saveTokenToIdMapping(String tokenValue, Object loginId, long timeout) {
		getSaTokenDao().set(splicingKeyTokenValue(tokenValue), String.valueOf(loginId), timeout);
	}
```
不过好像再login的时候就给你调用toString了，

**Comment by zhyblack** [comment]
```
// 会话登录：参数填写要登录的账号id，建议的数据类型：long | int | String， 不可以传入复杂类型，如：User、Admin 等等
StpUtil.login(Object id);     
```
官网有建议了，。
https://sa-token.cc/doc.html#/use/login-auth?id=%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81

**Comment by einsitang** [comment]
> ```
> // 会话登录：参数填写要登录的账号id，建议的数据类型：long | int | String， 不可以传入复杂类型，如：User、Admin 等等
> StpUtil.login(Object id);     
> ```
> 
> 官网有建议了，。 https://sa-token.cc/doc.html#/use/login-auth?id=%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81

非常感谢你的帮忙，我在编码的时候没发现，不过也不符合我们的设计，我们是两张数据表合并抽象成一个用户信息，而且联合主键的话，也没办法直接简单实用，看来我需要自行处理toString和反序列化了。

**Comment by zhyblack** [comment]
> > ```
> > // 会话登录：参数填写要登录的账号id，建议的数据类型：long | int | String， 不可以传入复杂类型，如：User、Admin 等等
> > StpUtil.login(Object id);     
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 官网有建议了，。 https://sa-token.cc/doc.html#/use/login-auth?id=%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81
> 
> 非常感谢你的帮忙，我在编码的时候没发现，不过也不符合我们的设计，我们是两张数据表合并抽象成一个用户信息，而且联合主键的话，也没办法直接简单实用，看来我需要自行处理toString和反序列化了。

使用jwt的实现可以扩展参数 不知道你可不可以使用 
https://sa-token.cc/doc.html#/plugin/jwt-extend?id=%e5%92%8c-jwt-%e9%9b%86%e6%88%90

**Comment by einsitang** [comment]
> > > ```
> > > // 会话登录：参数填写要登录的账号id，建议的数据类型：long | int | String， 不可以传入复杂类型，如：User、Admin 等等
> > > StpUtil.login(Object id);     
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 官网有建议了，。 https://sa-token.cc/doc.html#/use/login-auth?id=%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81
> > 
> > 
> > 非常感谢你的帮忙，我在编码的时候没发现，不过也不符合我们的设计，我们是两张数据表合并抽象成一个用户信息，而且联合主键的话，也没办法直接简单实用，看来我需要自行处理toString和反序列化了。
> 
> 使用jwt的实现可以扩展参数 不知道你可不可以使用 https://sa-token.cc/doc.html#/plugin/jwt-extend?id=%e5%92%8c-jwt-%e9%9b%86%e6%88%90

jwt只能附带数据，不能区分用户，我的业务是需要区分独立的用户，我恐怕要做反序列化处理了
