### ISSUE TITLE
请教大佬如何自定义从请求参数或者从请求body的json里面解析token

### ISSUE THREAD

**Issue by zhangdp** [dromara/Sa-Token#465]
### 对以下问题有疑问:
因业务需求有些接口token不能放在Header中或者Cookie中传输，需要从请求参数中获取token或者从请求body的json解析出token来认证，翻了下官网文档似乎没有这方面的内容，请教下大佬们该如何实现？

**Comment by ly-chn** [comment]
```java
    @PostMapping("test")
    public void test1(@RequestBody Map<String, String> map) {
        // 假设map是个实体类, 我这里没创建
        StpUtil.getStpLogic().checkActivityTimeout(map.get("token"));
    }
```

**Comment by ly-chn** [comment]
具体作用自己看下源码吧, 这个需求有些小众, 所以只能这样做了, sa-token不会读取请求体内容, 因为会造成负面影响

**Comment by click33** [comment]
可以放在url上：  /api/getInfo?satoken=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
![image](https://github.com/dromara/Sa-Token/assets/36243476/6fa3f689-edb3-4378-a97d-64dc19838266)
