### ISSUE TITLE
这个堆栈怎么关掉啊？

### ISSUE THREAD

**Issue by zzy-life** [dromara/Sa-Token#466]
### 对以下问题有疑问: 我只想关掉这个堆栈，我不想知道他怎么来的
![image](https://github.com/dromara/Sa-Token/assets/68179477/5d157ce3-6df5-4124-a437-dc7c75c24696)

< 备注：请尽量详细描述问题所在 >

**Comment by click33** [comment]
你总得描述一下，你做了什么，出现的这个东西吧？

**Comment by zzy-life** [comment]
线上环境才有 测不出来  堆栈是这里抛出的
![image](https://github.com/dromara/Sa-Token/assets/68179477/cc0649e7-3b39-483d-b4ae-da73968cdadf)

**Comment by click33** [comment]
是不是访问404接口了？

**Comment by zzy-life** [comment]
我刚测试了&nbsp; 不是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 中午12:33
收件人: ***@***.***&gt;;
抄送: "Zhiyu ***@***.******@***.***&gt;;
主题: Re: [dromara/Sa-Token] 这个堆栈怎么关掉啊？ (Issue #466)




 
是不是访问404接口了？

**Comment by click33** [comment]
那我也不知道了

**Comment by click33** [comment]
不是 sa-token 框架抛的，sa-token 框架里没有 printStackTrace() 的代码
