### ISSUE TITLE
如何校验指定token是否过期(被挤掉的)

### ISSUE THREAD

**Issue by mmdlsu** [dromara/Sa-Token#467]
被挤掉的token还可以通过StpUtil.getTokenSessionByToken(token)拿到信息

**Comment by mmdlsu** [comment]
主要是用于websocket的鉴权，要校验token是否过期或者被挤掉
![image](https://github.com/dromara/Sa-Token/assets/57515771/97001298-e12c-4a08-95cb-ddd18e0142e4)

**Comment by click33** [comment]
挤掉后 StpUtil.getLoginIdByToken(token) 返回的会是null
