### ISSUE TITLE
oauth2功能使用疑问

### ISSUE THREAD

**Issue by dh-free** [dromara/Sa-Token#469]
### 对以下问题有疑问:
oauth2功能使用，点击注销后，静默授权和显示授权不跳转，直接就获取到了

< 备注：请尽量详细描述问题所在 >
oauth2功能使用时，我显示授权和静默授权拿到token后，为啥点击注销后，再次点授权就直接获取到了token，不应该跳转重新通过code获取么？

**Comment by dh-free** [comment]
或者换个说法，怎么才能注销的时候把这些信息都清除掉，让用户重新进行登录授权。比如我在掘金网站用微信扫码登录成功后，然后退出登录，再次登录的时候又要重新扫码

**Comment by click33** [comment]
1、再次点授权就直接获取到了token
其实浏览器有跳转，只不过跳转过程是自动化的，一瞬间完成的，你看到的就好像没跳转。
你注销只是注销了client的会话数据，OAuth-Server 端的会话还在，当然就会一点击，就自动登录上了 

2、比如我在掘金网站用微信扫码登录成功后，然后退出登录，再次登录的时候又要重新扫码
扫码登录和OAuth2 授权是两种登录流程，不能拿来一起做类比

**Comment by dh-free** [comment]
> 感谢回复，我就想知道，我该怎么实现能让注销的时候，两端都注销，我目前在client端加了removetoken的调用，但还是不行
![image](https://github.com/dromara/Sa-Token/assets/48708512/d965f699-0ce3-48d1-81e2-8a7dac87b51b)

**Comment by dh-free** [comment]
> > 感谢回复，我就想知道，我该怎么实现能让注销的时候，两端都注销，我目前在client端加了removetoken的调用，但还是不行
> > ![image](https://user-images.githubusercontent.com/48708512/248547334-d965f699-0ce3-48d1-81e2-8a7dac87b51b.png)

我能想到的就是手动把redis的相关数据删掉，但感觉太low了

**Comment by click33** [comment]
removetoken 没用
oauth2 规范中，应该没有能力做到client清除Server端的数据
你想想，酷狗音乐使用QQ第三方登录，你注销酷狗登录，也不会使QQ掉线

**Comment by dh-free** [comment]
可能场景我搞错了，我的场景是需要做一个多应用的统一授权的服务，带登录界面，不同的应用全部都从这里登录认证。账户体系也统一在这个服务中管理，所以我想的是用这个password模式，通过不同的clientid区分不同应用，应用注销后就应该重新回到登陆页面取登录

**Comment by dh-free** [comment]
> 可能场景我搞错了，我的场景是需要做一个多应用的统一授权的服务，带登录界面，不同的应用全部都从这里登录认证。账户体系也统一在这个服务中管理，所以我想的是用这个password模式，通过不同的clientid区分不同应用，应用注销后就应该重新回到登陆页面取登录

我的场景其实更应该是sso是不，但我这些系统又不互通，都是独立的系统，不能一处登录，其他都不登陆

**Comment by click33** [comment]
sso和OAuth2 都是一处登陆，处处通行的
