### ISSUE TITLE
希望能加一个不用登录的注解

### ISSUE THREAD

**Issue by ll789899** [dromara/sa-token#47]
现在只有一个@SaCheckLogin用来检测登录 希望加一个注解放行非登录用户 这样不用去写路由配置比较方便

**Comment by click33** [comment]
默认啥都不写就是不登录

**Comment by ll789899** [comment]
就比如我给user/**添加了登录拦截器 但是其中user/login、user/register等方法我只需要加一个注解就能允许该接口放行 这样就不用写excludePathPatterns  而且修改了相关url地址后也不用同时修改配置了 方便偷懒🤣
