### ISSUE TITLE
未能获取有效的上下文处理器”

### ISSUE THREAD

**Issue by wujixialan** [dromara/Sa-Token#470]
### 对以下问题有疑问:

spring-boot-starter-web 和spring-boot-starter-webflux  都引入了，结果报 未能获取有效的上下文处理器”
< 备注：请尽量详细描述问题所在 >

**Comment by AndyT0** [comment]
SpringBoot3 版本吗？

**Comment by ly-chn** [comment]
请先根据[官方文档-常见问题](https://sa-token.cc/doc.html#/more/common-questions)进行排查
