### ISSUE TITLE
StpUtil.logout();清除cookie失败

### ISSUE THREAD

**Issue by LoveleeKay** [dromara/Sa-Token#471]
### 使用版本:
1.31.0

### 涉及的功能模块：
StpUtil.logout();

### 测试步骤：
+ 我经过以下步骤测试：
StpUtil.logout();  
+ 得出以下结果：
浏览器清除cookie失败

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：
原因：cn.dev33.satoken.context.model.SaResponse#deleteCookie 删除cookie的方法中没有传入domain
+ 我的理解是：
原因：cn.dev33.satoken.context.model.SaResponse#deleteCookie 删除cookie的方法中没有传入domain
请问，是我的理解不对，还是文档出了问题？

**Comment by click33** [comment]
升级到最新版试试，如果还是这样的话，请提供一个复现demo

**Comment by LoveleeKay** [comment]
![image](https://github.com/dromara/Sa-Token/assets/35088017/f9d3e680-1cae-4f17-a29b-300500557161)
应该是新版本解决了，感谢

**Comment by MapleChenf** [comment]
1.37.0版本这个问题又出现了
