### ISSUE TITLE
请问一个后端中， 多个前端如何实现登录（不同用户，比如APP端和管理后台）

### ISSUE THREAD

**Issue by lwxk** [dromara/Sa-Token#473]
### 对以下问题有疑问:

< 备注：请尽量详细描述问题所在 >

**Comment by click33** [comment]
你能再把业务场景描述清楚一点吗，只看标题我理解的意思，你是在找多账号登录？https://sa-token.cc/doc.html#/up/many-account

**Comment by lwxk** [comment]
是的，谢谢。
