### ISSUE TITLE
关于SaStorage 类起名字的一些想法。

### ISSUE THREAD

**Issue by zzq666666** [dromara/Sa-Token#474]
第一次看到cn.dev33.satoken.stp.StpLogic#setTokenValueToStorage 方法的时候，我以为是要吧token存储到浏览器的storage中去，仔细一想，服务器是无法操作浏览器storage的，于是各种差资料作者是通过什么手段把token塞到浏览器的storage中去的，用意是什么。
后来发现偶着的注释： Storage Model，请求作用域的读取值对象。<p> 在一次请求范围内: 存值、取值。数据在请求结束后失效。
这方恍然大悟，原来就是作用于就是一次请求。于是我就有点怀疑这个名字起的不好了，叫SaRequest 或者 SaRequestStorage是不是更好点。

SaStorageForServlet在前后端分离的场景下，是不是比较鸡肋，前后端分离的场景下基本上都是请求参数，或者header进行交互，基本上不会去操作Reruest作用域吧。

可能是我太菜了，看了一上午才想到看注释，才看明白。

**Comment by click33** [comment]
“于是我就有点怀疑这个名字起的不好了”
取名字时我也纠结了半天，没想到啥好名字.

“叫 SaRequest 或者 SaRequestStorage是不是更好点。”
不太行，SaRequest 已经有这个类了，SaRequestStorage 也有点撞衫

“SaStorageForServlet在前后端分离的场景下，是不是比较鸡肋”
这个和是否前后端分离没有关系，将 token 保存在 SaStorage 中是为了在一个方法中执行 StpUtil.login() 后可以立即读取到 token

**Comment by zzq666666** [comment]
“将 token 保存在 SaStorage 中是为了在一个方法中执行 StpUtil.login() 后可以立即读取到 token”
懂了，当调用cn.dev33.satoken.stp.StpUtil#getTokenValue 方法的时候，是优先从SaStorage中获取。感谢🙏
