### ISSUE TITLE
同一账号最大登录数量的处理策略

### ISSUE THREAD

**Issue by time-light-watcher** [dromara/Sa-Token#475]
### 建议增加的新功能:
达到同一账号最大登录数量maxLoginCount时建议提供多种处理策略：
1. 拒绝登录创建新会话
2. 注销最先过期的会话
3. 注销最先登录的会话（当前版本采用的策略）

### 应用场景阐述：
多个用户共用一个账号时，有可能最先登录的用户才是活跃的，而之后登录的用户并不活跃。按当前版本的策略，当达到最大登录数量时，后登录的不活跃会话甚至早已过期的会话的TokenSign仍被保留在tokenSighList中，反而真正的活跃会话被注销了，用户体验很不友好。

**Comment by click33** [comment]
好想法，不过有点难办

**Comment by time-light-watcher** [comment]
目前token的lastActiveTime似乎是通过单独的缓存key维护的，并且满足active-timeout过期了之后，并不会同时清除token-session以及account-session的tokenSighList中的这个token。
那么是不是可以考虑将lastActiveTime直接保存到TokenSign中，这样应该不会影响原有逻辑，且按会话过期顺序注销会话也能直接对tokenSighList排序实现。

**Comment by click33** [comment]
此插件需求已提交到 sa-token-three-plugin 仓库，请在此链接关注后续是否实现：
https://github.com/sa-tokens/sa-token-three-plugin/issues/1
