### ISSUE TITLE
SpringBoot配置文件添加了 lazy-initialization 导致无法加载上下文

### ISSUE THREAD

**Issue by modakai** [dromara/Sa-Token#478]
### 使用版本:
1.34.0

### 报错信息：
![357069140fdb01636f613897ae9ecc81](https://github.com/dromara/Sa-Token/assets/124060255/f66ab9d5-9d35-4797-8009-2a485cc2e8c2)

### 步骤
在application.yml 配置文件中加上这一行之后
![cd143f7ae8458923ec9034fb152f7b9f](https://github.com/dromara/Sa-Token/assets/124060255/e5db80f6-c10c-463e-beb5-6282b28f4845)
会导致 无法加载上下文; 启动后
![image](https://github.com/dromara/Sa-Token/assets/124060255/73b1a7e1-2896-4d5f-9b2e-a5a2556dc1a5)
当不加入时
![image](https://github.com/dromara/Sa-Token/assets/124060255/a11bfa52-0548-4570-9680-cd74fcf0a247)
配置文件中的配置也会全部导入到指定的 SaManager 中的配置类里
不知道算不算Bug

**Comment by sz-wang-zh** [comment]
gitee上有人提问了，issue里有人给出了解决方案
