### ISSUE TITLE
关于刷新token的问题

### ISSUE THREAD

**Issue by TOP-LH** [dromara/Sa-Token#481]
问题描述:
你好, 关于刷新token的问题我有一些问题想提问一下, 现在我们的续签是不断的重置redis的时长, 使其token不过期. 
但作为安全性来说, 这样是不对的, 这样也就代表一旦黑客获取到一个token他就可以一直使用这个token进行操作.

我的最终目标:
需要不定时的作废掉这个token, 让前端使用新的token来访问(但需要让用户尽量无感知), 才能避免这种操作
请问有什么好的办法实现吗? 望解答, 谢谢

**Comment by ly-chn** [comment]
想法不错, 非常的棒, 但

> 前端使用新的token, 来源不还是后端吗, 只要后端不断下发新的token, 那么用不用新的token就没有区别, 只是黑客(算不上)要加一段逻辑来更新token, 两行代码的事

你要做的是
1. 加强密码安全, 避免密码泄露
2. 限流防止用户获取大量数据

**Comment by caizy-2020** [comment]
> 问题描述: 你好, 关于刷新token的问题我有一些问题想提问一下, 现在我们的续签是不断的重置redis的时长, 使其token不过期. 但作为安全性来说, 这样是不对的, 这样也就代表一旦黑客获取到一个token他就可以一直使用这个token进行操作.
> 
> 我的最终目标: 需要不定时的作废掉这个token, 让前端使用新的token来访问(但需要让用户尽量无感知), 才能避免这种操作 请问有什么好的办法实现吗? 望解答, 谢谢

Oauth2.0里的authToken和refreshToken机制好像能满足你的需求
