### ISSUE TITLE
token被挤下线后，redis中的数据希望被清除

### ISSUE THREAD

**Issue by javaerSivan** [dromara/Sa-Token#482]
### 建议增加的新功能:
token被挤下线后，redis中的数据希望被清除

### 应用场景阐述：
当我开启了互踢登录的方式后，第二个设备上登入同一个账号时，第一个token确实作废了，但是依然保持才redis中，会导致redis中出现很多无效的token,希望能将这类垃圾数据清理。
我尝试使用监听器（SaTokenListener）去手动删除，但是却发现没有进 如下方法：
/** 每次被顶下线时触发 */
    @Override
    public void doReplaced(String loginType, Object loginId, String tokenValue) 

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
![image](https://github.com/dromara/Sa-Token/assets/36243476/fccc9bf1-7f55-4ec1-aa59-c155416bb5b9)
