### ISSUE TITLE
StpUtil.getLoginIdByToken 方法实现逻辑疑问

### ISSUE THREAD

**Issue by GourdErwa** [dromara/Sa-Token#486]
### 对以下问题有疑问:
考虑如果集成 redis，权限校验时会查询一次 redis，通过 token 找账号 ID 是否也会查询一次 redis ？

功能实现疑问：
如果集成 redis，调用该方法是否在查询 redis 一次？还是通过反解析 token 直接可以拿到账号 ID
``` java
// 获取指定 token 对应的账号id，如果未登录，则返回 null
StpUtil.getLoginIdByToken(String tokenValue);
```

**Comment by ly-chn** [comment]
会调用redis, 怎么你们redis很脆弱嘛哈哈

没关系的, 这几次调用对redis不会造成什么压力. 

> 当你知道造成压力时, 它才真的对redis造成了压力. 当你对这一点有疑问时, 大概率不影响你们的redis性能

**Comment by GourdErwa** [comment]
> 会调用redis, 怎么你们redis很脆弱嘛哈哈
> 
> 没关系的, 这几次调用对redis不会造成什么压力.
> 
> > 当你知道造成压力时, 它才真的对redis造成了压力. 当你对这一点有疑问时, 大概率不影响你们的redis性能

APP 用户每次通过 token 传递用户信息，如果这样一个请求需要 2 次 redis 查询。压力可以接收。

如果可以把用户 id 映射到 token 中，每次反解析 token 就可以了，不知是否可行？

**Comment by ly-chn** [comment]
其一, 这个点可以优化, 就是java内置一个二级缓存, 从java缓存中读取用户信息即可, 但是对java内存消耗有所提高, 各有优劣
其二, 从token解析出来用户id了, 如何判定用户登录是否过期了呢?
其三, 每次反解析token就可以获取用户id, 可以扩展来想, 不仅id, 也可以查用户角色和权限和其他内容, 已经实现了, 名词叫jwt, 见[文档](https://sa-token.cc/doc.html#/plugin/jwt-extend)
> 关于jwt我也列举一些优缺点, 供你参考
> 
> 优点: 无需redis, 也无需java缓存用户token, 服务器存储压力大大减小, 不怕用户重启
> 
> 缺点: 
> 1. token会变得很长, 因为要存储用户信息, 具体长度由存储的信息量决定
> 2. java解析会耗内存, 如果存储信息过多, 不比redis快
> 3. 由于jwt token很长, 网络传输性能会有影响
> 4. 其余暂不列举了, 各有优劣, 不好评估, 根据你们实际需求抉择即可

**Comment by GourdErwa** [comment]
感谢解答。您可以关闭该问题。
提一个小建议，为了避免引入三方依赖，或者最小化引入三方的工具包，可以使用 [shaded-jar](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) 模式处理，隔离 sa-token 中依赖工具包与实际项目相同依赖版本不一致问题。
