### ISSUE TITLE
新增支持多种登录认证方式

### ISSUE THREAD

**Issue by caizy-2020** [dromara/Sa-Token#490]
### 建议增加的新功能:
建议在StpLogic 新增定义类似Spring Security中的AuthenticationProvider支持可扩展的多种登录认证，例如短信验证码、微信公众号登录

### 应用场景阐述：
现在很多的网站、H5网站、app都是支持多种登录认证方式的，微信登录、短信验证码登录，密码登录都是常见的

**Comment by ly-chn** [comment]
参考[ruoyi-vue-plus](https://gitee.com/dromara/RuoYi-Vue-Plus/blob/4.X/ruoyi-system/src/main/java/com/ruoyi/system/service/SysLoginService.java)中的demo



可以详细讲讲和你的需求之间的差异吗, 除了编码位置不同以外

**Comment by click33** [comment]
你说的这些都是登录的前奏动作，Sa-Token 只管登录后的会话管理，不掺和前奏动作

**Comment by caizy-2020** [comment]
> 参考[ruoyi-vue-plus](https://gitee.com/dromara/RuoYi-Vue-Plus/blob/4.X/ruoyi-system/src/main/java/com/ruoyi/system/service/SysLoginService.java)中的demo
> 
> 可以详细讲讲和你的需求之间的差异吗, 除了编码位置不同以外

好的，非常感谢。
可能是我表达的问题，我不是想要具体的代码实现。
我的重点是想着Sa-Token框架本身是不是可以定义好这样的一个接口或者抽象类等可以供开发者自行实现

**Comment by caizy-2020** [comment]
> 你说的这些都是登录的前奏动作，Sa-Token 只管登录后的会话管理，不掺和前奏动作

好的，那可能是我自己对Sa-Token的理解有问题，谢谢

**Comment by ly-chn** [comment]
后续可能会有人开发插件来实现, 但这个需求太小众了, 暂时能想到的原因如下: 
1. 小程序/公众号等接口变动频繁, 维护压力大, 如果维护不及时, 还不如用户自己写, 而且第三方插件已经很完善了
2. 登录校验, 是否需要存储用户信息, 权限信息, 更新频率等等, 这些由用户自己把控更合适
3. 事实上sa-token也没有针对密码登录进行校验, 只是内置了一些加密方式.
4. 即便内置了小程序/公众号等方式登录, 用户还是要集成第三方工具使用小程序的其他API, 属于需求重复了
