### ISSUE TITLE
关于单点登录实现问题

### ISSUE THREAD

**Issue by youaremywind** [dromara/Sa-Token#492]
### 对以下问题有疑问:
关于

< 备注：请尽量详细描述问题所在 >
### 使用版本:
<dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-sso</artifactId>
            <version>1.35.0.RC</version>
        </dependency>
### 涉及的功能模块：
登录 和 校验

### 测试步骤：
+ 我经过以下步骤测试：
在https://plus-doc.dromara.org/#/ruoyi-cloud-plus/home 系统中，想实现https://sa-token.cc/doc.html#/sso/sso-home-jump 这个
功能，进行代码集成之后，发现登录成功之后未跳转到home页面，sso-home-jump这个项目登录，成功之后会刷新一下 ，但是刷新的时候一直判断是未登录
![image](https://github.com/dromara/Sa-Token/assets/18423358/d03f6980-9491-49e3-9998-9dfcf4be1710)

![image](https://github.com/dromara/Sa-Token/assets/18423358/5779d845-1dae-4a5b-a489-551ef0420fef)

后来发现是ruoyi-cloud-plus中的配置文件中is-read-cookie: false 导致的，不改变这个的前提下，如何做到让系统可以登录成功后进入home页面
或者说有其他什么更好的方案

**Comment by click33** [comment]
那就前端自己跳页面呗，location.href=xxx 这样

**Comment by click33** [comment]
还有疑问的话 加群咨询吧
