### ISSUE TITLE
访问http://sa-sso-client1.com:9001/ 没有重定向对应的登录页面

### ISSUE THREAD

**Issue by youaremywind** [dromara/Sa-Token#493]
### 使用版本:
		<sa-token.version>1.35.0.RC</sa-token.version>
### 涉及的功能模块：
登录

### 测试步骤：
+ 我经过以下步骤测试：
https://sa-token.cc/doc.html#/sso/sso-type2
启动
<img width="317" alt="image" src="https://github.com/dromara/Sa-Token/assets/18423358/71e951ef-0b80-48b0-9f41-b4d1a0beacf1">
访问http://sa-sso-client1.com:9001/ 没有重定向到 对应的登录页面
+ 得出以下结果：

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：
<img width="805" alt="image" src="https://github.com/dromara/Sa-Token/assets/18423358/3d1d97f8-01f9-4983-80bc-63286bc0e355">

+ 我的理解是：
<img width="1025" alt="image" src="https://github.com/dromara/Sa-Token/assets/18423358/7336d5f7-9170-46a7-a9fc-32337be801f6">
没有对/这个接口做拦截所以没有定向到 登录页面
请问，是我的理解不对，还是文档出了问题？

**Comment by click33** [comment]
需要你手动点一下登录，才去跳转到登录页面
如果要全自动化，可以参考此处 
![image](https://github.com/dromara/Sa-Token/assets/36243476/6f8894e6-3ada-4fa8-afc7-0e6342081575)

https://sa-token.cc/doc.html#/sso/sso-questions
