### ISSUE TITLE
buildRedirectUrl中deleteTicket怎么没有根据client获取对应的ticket

### ISSUE THREAD

**Issue by wtf-boy** [dromara/Sa-Token#495]
### 对以下问题有疑问:
public String buildRedirectUrl(Object loginId, String client, String redirect) {
		
		// 校验 重定向地址 是否合法 
		checkRedirectUrl(redirect);
		
		// 删掉 旧Ticket  
		deleteTicket(getTicketValue(loginId));
		
		// 创建 新Ticket
		String ticket = createTicket(loginId, client);
		
		// 构建 授权重定向地址 （Server端 根据此地址向 Client端 下放Ticket）
		return SaFoxUtil.joinParam(encodeBackParam(redirect), paramName.ticket, ticket);
	}

< 备注：请尽量详细描述问题所在 >
单点登录时,会在不同client中创建不同的ticket,但是删除时直接取最新的ticket,可能导致其它client的ticket被删除，导致后续校验错误
![image](https://github.com/dromara/Sa-Token/assets/11848141/670edf9d-61ce-4957-a714-4be2f1cc8ace)

**Comment by click33** [comment]
就是要保证同一时间内只能有一个ticket可用

**Comment by click33** [comment]
正常情况下，一个ticket从创建，到校验，再到删除，只要客户网速够快，不会超过三秒，你说的“删除时直接取最新的ticket,可能导致其它client的ticket被删除”这种情况基本不会存在，哪怕存在了，也是应该删除的，ticket是临时授权票据，同一时间内，只能有一个ticket是可用的，如果ticket没被用掉，那下次用户创建时，框架就会自动帮他把上一次的删掉

这是 OAuth2 模式下 code 授权码的特点，sso模式三就是参照OAuth2授权码模式设计的，ticket的特点和code是差不多的：
![image](https://github.com/dromara/Sa-Token/assets/36243476/cc38cff3-1886-45ff-9e40-01748b077208)

**Comment by wtf-boy** [comment]
明白了，谢谢
