### ISSUE TITLE
建议增加refreshToken

### ISSUE THREAD

**Issue by zhangdp** [dromara/Sa-Token#498]
### 建议增加的新功能:
普通登录目前只有单token机制可以称为只有accessToken，建议增加类似oauth2的accessToken、refreshToken机制，不自动续签accessToken，改为必须由refreshToken来续签，且每次续签会签发新的accessToken、refreshToken，旧的作废

### 应用场景阐述：
1、单accessToken每次请求都自动续签，存在多次无必要redis操作，甚至一个请求就续签好几次（经观察应该是有调用getLoginId()就会续签，但是一个请求会有检查登录、检查权限、获取用户id、获取session等等好几次操作），在多并发场景下或者比如前端定时请求比较多的情况下影响较大。如果引入refreshToken职责清晰，必要的时候再续签减少操作提升性能。
2、accessToken时间比较短，在移动端app场景下比如长时间不操作或者后台时间久了再次进入app时就会出现token已过期需要重新登陆的情况，如果引入refreshToken则可以先通过refreshToken获取新accessToken避免重新登陆提升用户感知。虽然也可以通过自动重新登陆来解决，但是如果是密码登陆无疑增加暴露密码的风险，有些app是通过第三方单点登录的多次请求也不合适。
3、加入refreshToken安全一些，至少心理上觉得，一是每次请求都会传输accessToken且刷新还不会变，被拦截获取的风险较高，真被抓包拿到了token甚至可以用到死，而refreshToken只在第一次登录和续签时才会传输，次数对比传输accessToken简直不值一提，不可否认refreshToken也有泄露的风险，但我们能做的不就是竭尽可能减少被盗取的风险吗，就跟密码也会泄露一样，那我们就可以不用token不用session每次请求都直接带上账号密码吗？总而言之，一是加入refreshToken减少传输次数从而减少被拦截获取的风险，二是每次续签都会签发新的且旧的作废，如果真泄露了能减少损失，提升盗取的难度。[RFC6749](http://www.rfcreader.com/#rfc6749_line2308)第10.4也提到了服务器需要维护refreshToken与客户端的绑定关系，以及传输refreshToken需使用加密传输等来保证安全，而单accessToken就不好维护绑定关系，保护就传输几次的refreshToken也总比保护传输无数次的accessToken简单高效

**Comment by click33** [comment]
关于长短 token，Sa-Token 没有提供直接的 API 支持，但是你可以利用 “临时 token 认证模块” 轻易的达到这一点：

1、把 `sa-token.timeout` 的值配置小一点，然后把 StpUtil.login(10001) 生成的 token 作为短 token ，用来鉴权
2、用 “临时 token 认证模块” 生成长token， `String refreshToken = SaTempUtil.createToken(10001, 2592000);`
3、把这两个 token 一起返回到前端
4、你再开个接口，可以让前端通过长token，刷新短token，参考代码：

``` java

	@RequestMapping("/refreshToken")
	public SaResult refreshToken(String refreshToken) {
		// 1、验证
		Object userId = SaTempUtil.parseToken(refreshToken);
		if(userId == null) {
			return SaResult.error("无效 refreshToken");
		}

		// 2、为其生成新的短 token
		String accessToken = StpUtil.createLoginSession(userId);

		// 3、返回
		return SaResult.data(accessToken);
	}
```

**Comment by zclcs** [comment]
> 关于长短 token，Sa-Token 没有提供直接的 API 支持，但是你可以利用 “临时 token 认证模块” 轻易的达到这一点：
> 
> 1、把 `sa-token.timeout` 的值配置小一点，然后把 StpUtil.login(10001) 生成的 token 作为短 token ，用来鉴权 2、用 “临时 token 认证模块” 生成长token， `String refreshToken = SaTempUtil.createToken(10001, 2592000);` 3、把这两个 token 一起返回到前端 4、你再开个接口，可以让前端通过长token，刷新短token，参考代码：
> 
> ```java
> 	@RequestMapping("/refreshToken")
> 	public SaResult refreshToken(String refreshToken) {
> 		// 1、验证
> 		Object userId = SaTempUtil.parseToken(refreshToken);
> 		if(userId == null) {
> 			return SaResult.error("无效 refreshToken");
> 		}
> 
> 		// 2、为其生成新的短 token
> 		String accessToken = StpUtil.createLoginSession(userId);
> 
> 		// 3、返回
> 		return SaResult.data(accessToken);
> 	}
> ```

这样好像无法校验refreshToken的有效性

**Comment by TheBlindM** [comment]
> 关于长短 token，Sa-Token 没有提供直接的 API 支持，但是你可以利用 “临时 token 认证模块” 轻易的达到这一点：
> 
> 1、把 `sa-token.timeout` 的值配置小一点，然后把 StpUtil.login(10001) 生成的 token 作为短 token ，用来鉴权 2、用 “临时 token 认证模块” 生成长token， `String refreshToken = SaTempUtil.createToken(10001, 2592000);` 3、把这两个 token 一起返回到前端 4、你再开个接口，可以让前端通过长token，刷新短token，参考代码：
> 
> ```java
> 	@RequestMapping("/refreshToken")
> 	public SaResult refreshToken(String refreshToken) {
> 		// 1、验证
> 		Object userId = SaTempUtil.parseToken(refreshToken);
> 		if(userId == null) {
> 			return SaResult.error("无效 refreshToken");
> 		}
> 
> 		// 2、为其生成新的短 token
> 		String accessToken = StpUtil.createLoginSession(userId);
> 
> 		// 3、返回
> 		return SaResult.data(accessToken);
> 	}
> ```

有详细的demo吗？根据你的例子会一直出现未能读取到有效Token

**Comment by click33** [comment]
![image](https://github.com/dromara/Sa-Token/assets/36243476/d5c80cb9-8a30-4c88-8ca9-66573f5edda3)
参考排查

**Comment by TheBlindM** [comment]
![image](https://github.com/dromara/Sa-Token/assets/48701152/5b8df19d-1f93-4944-9610-d5975e2e1db3)
![image](https://github.com/dromara/Sa-Token/assets/48701152/711e22e6-3415-48a3-9c2d-a7b1af3a2745)
![image](https://github.com/dromara/Sa-Token/assets/48701152/12fd34cd-4a04-4536-8dd0-0a4ec1d7d514)
![image](https://github.com/dromara/Sa-Token/assets/48701152/5d8fc4e6-109c-4d40-a435-a0bd36815828)

**Comment by TheBlindM** [comment]
![image](https://github.com/dromara/Sa-Token/assets/48701152/473dfb35-e933-43d0-b0df-0fe526ffed86)
StpUtil.checkLogin() 一直异常

![image](https://github.com/dromara/Sa-Token/assets/48701152/8d09a7f8-96ee-466a-85c8-eb2d174af214)
