### ISSUE TITLE
可不可以提供通过id反查询用户信息功能

### ISSUE THREAD

**Issue by modakai** [dromara/Sa-Token#501]
在权限认证的时候 想通过loginId 反查询用户的信息，但是我看了一群官网的API好像都没有（或许是我看漏了）
![image](https://github.com/dromara/Sa-Token/assets/124060255/64a5eb43-bde3-48e3-ac5c-290c5e0bfe45)
如果没有这个API的话，希望以后可以提高一下，个人觉得是很方便的，既然都存储到缓存中了，就省去查询一次数据库

**Comment by click33** [comment]
// 获取账号 id 为 10001 的 Account-Session
StpUtil.getSessionByLoginId(10001);

获取指定账号的 SaSession 对象，然后读写数据
