### ISSUE TITLE
OAuth2.0推荐升级到OAuth2.1

### ISSUE THREAD

**Issue by monkeyk** [dromara/Sa-Token#503]
### 建议增加的新功能:
OAuth2.0推荐升级到OAuth2.1

### 应用场景阐述：
- 更高的安全场景支持
- 更多的终端设备与安全接入（物联网相关）
- 与openid connect 1.0整合

https://andaily.com/blog/?p=20004

**Comment by click33** [comment]
OAuth2模块的升级方案目前正在计划中

**Comment by Liesport758** [comment]
准备升级到oauth2.1吗
