### ISSUE TITLE
[solved] 因@EnableWebMvc导致的非Web上下文无法获取Request

### ISSUE THREAD

**Issue by Asteroid77** [dromara/Sa-Token#505]
已解决，给后面的小伙伴们参考，节省时间。
---
环境：Spring Boot 2.7.5 , Java8, maven.
背景：项目初期集成Swagger3因历史原因启动类加上了@EnableWebMvc，当时使用Shiro权限框架开发并无异常。
但换到Sa-Token后，一直报非Web上下文无法获取Request(Response)
查阅[文档](https://sa-token.cc/v/v1.34.0/doc.html#/more/common-questions?id=q%ef%bc%9a%e5%9c%a8-saservletfilter-%e4%b8%ad%e8%b0%83%e7%94%a8-springmvcutilgetrequest-%e6%8a%a5%e9%94%99%ef%bc%9a%e9%9d%9eweb%e4%b8%8a%e4%b8%8b%e6%96%87%e6%97%a0%e6%b3%95%e8%8e%b7%e5%8f%96request%ef%bc%9f)，发现配置类中需要取消掉@EnableWebMvc，当时没细想以为启动类有也可以，但随着我使用最小系统复现发现启动类有也不行。

取消后，启动报错：
[Failed to start bean 'documentationPluginsBootstrapper' in spring data rest](https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest)
链接里面，给出了无需@EnableWebMvc注解启用Swagger3的方案，调整后目前正常使用Sa-Token，希望这篇Issue能给你节省一些时间。

The issue has been resolved, and I hope that sharing this solution will help others avoid wasting time. The problem arose because I was using Swagger3 in a Spring Boot project. Due to some historical reasons, I had used the @EnableWebMvc annotation in the application class. However, the Sa-Token framework is not compatible with the @EnableWebMvc annotation (In fact, it's not advisable to use this annotation in a Spring Boot project).

Subsequently, I removed the @EnableWebMvc annotation. However, I encountered an error when starting my project: [Failed to start bean 'documentationPluginsBootstrapper' in Spring Data REST](https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest). I managed to resolve this error using the information provided in the provided link.

**Comment by ly-chn** [comment]
感谢提供, 为你点赞
