### ISSUE TITLE
采用cookie登录能不能配置cookie有效domain和path

### ISSUE THREAD

**Issue by wangran99** [dromara/Sa-Token#507]
### 对以下问题有疑问:

采用cookie登录能不能配置cookie有效domain和path 

因为很多项目用nginx的同一个端口，默认cookie登录的path是/ ，期望cookie有效路径是前端的/mall-vue ，/chat-vue ，不同的前端路径有不同的cookie。

**Comment by ly-chn** [comment]
https://sa-token.cc/doc.html#/use/config

在这个页面搜"cookie"

**Comment by click33** [comment]
![Uploading image.png…]()

**Comment by click33** [comment]
![image](https://github.com/dromara/Sa-Token/assets/36243476/bd36493c-42fa-4af9-a886-c11f75e69d57)
