### ISSUE TITLE
spring-cloud-gateway:未能获取有效的上下文

### ISSUE THREAD

**Issue by feiyue** [dromara/Sa-Token#508]
### 使用版本:
1.35.0.RC

### 报错信息：
未能获取有效的上下文

### 复现步骤：
1、 SaReactorFilter 已经注册
2、sa-token-reactor-spring-boot-starter已经正确引入
3、没有开启：spring.main.lazy-initialization=true

我在spring-cloud-gateway模块中使用，问题是：我注册了一个GlobalFilter，里面使用了：StpUtil.isLogin()
如果Order设置为：Ordered.LOWEST_PRECEDENCE，就会频繁出现偶发异常。还不是必然出现。
如果设置为：Ordered.HIGHEST_PRECEDENCE,就正常。

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by feiyue** [comment]
springboot版本：2.6.3
spring-cloud版本：2021.0.1

**Comment by feiyue** [comment]
https://github.com/dromara/Sa-Token/issues/445
是否是一样的问题？

**Comment by click33** [comment]
微信已回复
