### ISSUE TITLE
对tokenSignList的一些疑惑

### ISSUE THREAD

**Issue by g9420** [dromara/Sa-Token#510]
### 对以下问题有疑问:
在SaSession类中的tokenSignList这个用来在内存中存储token的列表，当使用redis作为存储时，是否应该提供自动的机制保持token的统一，不然redis中的键已过期而tokenSignList却需要手动维护，目前仅仅是看到对外提供了一个`removeTokenSign(String tokenValue)`方法来手动删除token

![image](https://github.com/dromara/Sa-Token/assets/41284829/fc9a9ec9-0164-476a-9a46-f4b2b76fffa4)

**Comment by click33** [comment]
可以维护，但必要不是很大，这里只是记录一下历史 token 记录，具体一个 token 是否有效，还是要根据 StpUtil.getLoginIdByToken("token") 的返回结果来判断

**Comment by g9420** [comment]
您好，我有两个问题
1、维护这个token历史记录有什么用呢，过期的token还有记录的必要吗
2、如果做一个管理用户令牌的页面，管理同一个用户不同端的令牌，获取同一个用户所有的有效的令牌，是需要一 一 判断过期时间是吗

**Comment by AppleOfGray** [comment]
设想这样一种场景,某个用户登录后由于长时间没有操作,被框架标记为已过期. 此时如果用户又上线了, 携带了之前的token, 框架就可以从token历史记录里面判断当前token对应的用户已过期(而不是未登录状态),从而进行正确的反馈. 

关于你的第二个问题, 建议从这里寻找答案: https://sa-token.cc/doc.html#/up/search-session
