### ISSUE TITLE
单点登录系统设置token-prefix后无法登录

### ISSUE THREAD

**Issue by sunshio** [dromara/Sa-Token#514]
### 使用版本:
1.36.0

### 原因：
未配置token-prefix时，sa-token可以从cookies中到正确的token，但由于cookies中的tokenValue不存储前缀，导致当配置了token-prefix时，拿不到token。
### 解决办法：
重写SaStorageForServlet，原版是用request存取值，修改版则用session存取值，这样，登录成功后就可以在storage中拿到正确的token（因为storage中存了带前缀的token）
`@Bean
	public SaTokenContext getSaTokenContextForSpring() {
		return new SaTokenContextForSpring(){
			@Override
			public SaStorage getStorage() {
				return new SaStorageForServlet(SpringMVCUtil.getRequest()){
					public SaStorageForServlet set(String key, Object value) {
						this.request.getSession().setAttribute(key, value);
						return this;
					}

					public Object get(String key) {
						return this.request.getSession().getAttribute(key);
					}

					public SaStorageForServlet delete(String key) {
						this.request.getSession().removeAttribute(key);
						return this;
					}
				};
			}
		};
	}`

**Comment by sunshio** [comment]
`@SpringBootApplication(exclude = SaTokenContextRegister.class)`
```
@Bean
	public SaTokenContext getSaTokenContextForSpring() {
		return new SaTokenContextForSpring(){
			@Override
			public SaStorage getStorage() {
				return new SaStorageForServlet(SpringMVCUtil.getRequest()){
					public SaStorageForServlet set(String key, Object value) {
						this.request.getSession().setAttribute(key, value);
						return this;
					}

					public Object get(String key) {
						return this.request.getSession().getAttribute(key);
					}

					public SaStorageForServlet delete(String key) {
						this.request.getSession().removeAttribute(key);
						return this;
					}
				};
			}
		};
	}
```

**Comment by click33** [comment]
1、加了 token 前缀后 Cookie 失效在文档里有说明：
![image](https://github.com/dromara/Sa-Token/assets/36243476/5ff8fae3-6464-4b22-90e0-8e8a7cbc2852)

2、社区已有解决方案
https://gitee.com/sa-tokens/sa-token-three-plugin

3、你这个重写有问题，SaStorage 是数据在一次请求内范围有效，你这重写后直接成了一次会话范围内有效了。
![image](https://github.com/dromara/Sa-Token/assets/36243476/571bff2f-c412-474c-9155-627ca4cf8792)
参考：https://sa-token.cc/doc.html#/fun/three-scope
