### ISSUE TITLE
tokenName设置为"Cookie"时会导致判断登陆失败

### ISSUE THREAD

**Issue by danta1337** [dromara/Sa-Token#518]
### 使用版本:
1.36.0

### 报错信息：

如果设置tokenName为字符串"Cookie"，前端请求携带的Cookie请求头为：

`Cookie: Cookie=G3ryTh2K8SRK9GkKC55FLLLRBKC8mu8M1rcXCWXunevCDmqfasfyQISM3QOI7pl2; `

根据方法`cn.dev33.satoken.stp.StpLogic#getTokenValueNotCut`
按照现有的获取Cookie的顺序是：Storage -> 请求体 -> header -> Cookie
这样在获取header中的token时，最终获取的就会是

`Cookie=G3ryTh2K8SRK9GkKC55FLLLRBKC8mu8M1rcXCWXunevCDmqfasfyQISM3QOI7pl2`

只要某一步获取token成功就返回，所以不会再到Cookie中去获取，最终获取到的Token前面会多出"Cookie="的字符串，后续与已登陆数据的Cookie比对时就会失败（缓存中记录的已登陆的Cookie数据应该只有等号后面的字符串），最终判断当前用户未登陆

### 希望结果：

希望能在tokenName设置为"Cookie"时可以正确判断用户登录状态

### 复现步骤：

配置文件`application.properties`中设置tokenName为"Cookie"

`sa-token.token-name=Cookie`

使用HTTP请求模拟`login `和判断登陆`isLogin`，会判断登陆失败

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by danta1337** [comment]
不知道算不算是个问题，不过修改为其他tokenName就可以了

**Comment by click33** [comment]
Cookie 是浏览器限定的敏感字段，不允许自定义格式提交，不要设置为这个名字
