### ISSUE TITLE
能否通过配置文件为不同端配置不同的token过期时间？

### ISSUE THREAD

**Issue by Aaronsound** [dromara/Sa-Token#524]
### 对以下问题有疑问:

< 备注：请尽量详细描述问题所在 >
同一个账号，PC端和小程序登录使用不同的过期时间配置，能否通过配置文件来实现呢？

**Comment by ly-chn** [comment]
请参考[不同体系不同-satokenconfig-配置](https://sa-token.cc/doc.html#/up/many-account?id=_8%e3%80%81%e4%b8%8d%e5%90%8c%e4%bd%93%e7%b3%bb%e4%b8%8d%e5%90%8c-satokenconfig-%e9%85%8d%e7%bd%ae)
