### ISSUE TITLE
如何避免404的请求不被sa-token拦截鉴权

### ISSUE THREAD

**Issue by wangran99** [dromara/Sa-Token#525]
### 对以下问题有疑问:

目前设置了sa-token的拦截器，所有的请求，包括错误url的请求都不报404错误了，有什么办法让请求先判断是不是404，然后再鉴权。谢谢~

**Comment by ly-chn** [comment]
拦截器不会导致404被拦截吧, 你应该是配置了过滤器. 不妨发一下你的配置方式?

**Comment by GongLe** [comment]
和我遇到是类似问题？
具体如下：web或业务层抛出去RuntimeException后RestControllerAdvice无法捕获，白屏，控制台显示为
`org.springframework.web.util.NestedServletException: Request processing failed; nested exception`图一。
不知是否是satoken导致，默认satoken starter会装载哪些拦截器呢？

图一：
![image](https://github.com/dromara/Sa-Token/assets/1720495/1f07e392-4d0a-4601-845d-753d66d8ad4c)

**Comment by GongLe** [comment]
org.springframework.web.servlet.FrameworkServlet#processRequest
![image](https://github.com/dromara/Sa-Token/assets/1720495/9faace05-b3fc-4d8b-be6d-04b431196d7a)

**Comment by ly-chn** [comment]
@GongLe 你这是sa-token用法有误吧, 报错明显来自你自定义的jwt intercept, 并非sa-token所提供

**Comment by GongLe** [comment]
堆栈信息中确实没satoken的包，还没找到具体问题原因。。。

**Comment by GongLe** [comment]
> @GongLe 你这是sa-token用法有误吧, 报错明显来自你自定义的jwt intercept, 并非sa-token所提供

堆栈信息中确实没satoken的包，还没找到具体问题原因。。。/微笑

**Comment by wangran99** [comment]
配置文件：
![image](https://github.com/dromara/Sa-Token/assets/17898332/cffb188a-0fd0-4391-8758-bae008deb37e)
配置代码：
![image](https://github.com/dromara/Sa-Token/assets/17898332/100a7ebd-81ff-48ff-b159-63dac4c1ddcc)


本来应该404的请求，被satoken拦截了。希望404的请求不被拦截，返给前端404提示信息，或者说希望所有的404请求都不被satoken拦截到，如何实现，谢谢~

**Comment by ly-chn** [comment]
@wangran99 如果通过WebMvcConfigurer的Interceptors来实现, 可以尝试将/error接口放行. 因为404会跳转到这个地址

**Comment by wangran99** [comment]
> 

感谢，解决问题了 @ly-chn

**Comment by wangran99** [comment]
问题已解决。将WebMvcConfigurer中/error接口放行.404会跳转到这个地址。
![image](https://github.com/dromara/Sa-Token/assets/17898332/9bed6cf3-596e-44d8-9abf-4e5c95e5381d)

**Comment by liuzhihai520** [comment]
这个我尝试了，但是它任然跳转的是500页面，并且要报错notLoginException不知道还有没有更科学的解决方法？直接跳转404且错误日志不在后端打印？

**Comment by ly-chn** [comment]
> 这个我尝试了，但是它任然跳转的是500页面，并且要报错notLoginException不知道还有没有更科学的解决方法？直接跳转404且错误日志不在后端打印？

配置方式发一下

**Comment by liuzhihai520** [comment]
> > 这个我尝试了，但是它任然跳转的是500页面，并且要报错notLoginException不知道还有没有更科学的解决方法？直接跳转404且错误日志不在后端打印？
> 
> 配置方式发一下

public void addInterceptors(InterceptorRegistry registry) {

        // 注册路由拦截器，自定义认证规则
        registry.addInterceptor(new SaInterceptor(handler -> {
                    SaRouter.match("/**").check(r -> StpUtil.checkLogin());
                    SaRouter.match("/orders", r -> StpUtil.checkPermission("order:orderlist"));
                    SaRouter.match("/order/unifiedOrder", r -> StpUtil.checkPermission("order:addorder"));
                    SaRouter.match("/order/batchOrder", r -> StpUtil.checkPermission("order:batchorder"));
                    SaRouter.match("/order/drawBack", r -> StpUtil.checkPermission("order:orderlist"));
                    SaRouter.match("/order/orderDetails", r -> StpUtil.checkPermission("order:orderlist"));
                    SaRouter.match("/recharge/list", r -> StpUtil.checkPermission("recharge:list"));
                    SaRouter.match("/recharge/exts", r -> StpUtil.checkPermission("recharge:list"));
                    SaRouter.match("/recharge/orderstatus", r -> StpUtil.checkPermission("recharge:list"));
                    SaRouter.match("/recharge/rechargeOrder", r -> StpUtil.checkPermission("recharge:recharge"));
                }))
                .addPathPatterns("/**")
                .excludePathPatterns("/")
                .excludePathPatterns("/favicon.ico")
                .excludePathPatterns("/error")
                .excludePathPatterns("/captcha")
                .excludePathPatterns("/dologin")
                .excludePathPatterns("/core/**");
    }

当没有登陆，然后随便输入一个错误的url地址的时候就会触发500，而不是404

**Comment by ly-chn** [comment]
微服务吗, 到自己的子服务去加

**Comment by liuzhihai520** [comment]
> 微服务吗, 到自己的子服务去加 @liuzhihai520

感谢解答！
不是微服务，是springboot + satoken，我也知道是怎么回事，就是在没登录的时候，SaRouter.match("/**").check(r -> StpUtil.checkLogin()); 验证了404地址抛出的错误，但是我不知道怎么捕获，解决这个问题。

**Comment by ly-chn** [comment]
大致看了一下, 貌似sb3的匹配机制, 将ResourceHttpRequestHandler作为兜底了(不确定), 超出我能力范围了, 等作者解决吧. 如果你没有静态资源, 或不需要拦截静态资源, 可以暂时直接将静态资源放行: 

```java

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SaInterceptor(handle -> {
                    if (handle instanceof ResourceHttpRequestHandler) {
                        return;
                    }
                    SaRouter.match("any", StpUtil::checkLogin);
                }))
                .addPathPatterns("/**")
                .excludePathPatterns("/error")
    }

```

**Comment by carbon-projects** [comment]
我也有同样的问题，访问不存在的URL，抛出了notLoginException，并不会被捕获，也是跳/error 500了
