### ISSUE TITLE
微服务 - 内部服务外网隔离结合多账号认证

### ISSUE THREAD

**Issue by wly1456839489** [dromara/Sa-Token#531]
/**
 * Sa-Token 权限认证 配置类 
 */
@Configuration
public class SaTokenConfigure implements WebMvcConfigurer {
    // 注册 Sa-Token 全局过滤器 
    @Bean
    public SaServletFilter getSaServletFilter() {
        return new SaServletFilter()
                .addInclude("/**")
                .addExclude("/favicon.ico")
                .setAuth(obj -> {
                    // 校验 Same-Token 身份凭证     —— 以下两句代码可简化为：SaSameUtil.checkCurrentRequestToken(); 
                    String token = SaHolder.getRequest().getHeader(SaSameUtil.SAME_TOKEN);
                    SaSameUtil.checkToken(token);
                })
                .setError(e -> {
                    return SaResult.error(e.getMessage());
                })
                ;
    }
}

在这里怎么单独作区分啊，我已经有StpUserUtil了

**Comment by wly1456839489** [comment]
我现在带了user的token去访问子服务，提示401

**Comment by click33** [comment]
Same-Token 和会话 token 没有任何关系，你应该是对这两种 token 没理解透彻导致误用了
