### ISSUE TITLE
全局过滤器匹配规则问题

### ISSUE THREAD

**Issue by x-redefiner** [dromara/Sa-Token#532]
### 使用版本:
1.37.0

### 涉及的功能模块：
sa-token-reactor-spring-boot-starter
sa-token-spring-boot-autoconfig

### 测试步骤：
+ 我经过以下步骤测试：
微服务中 SaServletFilter 增加忽略.addExclude("/doc.html", "/**/*.html", "/**/*.css", "/**/*.js", "/**/api-docs/**")
网关中 SaReactorFilter 增加相同忽略
+ 得出以下结果：
网关中匹配规则无法生效
+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：
SaTokenContext接口的boolean matchPath(String var1, String var2);方法在两个包中实现不同导致匹配规则不一致。
+ 我的理解是：
文档中未标明匹配规则不同，是否应该源码中统一实现方法
请问，是我的理解不对，还是文档出了问题？

**Comment by wly1456839489** [comment]
大佬，想问一下你用了多账号认证了吗，你是怎么区分admin的token和user的token

**Comment by click33** [comment]
SaServletFilter 是在适配 SpringMVC
SaReactorFilter 是在适配 webflux
两者算法不一致，是因为 SpringMVC 和 webflux 的匹配算法不一致
sa-token 在适配谁，就跟着谁的算法来，
不然就容易因为 鉴权的匹配算法和Web框架的匹配算法不一致导致绕过鉴权
