### ISSUE TITLE
解析token获取value，并转换为指定类型，传入不存在的token报空指针错误

### ISSUE THREAD

**Issue by Red63** [dromara/Sa-Token#538]
### 使用版本:
1.37.0

### 报错信息：
SaTempUtil.parseToken(xxToken, T.class); JWT风格解析临时token的数据时，如果此token获取不到值时报空指针错误

**源代码出处：**

    public static Object getValue(String key, String jwtToken, String keyt) {
    	// 取出数据 
    	Claims claims = parseToken(jwtToken, keyt);	
    	// 验证是否超时 
    	Long eff = claims.get(KEY_EFF, Long.class);    //此处eff可能为null

        //此处判断null不合理eff != NEVER_EXPIRE引发java.lang.NullPointerException
    	if((eff == null || eff < System.currentTimeMillis()) && eff != NEVER_EXPIRE) {  
    		throw new SaTokenException("token 已超时，无法解析：" + jwtToken).setCode(SaTempJwtErrorCode.CODE_30303);
    	}
    	
        // 获取数据 
        return claims.get(KEY_VALUE + key);
    }

### 希望结果：
通过指定的临时token获取值应该抛出超时

//eff==null 优先判断
if(eff == null || (eff < System.currentTimeMillis() && eff != NEVER_EXPIRE)) {  
		throw new SaTokenException("token 已超时，无法解析：" + jwtToken).setCode(SaTempJwtErrorCode.CODE_30303);
	}

### 复现步骤：
SaTempUtil.parseToken(‘写入一个不存在的token时’, String.class);

**Comment by ly-chn** [comment]
收到, 谢谢
