### ISSUE TITLE
API 接口参数签名疑问

### ISSUE THREAD

**Issue by chenxiaolong8023** [dromara/Sa-Token#545]
### 对以下问题有疑问:
[API 接口参数签名](https://sa-token.cc/doc.html#/plugin/api-sign?id=api-%e6%8e%a5%e5%8f%a3%e5%8f%82%e6%95%b0%e7%ad%be%e5%90%8d)

< 备注：请尽量详细描述问题所在 >
只能对get和form表单内参数进行自动签名。但是现在post接口基本上都是json格式，通过body传参数，这部分无法自动签名和验签。

**Comment by ly-chn** [comment]
在大部分框架(不局限于java语言)中, 请求体不支持多次读取(如springboot会自动读取并解析一次), 因此无法支持任何请求体内容(即便是get请求的请求体)

相关资料, 请在搜索引擎检索关键词: `request body 多次读取`

**Comment by esdoner** [comment]
能够通过比如 springboot 的解析结果，手动覆盖到 SaHolder Request 里面嘛。

Map<String, String> params = SaHolder.getRequest().getParamMap();
params.put("name", model.getName);

比如这样也还是无效，最后校验的还是 servlet request 里的 不可变的 paramMap

**Comment by ly-chn** [comment]
@esdoner 你可以自定义HttpServletRequestWrapper来实现, 但优先级要高于你自定义的 sa-token interceptor或者 sa-token 的 filter. 主要是意义不大, 这种情况, 你的不如SaIgnore 后, 取出token 再参考cn.dev33.satoken.stp.StpLogic#getLoginIdDefaultNull定义一个自己的方法来实现, 虽然写起来麻烦, 但是你自定义的 wrapper可以多次使用
