### ISSUE TITLE
token在url中，与token-name 不一样，调用checkPermission方法

### ISSUE THREAD

**Issue by tjlizz** [dromara/Sa-Token#549]
### 对以下问题有疑问:

```java
sa-token:
  isReadCookie: false
  # token名称 (同时也是cookie名称)
  token-name: Authorization
```
上面是我在`application.yml`中的配置。

现在有这个一个需求，系统内有一个文件想要分享出去，这个分享链接也要进行权限认证。类似这样一个链接

`http://localhost/index.json?t=abcd123`

在`url`中`token`的名字不是`Authorization`而是`t`

这个方法内部调用了

```java
 StpUtil.checkPermission("data:read");
```

就会提示用户未登录。

请问有这方面的解决方法吗？我看了文档也没找到相关解决方法。

如果是我没找到，麻烦告诉我一下。如果不支持这种情况，那我就自己实现了。

谢谢！
< 备注：请尽量详细描述问题所在 >

**Comment by ly-chn** [comment]
无法同时支持多个tokenName, 你可以在自己的过滤器中将t写入到Authorization, 或者用其他方法实现;

另外这种场景更建议使用[临时token](https://sa-token.cc/doc.html#/plugin/temp-token?id=%e4%b8%b4%e6%97%b6token%e4%bb%a4%e7%89%8c%e8%ae%a4%e8%af%81)来实现
