### ISSUE TITLE
关于用户一个权限都没有的问题

### ISSUE THREAD

**Issue by zhihuishi-rain** [dromara/Sa-Token#551]
### 版本:
1.35.0

### 复现步骤：
cn.dev33.satoken.stp.StpLogic#checkPermissionAnd方法中调用的getPermissionList，当返回的权限码集合为空，用户一个权限都没有时也可以通过权限校验
![image](https://github.com/dromara/Sa-Token/assets/39619502/32dbc2b5-04fd-4dc8-9f8c-05a270de1c05)

**Comment by zhihuishi-rain** [comment]
使用的是注解鉴权，自己实现了StpInterface的getPermissionList方法，业务场景是没有给当前登录用户赋予任何角色和权限，角色码和权限码集合都为空的情况，这种情况下权限校验可以通过，正常应该无权限才对，毕竟我没给用户赋任何权限
![image](https://github.com/dromara/Sa-Token/assets/39619502/51164c59-dee1-462c-b9e5-9775318f5e13)
![image](https://github.com/dromara/Sa-Token/assets/39619502/59146202-97dc-41c9-b5db-949db19bf9d6)

**Comment by ly-chn** [comment]
StpUtil.getPermissionList()获取当前账号所拥有的权限集合看一下返回结果
