### ISSUE TITLE
StpLogic类中的方法checkLoginArgs中有一段是不是有

### ISSUE THREAD

**Issue by crescent99** [dromara/Sa-Token#561]
### 对以下问题有疑问:

< 备注：请尽量详细描述问题所在 >
![微信图片_20231227110656](https://github.com/dromara/Sa-Token/assets/59277855/8cdff6ad-3be8-41a7-8afe-abebd024f6b5)

这里extraData有值为什么还说StpLogic 不支持 extra 扩展参数模式？

**Comment by ly-chn** [comment]
extra为jwt所使用, 普通token请使用[session会话](https://sa-token.cc/doc.html#/use/session)
