### ISSUE TITLE
问题：关于 token伪造

### ISSUE THREAD

**Issue by Jason-We** [dromara/sa-token#57]
有个疑问：前后端分离项目中每次请求在header中携带token去后端校验。如果其他人获取到了有效登录后的token在拼接恶意请求，是不是就绕过了登录保护了？

**Comment by telanflow** [comment]
我感觉你这个问题 跟  别人获取了cookie一个道理。
我要是能获取别人的cookie 什么QQ空间、微博、知乎、百度贴吧、github 我都能进。

【淘宝、京东】这种网站支付的时候有其他的防护措施就不提了

**Comment by telanflow** [comment]
XSS / CSRF / 中间人 等攻击方式都可能获取到用户的 cookie 或 request header等其他客户端数据

XSS / CSRF 等主要就是代码来防范了，中间人攻击一般给网站加上 https 即可大概率防范（但是https可能会被恶意降级从而抓取http请求的明文数据）。
