### ISSUE TITLE
我想禁用cookie，但是配置了跨域禁用cookie之后没有什么用

### ISSUE THREAD

**Issue by TenXLL** [dromara/Sa-Token#570]
### 对以下问题有疑问:

< 备注：请尽量详细描述问题所在 >

**Comment by ly-chn** [comment]
你是否有必要重复描述一下自己的问题. 如果只看前半句的话, 我猜你的需求是"sa-token能否默认不处理cookie", 那么答案是: isReadCookie=false

**Comment by TenXLL** [comment]
谢谢，解决了

**Comment by TenXLL** [comment]
困扰了我好久
