### ISSUE TITLE
能否支持数据库替代redis

### ISSUE THREAD

**Issue by liu-xinhui** [dromara/Sa-Token#576]
### 应用场景阐述：
制造企业小公司，几百人使用的场景，token存数据库并发也是足够的。多引入redis，就增加了成本，还多一道风险，能否支持token持久化到数据库。

< 备注：请尽量详细描述功能应用场景 >

**Comment by ly-chn** [comment]
仅供参考: https://gitee.com/sa-tokens/sa-token-three-plugin/tree/master/sa-token-three-jdbc-fastjson2

**Comment by liu-xinhui** [comment]
@ly-chn 多谢
