### ISSUE TITLE
sa-token-dao-redis-jackson没有1.37.0版本吗

### ISSUE THREAD

**Issue by qinkangdeid** [dromara/Sa-Token#577]
### 使用版本:
1.34.0

### 涉及的功能模块：

sa-token-dao-redis-jackson

### 测试步骤：
+ 我经过以下步骤测试：

看到有最新版本 1.37.0 想升级依赖

+ 得出以下结果：

除了sa-token-dao-redis-jackson都有1.37.0版本 这个只有1.34.0版本
<img width="850" alt="image" src="https://github.com/dromara/Sa-Token/assets/17582522/9bc18151-ab73-4358-99d1-2b4f0139ec04">

+ 我的理解是：

sa-token生态组件统一版本号 类似一个bom清单版本 

请问，是我的理解不对，还是文档出了问题？

**Comment by ly-chn** [comment]
artifactId已调整, 详见更新日志, 新artifactId去掉了`-dao`
https://mvnrepository.com/artifact/cn.dev33/sa-token-redis-jackson
