### ISSUE TITLE
I want to use Scrypt since it seems to be the most secure in encrypting passwords, but it seems next impossible to implement.

### ISSUE THREAD

**Issue by ly-chn** [dromara/sa-token#58]
I'm really close with just going with a PBKDF2 since there is more documentation on it, but I'm hoping that there is someone out there who can help me get this going.
And I got it in Spring Security: org.springframework.security.crypto.scrypt.SCryptPasswordEncoder

**Comment by click33** [comment]
My friend, I'm sorry I didn't quite understand you. Could you describe your needs in more detail?

**Comment by xy-ly** [comment]
哦, 是的先生, 我想使用一些密码加密手段, 比如PBKDF2, Scrypt, Bcrypt等这些, 我看到了这些方法的实现, 在SpringbootSecurity中, 所以能否在SaToken中实现这些功能, 我想很多人会需要的, thank you

**Comment by click33** [comment]
请提交pr

**Comment by ly-chn** [comment]
You can't treat international friends like this !
