### ISSUE TITLE
JsonIgnore问题

### ISSUE THREAD

**Issue by yangbeibei69** [dromara/Sa-Token#585]
### 使用版本:
sa-token-redis-jackson、satoken：1.37.0

### 涉及的功能模块：
主体信息缓存到redis中时，部分字段使用了JsonIgnore注解，导致redis中序列化的主体json信息也没有该字段信息

### 测试步骤：
+ 我经过以下步骤测试：

+ 得出以下结果：

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：

+ 我的理解是：
采用JsonIgnore是为了数据返回前端时能够隐藏字段内容，但是后端使用此数据时应该希望是获取所有的字段数据
请问，是我的理解不对吗，或者有没有其他方式可以解决呢

**Comment by ly-chn** [comment]
理解没问题, 但是这个需求实现起来还是非常复杂的. 因为没法判断json是给前端的, 还是给redis的
可以尝试spring正常使用jackson序列化, 然后sa-token使用jdk或fastjson序列化, 这样sa-token序列化时就识别不到JsonIgnore注解了
