### ISSUE TITLE
框架配置timeout、activityTimeout和SaLoginModel类关系，使用疑问

### ISSUE THREAD

**Issue by Ryoui** [dromara/Sa-Token#605]
### 对以下问题有疑问:
登录时指定的SaLoginModel是否受框架配置中的timeout、activityTimeout影响，如
`StpUtil.login("10000", new SaLoginModel()
                    .setDevice(“web”)
                    .setTimeout(60 * 60 * 24 * 7));`
这里指定了7天，会收到timeout、activityTimeout配置的影响吗，比如timeout=1天，activityTimeout=30分钟。

**Comment by m18311155200** [comment]
首先，根据[2020-12-24 @v1.7.0](https://sa-token.cc/v/v1.33.0/doc.html#/more/update-log?id=_2020-12-24-v170)更新日志可以得知：activityTimeout控制token临时过期与续签功能，该参数不会影响到timeout的值，他们是两个不同的配置参数。
其次，根据[StpUtil - 鉴权工具类](https://sa-token.cc/v/v1.33.0/doc.html#/api/stp-util?id=stputil-%e9%89%b4%e6%9d%83%e5%b7%a5%e5%85%b7%e7%b1%bb)SaLoginModel 配置示例中的注释可以得知：如未在SaLoginModel指定timeout，自动取全局配置的 timeout 值，个人理解这句话变相意思就是SaLoginModel指定timeout优先于全局配置的 timeout 值。

**Comment by Ryoui** [comment]
@m18311155200 感谢，就是像确认SaLoginModel 设置的Timeout会受到框架配置里参数（timeout、activityTimeout）影响吗
