### ISSUE TITLE
关于微服务下Satoken和SameToken的验证疑问？

### ISSUE THREAD

**Issue by 1529084525** [dromara/Sa-Token#615]
### 对以下问题有疑问:

官方文档中对该问题进行了说明：
>与之类似的的报错还有：
SSO模式二时，报错：无效ticket：xxxxxxxxxx
OAuth2模块跨多个项目搭建Server时：报错无效 Access-Token：xxxxxx
微服务做分布式 Session 认证时，报错：无效 Token：xxxxxxxxx
等等等等....
这些功能有个统一的特点，就是需要多个项目连接同一个 Redis 才能搭建成功，如果连接的不是同一个 Redis，就会导致 Token / ticket 无法互相认证。

需要使用相同的redis才可以进行验证，但是可能出现每个子服务都不是一样的redis，所以导致 sametoken 无法验证，这应该如何解决？还是因为我文档阅读不够，

希望可以解答下。感谢/

**Comment by 1529084525** [comment]
不好意思，没有看到有这个
> [Sa-Token-Alone-Redis 独立Redis插件](https://sa-token.cc/doc.html#/plugin/alone-redis?id=sa-token-alone-redis-%e7%8b%ac%e7%ab%8bredis%e6%8f%92%e4%bb%b6)

我晚点试试看，

但是如果不分开可有方式解决该问题。

**Comment by click33** [comment]
要用 same-token 功能，必须连接同一个redis ，要么原生连  要么用 alone-redis 连  绕不过去的
