### ISSUE TITLE
多账号认证 OAuth2中 setSaOAuth2Config 中使用自定义StpUserUtil登录失效

### ISSUE THREAD

**Issue by clstech** [dromara/Sa-Token#620]
在 OAuth2中setSaOAuth2Config  使用多账号认证的StpUserUtil.login登录不会直接返回SaResult.ok()，而不会走重写 Access-Token 生成策略randomAccessToken，默认的StpUtil.login则正常

**Comment by AsheSSS** [comment]
> 在 OAuth2中setSaOAuth2Config 使用多账号认证的StpUserUtil.login登录不会直接返回SaResult.ok()，而不会走重写 Access-Token 生成策略randomAccessToken，默认的StpUtil.login则正常

我也遇到了这个问题，大佬是怎么解决的？
