### ISSUE TITLE
权限注解支持自定义注解包含权限注解

### ISSUE THREAD

**Issue by kliuyu07** [dromara/Sa-Token#646]
### 建议增加的新功能:
像spring security那样，支持自定义注解包含权限注解

### 应用场景阐述：
@SaCheckLogin
@SaCheckRole("admin")
@SaCheckPermission("user.add")
@RequestMapping("test")
public SaResult test() {
    // ... 
    return SaResult.ok(); 
}

自定义注解
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@SaCheckLogin
@SaCheckRole("admin")
@SaCheckPermission("user.add")
public @interface AdminAuthorized {
}

@AdminAuthorized
@RequestMapping("test")
public SaResult test() {
    // ... 
    return SaResult.ok(); 
}

可以把所需的权限提到一个注解里面，因为相同的权限会在很多个方法用到，如果每个方法都添加几个多个注解的话，不方便维护权限

**Comment by click33** [comment]
重写一下注解处理器即可
https://sa-token.cc/doc.html#/up/many-account?id=_7%e3%80%81%e4%bd%bf%e7%94%a8%e6%b3%a8%e8%a7%a3%e5%90%88%e5%b9%b6%e7%ae%80%e5%8c%96%e4%bb%a3%e7%a0%81
