### ISSUE TITLE
获取会话信息后根据SaSession只能支持timeOut时间，是否可以增加获取activeTimeOut

### ISSUE THREAD

**Issue by superZhouDaLu** [dromara/Sa-Token#649]
### 建议增加的新功能:
SaSession获取`activeTimeOut`方法，或者StpUtil增加`getTokenActiveTimeoutByToken`方法。

### 应用场景阐述：
获取会话列表无法得知用户最后操作时间

**Comment by click33** [comment]
StpUtil.stpLogic.getTokenActiveTimeoutByToken()
