### ISSUE TITLE
角色和权限怎么添加的

### ISSUE THREAD

**Issue by panzhangbao** [dromara/sa-token#65]
我知道校验角色和权限，
问题事怎么增加角色和权限，这里的角色和权限数据存储到哪里去了？总不能自己定义角色和权限吧。
比如某个用户，如何给他授予角色和权限？

**Comment by panzhangbao** [comment]
看到了，这个跟自己业务有关系。谢啦
http://sa-token.dev33.cn/doc/index.html#/use/jur-auth

**Comment by click33** [comment]
😏😏😏
