### ISSUE TITLE
设置了同一账号可同时登录依旧被踢下线

### ISSUE THREAD

**Issue by objectboy2016** [dromara/Sa-Token#657]
### 使用版本:
1.38.0

### 报错信息：
账号被踢下线,   是偶尔, 不是立即

### 复现步骤：

sa-token: 
            token-name: manage-token 
            timeout: 7200 
            active-timeout: 7200 
            is-concurrent: true 
            is-share: true 
            token-style: simple-uuid 
            is-log: false

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ZyRiven** [comment]
请问解决了吗，我是一直被挤掉线
