### ISSUE TITLE
校验角色和权限注解无效

### ISSUE THREAD

**Issue by panzhangbao** [dromara/sa-token#66]
@SaCheckRole("admin")
@SaCheckPermission("user")
我在Controller上测试的，无效，而且也不走自定义权限验证接口扩展

@Component
public class StpInterfaceImpl implements StpInterface {
 /**
     * 返回一个账号所拥有的权限码集合
     */
    @Override
    public List<String> getPermissionList(Object loginId, String loginKey) {

        // TODO 查询数据库

        // 本list仅做模拟，实际项目中要根据具体业务逻辑来查询权限
        List<String> list = new ArrayList<String>();
        list.add("101");
        list.add("user-add");
        list.add("user-delete");
        list.add("user-update");
        list.add("user-get");
        list.add("article-get");
        return list;
    }

    /**
     * 返回一个账号所拥有的角色标识集合 (权限与角色可分开校验)
     */
    @Override
    public List<String> getRoleList(Object loginId, String loginKey) {
        return Arrays.asList("a");
    }

**Comment by click33** [comment]
sa-token内置两种模式完成注解鉴权，分别是AOP模式和拦截器模式, 为了避免不必要的性能浪费，这两种模式默认都处于关闭状态
因此如若使用注解鉴权，你必须选择其一进行注册

确保你选择其一进行注册了吗

**Comment by panzhangbao** [comment]
好的，可以了，谢谢了，之前只是用了SaRouteInterceptor，没用SaAnnotationInterceptor，现在2个一起使用，统一验证和注解验证都可以了
