### ISSUE TITLE
sa-token 是否会推出OIDC协议 实现的案例呢

### ISSUE THREAD

**Issue by mocha666** [dromara/Sa-Token#666]
### 建议增加的新功能:
OAuth2 的 OIDC协议的功能扩展实现 

### 应用场景阐述：
目前对接很多第三方系统的话 ，使用 OIDC 的来实现的场景是非常多的 ，对多个系统系统进行 SSO 改造 对在线任务也会有一定的影响

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
后续版本会逐步实现的

**Comment by mocha666** [comment]
目前的话 有相关的参考案例嘛    。自己搞的时候不知如何只用这个依赖来实现

**Comment by click33** [comment]
你可以通过重写一些接口的返回值，追加上这个逻辑，但是目前没有相关案例

**Comment by click33** [comment]
敬请期待后续版本

**Comment by mocha666** [comment]
好的  ，狠狠的期待下了  ，完善了OIDC  就可以放弃 spring security 了

**Comment by click33** [comment]
https://sa-token.cc/doc.html#/oauth2/oauth2-oidc
