### ISSUE TITLE
oauth2 - 密码登录 PasswordGrantTypeHandler 不支持自定义错误信息

### ISSUE THREAD

**Issue by yuenwk** [dromara/Sa-Token#676]
### 使用版本:
1.39.0

### 涉及的功能模块：
oauth2

### 测试步骤：
+ 我经过以下步骤测试：登录处理函数中，结果通过 `SaResult` 包装（如用户名密码或错误）返回，
  但 `PasswordGrantTypeHandler` 中未处理该结果，会直接抛出异常`登录失败`比较**含糊**。

+ 其中 PasswordGrantTypeHandler 的代码：
  ```java
          // 3、调用API 开始登录，如果没能成功登录，则直接退出
          loginByUsernamePassword(username, password);
          Object loginId = StpUtil.getLoginIdDefaultNull();
          if(loginId == null) {
              throw new SaOAuth2Exception("登录失败");
          }
  ```

+ 我的理解是：在 `SaOAuth2ServerConfig.doLoginHandle` 方法中直接抛出异常也是一种办法。
  但`SaOAuth2ServerProcessor.doLogin`中也会使用该方法，所以优先处理 `SaResult` 返回错误比较合理。

**Comment by click33** [comment]
直接抛异常吧
