### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by camaker** [dromara/Sa-Token#677]
### 应用场景阐述：

有计划支持做国际化吗？
比如：

SaOAuth2Template.java 代码里

![image](https://github.com/user-attachments/assets/f81f2f74-bd42-4ec0-87d5-c95801227c07)

抛出的异常里有写死的中文提示

< 备注：请尽量详细描述功能应用场景 >

**Comment by click33** [comment]
你可以根据异常的 Code 值，自定义返回信息 
参考：https://sa-token.cc/doc.html#/fun/exception-code
