### ISSUE TITLE
oauth模块  oidc 在application.yml 中 sa-token.oauth2-server.oidc 项的值不会生效   

### ISSUE THREAD

**Issue by mocha666** [dromara/Sa-Token#681]
### 使用版本:
sa-token 1.39.0 

在application.yml 中 sa-token.oauth2-server.oidc 项的值不会生效   

配置中的 
<img width="255" alt="image" src="https://github.com/user-attachments/assets/dddb01eb-9162-4625-91b5-471189cd1f7f">

实际解析 id_token 得到的载荷
![image](https://github.com/user-attachments/assets/1e11e23a-ca5a-4f33-bd95-868851fead8f)

### 预期结果：
容器化的 一个账户自有中心中运行，环境下 前方还有waf 与代理 ，

发现自动获取的iss网址  是协议头与 这里获取的iss不一致，这里直接获取的  iss 与像是在服务中所获取的一个iss ， 与实际客户端上获取的 iss 不一致 导致异常，我尝试在  配置文件 sa-token.oauth2-server.oidc 项中添加  iss 以固定 iss， 但实际是没有生效

**Comment by mocha666** [comment]
<img width="412" alt="image" src="https://github.com/user-attachments/assets/b8d9f20a-066f-450a-951b-5b15ec9da2c7">
另外我尝试在  定制化配置中添加 setOidc 方法  ，重新设置 SaOAuth2OidcConfig 也无法将这个变成 https

**Comment by click33** [comment]
应该是源码bug了，你暂时可以通过重写 OIDC 的 Scope 处理器，然后重写 getIss 方法，下个版本我们将修复此问题
``` java
@Component
public class CustomOidcScopeHandler extends OidcScopeHandler {

    @Override
    public String getIss() {
        // 返回配置的 iss 值
        return SaOAuth2Manager.getServerConfig().getOidc().getIss();
    }

}
```

**Comment by mocha666** [comment]
> 应该是源码bug了，你暂时可以通过重写 OIDC 的 Scope 处理器，然后重写 getIss 方法，下个版本我们将修复此问题
> 
> ```java
> @Component
> public class CustomOidcScopeHandler extends OidcScopeHandler {
> 
>     @Override
>     public String getIss() {
>         // 返回配置的 iss 值
>         return SaOAuth2Manager.getServerConfig().getOidc().getIss();
>     }
> 
> }
> ```

收到 已经通过重写该项进行恢复，后续更新的话 这边在进行尝试   新的版本
