### ISSUE TITLE
Whether to support springboot3+redis ？

### ISSUE THREAD

**Issue by jingbio** [dromara/Sa-Token#688]
### 对以下问题有疑问:
For the latest version of springboot3, the official website does not provide redis configuration instructions.

If you use the configuration provided on the official website, an error will be reported. Because springboot3 will add the data prefix to the redis configuration by default.
For example：

spring:
  data:
    redis:
      host: 19xxx
      port: 6379
      database: 14
      timeout: 3000
      connectTimeout: 5000
      password: xxx

**Comment by click33** [comment]
Yes, we will mention this in future versions of the document to remind more users to pay attention

**Comment by click33** [comment]
支持
