### ISSUE TITLE
请问如何实现指定的token对应指定的loginId？

### ISSUE THREAD

**Issue by xujimu** [dromara/Sa-Token#689]
我有一个管理系统使用的 spring boot + satoken前端发过来账号密码,简单的使用StpUtil.login(userId) 进行登录
现在我需要再加一个永不过期的token 每个用户都有唯一的token 他不需要用户登录去换取token 直接携带token就可以访问需要登录的资源 而且可以调用StpUtil.getLoginIdAsString()方法 类似于调用API所需要accessToken

**Comment by ly-chn** [comment]
目前来说没有办法固定Token, 不过你可以在登录校验时, 如果发现token过期, 就重新登录一下这个用户

如: 

	/**
	 * 注册 Sa-Token 拦截器打开注解鉴权功能  
	 */
	@Override
	public void addInterceptors(InterceptorRegistry registry) {
		// 注册 Sa-Token 拦截器打开注解鉴权功能 
		registry.addInterceptor(new SaInterceptor(any -> {
			// 未登录, 且是固定token, 则自动登录
			if (!StpUtil.isLogin()) {
				String userToken = StpUtil.getTokenValue();
				if (Arrays.asList("固定token, 可能来自数据库或其他配置文件等", "固定token2", "固定token3").contains(userToken)) {
					StpUtil.login("对应用户id", new SaLoginModel().setToken(userToken));
				}
			}
			// 正常校验登录
			StpUtil.checkLogin();
		})).addPathPatterns("/**");
	}
