### ISSUE TITLE
sa-token-demo-jwt is not completed.

### ISSUE THREAD

**Issue by GavynG** [dromara/sa-token#69]
Version: sa-token 1.6.0   [38bfb45](https://github.com/dromara/sa-token/commit/38bfb45b26c77f30ad78ca0aaebc852e6df809fb)

URL:http://localhost:8081/test/test 
error:  
    `cn.dev33.satoken.exception.SaTokenException: jwt has not session
	    at com.pj.satoken.jwt.SaTokenJwtUtil$1.getSessionBySessionId(SaTokenJwtUtil.java:164)
	    at cn.dev33.satoken.stp.StpLogic.getTokenSession(StpLogic.java:661)
	    at cn.dev33.satoken.stp.StpLogic.getTokenSession(StpLogic.java:669)
	    at cn.dev33.satoken.stp.StpUtil.getTokenSession(StpUtil.java:313)
	    at com.pj.test.TestJwtController.test(TestJwtController.java:74)
	    …………`

访问/test/test接口时，会导致上述异常抛出，按理jwt整合时，不应调用session相关接口吧。希望能更新一下jwt整合的demo，多谢！
It seems StpUtil.getTokenSession() and StpUtil.logoutByLoginId() both cause the exception. As mentioned in the document,session should be disabled in the jwt-mode.
```	
       // 测试   浏览器访问： http://localhost:8081/test/test
	@RequestMapping("test")
	public AjaxJson test() {
		StpUtil.getTokenSession().logout();
		StpUtil.logoutByLoginId(10001);
		return AjaxJson.getSuccess();
	}
```

**Comment by click33** [comment]
参考官网常见问题解答 
![image](https://user-images.githubusercontent.com/36243476/114347372-6ada7200-9b97-11eb-8522-406e29c742ca.png)

**Comment by GavynG** [comment]
> 
> 
> 参考官网常见问题解答
> ![image](https://user-images.githubusercontent.com/36243476/114347372-6ada7200-9b97-11eb-8522-406e29c742ca.png)

谢谢回复！
我是看见FAQ里这个解答后才有这个疑问，就是demo应该是能跑通的吧，但现在demo里的test/test接口会抛异常，demo里这段代码是否不应该调用StpUtil.getTokenSession()？
我现在不知道logout该用什么方法。

**Comment by click33** [comment]
注销直接 StpUtil.logout() 就行了
StpUtil.getTokenSession() 没法调用 这是人为做的限制 你也可以找到那行代码去掉 不过去掉也没啥意义 用了jwt再用session说明架构选型有点不太合适 ，示例里那么些就是为了演示这个API不可用的

**Comment by GavynG** [comment]
> 
> 
> 注销直接 StpUtil.logout() 就行了
> StpUtil.getTokenSession() 没法调用 这是人为做的限制 你也可以找到那行代码去掉 不过去掉也没啥意义 用了jwt再用session说明架构选型有点不太合适 ，示例里那么些就是为了演示这个API不可用的

好的，明白了，demo里加点注释会更容易理解。 :)
谢谢！
