### ISSUE TITLE
授权码模式登录成功之后没有携带code重定向到redirect_uri

### ISSUE THREAD

**Issue by caixiaomao** [dromara/Sa-Token#708]
### 使用版本:
1.39.0
springboot 3.4.0

### 涉及的功能模块：
sa-token-oauth2

### 测试步骤：
+ 我经过以下步骤测试：
使用授权码模式访问，跳转到登录页输入用户名和密码登录，没有携带code重定向到redirect_uri地址，请问问题可能出在哪里？
+ 得出以下结果：

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：

+ 我的理解是：

请问，是我的理解不对，还是文档出了问题？

**Comment by click33** [comment]
官网仓库demo能运行成功吗

**Comment by caixiaomao** [comment]
> 官网仓库demo能运行成功吗

已解决，配置问题，感谢

**Comment by ares54321** [comment]
请问是怎么解决的，我也有同样的问题，登录成功不跳转也不报错！！

**Comment by ares54321** [comment]
哦 跟踪了一下代码，是因为把is-read-cookie设为了false导致拿不到token
