### ISSUE TITLE
能不能增加一个仅使用activity-timeout模式的选项？

### ISSUE THREAD

**Issue by VanMesure** [dromara/sa-token#80]
目前有两个决定token有效期的参数
spring.sa-token.timeout=2000

spring.sa-token.activity-timeout=100

我设置了activity-timeout，但是时间到达timeout的时候，即便用户一直操作，那么token也还是会过期。

可不可以选择只使用activity-timeout呢？

**Comment by click33** [comment]
spring.sa-token.timeout 设置成-1
