### ISSUE TITLE
定时清理过期Token功能中刷新标识存在可见性问题

### ISSUE THREAD

**Issue by jh-wong** [dromara/sa-token#82]
SaTokenDaoDefaultImpl中refreshFlag属性在线程中进行了判断，initRefreshThread()方法一开始赋值为true，后续可以根据endRefreshThread()方法调整refreshFlag变量的值，达到关闭清理数据效果，但是实现上可能存在可见性问题，因为refreshFlag属性并没有使用volidate修饰

**Comment by click33** [comment]
可以加上volidate关键字 算是一个可优化点
