### ISSUE TITLE
"开发文档" 页面无法正常打开

### ISSUE THREAD

**Issue by jxlion** [dromara/sa-token#85]
打开后的页面，如下：

![image](https://user-images.githubusercontent.com/51905592/119116012-689ee980-ba5a-11eb-890e-581659bb8c28.png)

从F12控制台可看到如下关键信息：

![image](https://user-images.githubusercontent.com/51905592/119116313-b3b8fc80-ba5a-11eb-9812-28ea2b5804c9.png)

我的操作系统是windows10。

**Comment by click33** [comment]
可能是网络波动
