### ISSUE TITLE
可否在配置文件中配置全局的校验模式

### ISSUE THREAD

**Issue by YoungTakhin** [dromara/Sa-Token#91]
默认的校验模式是AND，但如果因业务需要，需要的校验模式是OR，则需要在所有@SaCheckRole和@SaCheckPermission注解中设置，代码侵入性过大，因此可否在配置文件中配置全局的校验模式，在注解中配置的校验模式只对当前方法生效

**Comment by click33** [comment]
可以考虑

**Comment by YoungTakhin** [comment]
您好，请问这个功能提上里程碑了吗？

**Comment by click33** [comment]
暂时还没，这个需求比较小众，如果社区提到的人比较多，会考虑集成
如果提的人不多，还是自己来实现吧
另外，多账号体系章节的 [注解合并] 可能会给你一些帮助
http://sa-token.dev33.cn/doc/index.html#/up/many-account?id=_5%e3%80%81%e4%bd%bf%e7%94%a8%e6%b3%a8%e8%a7%a3%e5%90%88%e5%b9%b6%e7%ae%80%e5%8c%96%e4%bb%a3%e7%a0%81
