### ISSUE TITLE
可否实现不同的设备登录TOKEN 有不同的活动时间

### ISSUE THREAD

**Issue by mylvlin** [dromara/Sa-Token#97]
RT  比如APP 登录 可能需要30天不过期 或一直有效 ，但是WEB登录只需要30分钟没操作就过期，30分钟内操作就可以一直续期，目前activityTimeout 是对整个系统的起效的 不是针对DEVICE的

**Comment by click33** [comment]
让前端在web端控制一下token有效期就好了
