### ISSUE TITLE
Spring WebFlux 和SpringCloudGateway包有冲突

### ISSUE THREAD

**Issue by wait153** [dromara/Sa-Token#98]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.web.embedded.netty.NettyWebServer.<init>(NettyWebServer.java:86)

The following method did not exist:

    reactor.netty.http.server.HttpServer.channelGroup(Lio/netty/channel/group/ChannelGroup;)Lreactor/netty/http/server/HttpServer;

The method's class, reactor.netty.http.server.HttpServer, is available from the following locations:

    jar:file:/Users/li/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.5.RELEASE/reactor-netty-0.9.5.RELEASE.jar!/reactor/netty/http/server/HttpServer.class

The class hierarchy was loaded from the following locations:

    reactor.netty.http.server.HttpServer: file:/Users/li/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.5.RELEASE/reactor-netty-0.9.5.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of reactor.netty.http.server.HttpServer

**Comment by wait153** [comment]
<dependencies>

        <dependency>
            
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-reactor-spring-boot-starter</artifactId>
            <version>${sa-token-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-temp-jwt</artifactId>
            <version>1.22.0</version>
        </dependency>
    </dependencies>

**Comment by click33** [comment]
应该不是Sa-Token的问题 
另外，提供的信息太少，至少把SpringCloud的版本亮出来
最好来个复现demo
